### ISSUE TITLE
bvec file mismatch when DSI studio src file generating

### ISSUE THREAD

**Issue by weiwei-wch** [PennLINC/qsiprep#137]
Hi @mattcieslak 
     I preprocessed a multi-shelled DTI data with qsiprep 0.8.0, everything is fine in the begining, while when src file generating the program report errors and stoped, here is the log:

```
Node: qsiprep_wf.single_subject_TEST001_wf.dwi_finalize_acq_multishell_run_02_wf.transform_dwis_t1.calculate_qc.raw_src
Working directory: /work/qsiprep_wf/single_subject_TEST001_wf/dwi_finalize_acq_multishell_run_02_wf/transform_dwis_t1/calculate_qc/raw_src

Node inputs:

args = <undefined>
environ = {}
grad_dev = <undefined>
input_b_table_file = <undefined>
input_bvals_file = <undefined>
input_bvecs_file = <undefined>
input_dicom_dir = <undefined>
input_nifti_file = <undefined>
nthreads = 1
output_src = <undefined>
recursive = <undefined>
subject_id = <undefined>
test_trait = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 397, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 792, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 723, in raise_exception
    ).format(**runtime.dictcopy())
RuntimeError: Command:
dsi_studio --action=src  --bval=/work/qsiprep_wf/single_subject_TEST001_wf/dwi_finalize_acq_multishell_run_02_wf/transform_dwis_t1/rotate_gradients/rotated.bval --bvec=/work/qsiprep_wf/single_subject_TEST001_wf/dwi_finalize_acq_multishell_run_02_wf/transform_dwis_t1/rotate_gradients/rotated.bvec --source=/work/qsiprep_wf/single_subject_TEST001_wf/dwi_finalize_acq_multishell_run_02_wf/transform_dwis_t1/merge/vol0000_trans_merged.nii --threads=1 --output=/work/qsiprep_wf/single_subject_TEST001_wf/dwi_finalize_acq_multishell_run_02_wf/transform_dwis_t1/calculate_qc/raw_src/vol0000_trans_merged.src.gz
Standard output:
DSI Studio Jan 25 2020, Fang-Cheng Yeh
source=/work/qsiprep_wf/single_subject_TEST001_wf/dwi_finalize_acq_multishell_run_02_wf/transform_dwis_t1/merge/vol0000_trans_merged.nii
action=src
output=/work/qsiprep_wf/single_subject_TEST001_wf/dwi_finalize_acq_multishell_run_02_wf/transform_dwis_t1/calculate_qc/raw_src/vol0000_trans_merged.src.gz
image=/work/qsiprep_wf/single_subject_TEST001_wf/dwi_finalize_acq_multishell_run_02_wf/transform_dwis_t1/merge/vol0000_trans_merged.nii
loading
bval=/work/qsiprep_wf/single_subject_TEST001_wf/dwi_finalize_acq_multishell_run_02_wf/transform_dwis_t1/rotate_gradients/rotated.bval
bvec=/work/qsiprep_wf/single_subject_TEST001_wf/dwi_finalize_acq_multishell_run_02_wf/transform_dwis_t1/rotate_gradients/rotated.bvec
mismatch between bvec file and the loaded images
Warning: --threads is not used. Please check command line syntax.
Standard error:

Return code: 1
```
I checked the vol0000_trans_merged.nii and rotated bvec file and the size is matched (99 = 33*3)
A old version of dsi studio (2018/6/27) on windows can successfully generated the src file

**Comment by mattcieslak** [comment]
Hi @weiwei-wch, could you post the contents of `/work/qsiprep_wf/single_subject_TEST001_wf/dwi_finalize_acq_multishell_run_02_wf/transform_dwis_t1/rotate_gradients/rotated.bvec`? This might be fixed in 0.9.0 already

**Comment by weiwei-wch** [comment]
sure, follows are the bvec contents:
```
0.00000000 0.76901967 0.00958008 0.25573973 0.70847898 0.42638187 0.45066323 0.52165785 -0.62647184 0.06306038 0.76834499 -0.43463125 -0.33504184 0.88299630 0.49198298 0.28350467 0.76815949 0.00912006 0.56908245 -0.84945948 -0.66027126 -0.41876149 -0.90753322 -0.63609928 0.81472577 0.07337951 -0.71921218 0.61545708 0.35466012 -0.46098734 0.86236354 0.31932108 0.41488508
-0.00000000 0.02639999 0.91888754 0.68565928 0.68417902 -0.58850258 -0.16746120 0.80567669 0.74525980 -0.17668108 0.51334333 0.89336669 0.71658394 -0.46849804 -0.62586379 0.72073188 -0.44047971 -0.57556409 0.43818188 -0.23848266 0.65882525 -0.36736482 0.21984272 -0.04870056 0.45049213 0.98435347 0.30500262 0.57023730 0.93278032 -0.06154071 -0.19246079 0.71964244 0.14422177
0.00000000 -0.63867972 -0.39440324 -0.68151929 0.17307975 -0.68692301 -0.87684628 -0.28063885 0.22829994 -0.98224599 -0.38226248 -0.11398085 -0.61176337 0.02875988 -0.60518366 -0.63259043 -0.46465969 -0.81770581 -0.69580299 -0.47068525 -0.36054287 -0.83047089 -0.35784442 -0.77006881 0.36507363 -0.16019894 -0.62426536 0.54409742 0.06432002 -0.88527025 -0.46828192 0.61656209 -0.89837100
```
This problem was fixed when I cut one slice of dwi file to make number of slice in z-dimension to be even, which suggested that the mismatch problem was caused by topup since it could not work with its default setting when silce number was odd, but it still makes me confusing because the crash was happened in dsi-studio part.
Now I change the scan squence to make the slice even in the begining and running qsiprep pepiline to see if it can finish sucessfully, when preprocessing ends I can report the results here.

**Comment by mattcieslak** [comment]
In qsiprep you can have even or odd numbers of slices and TOPUP will be run with a configuration that will work. I suggest running with unaltered images

**Comment by weiwei-wch** [comment]
Thanks for your suggestion, so I should configure my own 'eddy_params,json' file?, I do not see a topup configuration description in https://qsiprep.readthedocs.io/en/latest.

**Comment by mattcieslak** [comment]
The topup configuration is automatically created based on the phase encoding directions of your scans and any available fieldmaps. I'm realizing now that there is not a good description of how this works in the documentation. If you run qsiprep with eddy and EPI fieldmaps (or two DWI series with opposite phase encoding directions) the html report will tell you where the images used in topup come from. For example, here is a report from a HCP Lifespan run:

```
TOPUP Inputs

A total of 2 distortion groups were included in the combined DWI series data. Distortion group '0 1 0 0.095910' was represented by images 0, 81 from /bids_dataset/sub-3046/ses-1/dwi/sub-3046_ses-1_acq-98_dir-PA_run-02_dwi.nii.gz and image 81 from /bids_dataset/sub-3046/ses-1/dwi/sub-3046_ses-1_acq-99_dir-PA_run-04_dwi.nii.gz. Distortion group '0 -1 0 0.095910' was represented by images 0, 81 from /bids_dataset/sub-3046/ses-1/dwi/sub-3046_ses-1_acq-98_dir-AP_run-01_dwi.nii.gz and image 81 from /bids_dataset/sub-3046/ses-1/dwi/sub-3046_ses-1_acq-99_dir-AP_run-03_dwi.nii.gz. A total of 2 distortion groups were included in the EPI fieldmap data. Distortion group '0 -1 0 0.059741' was represented by images 0, 1, 2 from /bids_dataset/sub-3046/ses-1/fmap/sub-3046_ses-1_dir-AP_epi.nii.gz. Distortion group '0 1 0 0.059741' was represented by images 0, 1, 2 from /bids_dataset/sub-3046/ses-1/fmap/sub-3046_ses-1_dir-PA_epi.nii.gz. 
```

**Comment by weiwei-wch** [comment]
So I am still unable to configure command for topup, since in FSL 6.0.3, topup still could not work well with an odd-slicing dwi file if "--subsamp 1" is not added, which is confusing since it is the default value. now I already chage the scan sequence so I am not facing this problem, but I hope this could help you somehow. Thanks for your patient replay.
