### ISSUE TITLE
ValueError: Field of view of image #1 is different from reference FOV

### ISSUE THREAD

**Issue by IRuotsa** [PennLINC/qsiprep#225]
Thanks for making qsiprep! I have a single-shell dwi dataset and it is acquired in 2 opposite phase-encoding directions. The preprocessing for some of my subjects did not execute cleanly and I got an error message (please see below).

I’m not completely sure, but I assume that there might be an issue that "ImageOrientationPatientDICOM" are not exactly same for both phase-encoding directions for some subjects. Do you think this might be the case? If so, is there a way to force the analysis, even though there is a tiny difference in the image orientation?

Here’s an example of ImageOrientationPatientDICOMs for subject that did not execute cleanly:
```
"PhaseEncodingDirection": "j",
"ImageOrientationPatientDICOM": [
		0.999819,
		0.0178492,
		0.00652408,
		-0.0115176,
"PhaseEncodingDirection": "j-",
"ImageOrientationPatientDICOM": [
		0.999819,
		0.017844,
		0.00652737,
		-0.0115115,
```

`singularity run --cleanenv /usr/local/qsiprep/qsiprep-0.13.0RC1.sif --participant_label 059 --denoise-method dwidenoise --unringing-method mrdegibbs --hmc_model eddy --fs-license-file /Path/bids_folder/sourcedata/license.txt --output_resolution 1 --notrack -w /Path/qsiprep_work /Path/bids_folder /Path/bids_folder/derivatives/ participant`

Error message: 
```
Node: qsiprep_wf.single_subject_059_wf.dwi_preproc_wf.pre_hmc_wf.raw_rpe_concat
Working directory: /Path/qsiprep_work/qsiprep_wf/single_subject_059_wf/dwi_preproc_wf/pre_hmc_wf/raw_rpe_concat

Node inputs:

compress = True
dtype = f4
header_source = <undefined>
in_files = <undefined>
is_dwi = True

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 434, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/interfaces/nilearn.py", line 133, in _run_interface
    new_nii = concat_imgs(self.inputs.in_files, dtype=self.inputs.dtype)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nilearn/_utils/niimg_conversions.py", line 459, in concat_niimgs
    memory=memory, memory_level=memory_level))):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nilearn/_utils/niimg_conversions.py", line 150, in _iter_check_niimg
    niimg.shape))
ValueError: Field of view of image #1 is different from reference FOV.
Reference affine:
array([[-1.99963880e+00, -2.30352096e-02,  3.02324779e-02,
         1.12514862e+02],
       [-3.56983095e-02,  1.68438005e+00, -1.07777059e+00,
        -6.68360977e+01],
       [ 1.30481552e-02,  1.07811558e+00,  1.68448699e+00,
        -9.98553925e+01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])
Image affine:
array([[-1.99963892e+00, -2.30229255e-02,  3.02324407e-02,
         1.12514229e+02],
       [-3.56879421e-02,  1.68438029e+00, -1.07777059e+00,
        -6.68367004e+01],
       [ 1.30547462e-02,  1.07811558e+00,  1.68448699e+00,
        -9.98557663e+01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])
Reference shape:
(106, 106, 70)
Image shape:
(106, 106, 70, 40)
```

Thanks a lot!

**Comment by mattcieslak** [comment]
Hi, thanks for reporting! This error is due to the images having slightly different affines, which could happen if the scanner operator moves the acquisition box a little between the two scans. We're working on this at the moment and should have a fix in the next release.

**Comment by giulia-berto** [comment]
Hi, I have the same error, but in my case the two affines are not only slightly different:
```
ValueError: Field of view of image #1 is different from reference FOV.
Reference affine:
array([[  -1.25,    0.  ,    0.  ,   90.  ],
       [   0.  ,    1.25,    0.  , -126.  ],
       [   0.  ,    0.  ,    1.25,  -72.  ],
       [   0.  ,    0.  ,    0.  ,    1.  ]])
Image affine:
array([[-2.29157591e+00, -1.89879686e-02,  1.44471088e-02,
         1.09835373e+02],
       [-1.34829255e-02,  2.17483091e+00,  7.24984646e-01,
        -1.43493515e+02],
       [ 1.96460877e-02, -7.22244501e-01,  2.18270230e+00,
        -3.02709713e+01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])
Reference shape:
(145, 174, 145)
Image shape:
(96, 96, 63, 50)
```
Am I doing something wrong or are those issues somehow related? Thanks!

**Comment by giulia-berto** [comment]
Sorry my bad, I was using a wrong set of inputs, please disregard my previous message.

**Comment by IRuotsa** [comment]
That's great! Thank you!

**Comment by IRuotsa** [comment]
Hi @mattcieslak , do you know when you will be releasing the next version, where this issue is fixed? Thanks!

**Comment by mattcieslak** [comment]
Sorry for the delay @IRuotsa, there has been a recent release but this bugfix hasn't made it in yet.

**Comment by IRuotsa** [comment]
Thank you for the update!

**Comment by hfxcarl** [comment]
> Reference shape:
> (106, 106, 70)
> Image shape:
> (106, 106, 70, 40)

Hi @mattcieslak, I'm having the same issue as @IRuotsa. Our input dwi data has 2 sequences. The main seq with pePA at 68-directions [110,110,77,68] and the other reverse pe-AP has 8-directions (all b0's) [110,110,77,8]. This is my error snippet:

> 220526-11:24:14,548 nipype.workflow ERROR:
	 Saving crash info to /data/derivatives/qsiprep/sub-CB001A/log/20220526-110328_e39f26ba-e612-41b2-9360-4bf3b29de761/crash-20220526-112414-tibbo-raw_rpe_concat-68631932-08d6-4e5a-9203-2fde2b45a7c3.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 521, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 639, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node raw_rpe_concat.
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 398, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/nilearn.py", line 134, in _run_interface
    new_nii = concat_imgs(self.inputs.in_files, dtype=self.inputs.dtype)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nilearn/_utils/niimg_conversions.py", line 484, in concat_niimgs
    for index, (size, niimg) in enumerate(zip(lengths, _iter_check_niimg(
  File "/usr/local/miniconda/lib/python3.8/site-packages/nilearn/_utils/niimg_conversions.py", line 159, in _iter_check_niimg
    raise ValueError(
ValueError: Field of view of image #1 is different from reference FOV.
Reference affine:
array([[-1.99231589e+00,  1.57260627e-01,  7.71215111e-02,
         9.54115906e+01],
       [ 1.52919680e-01,  1.99112785e+00, -1.09661102e-01,
        -9.22089310e+01],
       [ 8.53998289e-02,  1.03340410e-01,  1.99555147e+00,
        -9.62556076e+01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])
Image affine:
array([[-1.99231493e+00,  1.57260627e-01,  7.71398842e-02,
         9.54115906e+01],
       [ 1.52919605e-01,  1.99112785e+00, -1.09660499e-01,
        -9.22089310e+01],
       [ 8.54197815e-02,  1.03340410e-01,  1.99551177e+00,
        -9.62556076e+01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])
Reference shape:
(110, 110, 77)
Image shape:
(110, 110, 77, 8)

What seems to be the problem is Reference.shape is 3D and Image.shape 4D. Perhaps a straightforward fix would be to reduce the Image down to 3D by selecting either the best, first, middle volume or motion-correcting and calculating the temporal-average?

**Comment by mattcieslak** [comment]
@hfxcarl if your 8-direction image is all b=0's is it in the fmap/ or dwi/ directory? I think moving the 8-direction scan to fmap/sub-*_epi.nii.gz and add the dwi to the `"IntendedFor"` in its sidecar the b=0s will be used for distortion correction and the dwi will be processed correctly

**Comment by hfxcarl** [comment]
Hi @mattcieslak, As you suggested, I moved the 8-dir reverse-PE over to the /fmap/ directory with the "IntendedFor". The test-job is still running, but it has now gone well past the stage where it was previously failing with the above error. Thanks so much for your rapid feedback!

**Comment by weberam2** [comment]
Hi, just wanted to add in that I am also having this error

My input data is also two sequences: 
- one sequence is in AP direction with 3 b=0 and 30 b = 1000
- second sequence is in PA direction with 3 b=0 and 60 b=2000

QSIprep crashes, but produces preprocessed .nii.gz image:

log error:
```
Node: qsiprep_wf.single_subject_Rett01_wf.dwi_preproc_wf.pre_hmc_wf.raw_rpe_concat
Working directory: /scratch/qsiprep_wf/single_subject_Rett01_wf/dwi_preproc_wf/pre_hmc_wf/raw_rpe_concat

Node inputs:

compress = True
dtype = f4
header_source = <undefined>
in_files = <undefined>
is_dwi = True

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node raw_rpe_concat.

Traceback:
	Traceback (most recent call last):
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 398, in run
	    runtime = self._run_interface(runtime)
	  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/nilearn.py", line 134, in _run_interface
	    new_nii = concat_imgs(self.inputs.in_files, dtype=self.inputs.dtype)
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nilearn/_utils/niimg_conversions.py", line 487, in concat_niimgs
	    for index, (size, niimg) in enumerate(zip(lengths, _iter_check_niimg(
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nilearn/_utils/niimg_conversions.py", line 160, in _iter_check_niimg
	    raise ValueError(
	ValueError: Field of view of image #1 is different from reference FOV.
	Reference affine:
	array([[-1.79477441e+00, -6.63911998e-02,  1.19901352e-01,
	         1.28985382e+02],
	       [-8.74731839e-02,  1.76716912e+00, -3.30843806e-01,
	        -9.69735107e+01],
	       [ 1.05513543e-01,  3.35716337e-01,  1.76523221e+00,
	        -1.38833572e+02],
	       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
	         1.00000000e+00]])
	Image affine:
	array([[-1.79477453e+00, -6.63908795e-02,  1.19907245e-01,
	         1.28985336e+02],
	       [-8.74728560e-02,  1.76716900e+00, -3.30862254e-01,
	        -9.69734955e+01],
	       [ 1.05512999e-01,  3.35716873e-01,  1.76532757e+00,
	        -1.38833649e+02],
	       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
	         1.00000000e+00]])
	Reference shape:
	(140, 140, 80)
	Image shape:
	(140, 140, 80, 33)
```

the files that are produced are:
```
.
├── anat
│   ├── sub-Rett01_desc-brain_mask.nii.gz
│   ├── sub-Rett01_desc-preproc_T1w.nii.gz
│   ├── sub-Rett01_dseg.nii.gz
│   ├── sub-Rett01_from-MNI152NLin2009cAsym_to-T1w_mode-image_xfm.h5
│   ├── sub-Rett01_from-orig_to-T1w_mode-image_xfm.txt
│   ├── sub-Rett01_from-T1w_to-MNI152NLin2009cAsym_mode-image_xfm.h5
│   ├── sub-Rett01_label-CSF_probseg.nii.gz
│   ├── sub-Rett01_label-GM_probseg.nii.gz
│   ├── sub-Rett01_label-WM_probseg.nii.gz
│   ├── sub-Rett01_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz
│   ├── sub-Rett01_space-MNI152NLin2009cAsym_desc-preproc_T1w.nii.gz
│   ├── sub-Rett01_space-MNI152NLin2009cAsym_dseg.nii.gz
│   ├── sub-Rett01_space-MNI152NLin2009cAsym_label-CSF_probseg.nii.gz
│   ├── sub-Rett01_space-MNI152NLin2009cAsym_label-GM_probseg.nii.gz
│   └── sub-Rett01_space-MNI152NLin2009cAsym_label-WM_probseg.nii.gz
├── dwi
│   ├── sub-Rett01_confounds.tsv
│   ├── sub-Rett01_desc-SliceQC_dwi.json
│   ├── sub-Rett01_space-T1w_desc-brain_mask.nii.gz
│   ├── sub-Rett01_space-T1w_desc-eddy_cnr.nii.gz
│   ├── sub-Rett01_space-T1w_desc-preproc_dwi.b
│   ├── sub-Rett01_space-T1w_desc-preproc_dwi.bval
│   ├── sub-Rett01_space-T1w_desc-preproc_dwi.bvec
│   ├── sub-Rett01_space-T1w_desc-preproc_dwi.nii.gz
│   └── sub-Rett01_space-T1w_dwiref.nii.gz
└── log
    └── 20230219-013030_26d70369-0947-4b83-b15f-6c7f5256e9c8
        └── crash-20230219-013059-root-raw_rpe_concat-42fbb6b6-65ca-4d00-be47-71d3bd6bfdbe.txt

4 directories, 25 files

```

**Comment by pollaro** [comment]
I'm getting this same image FOV error with 1.1.1. And, like the note below, the field of view was never changed on the scanner. All the references and center of slices were copied over from the previous scans. My scan that is causing this issue is the same phase direction even.

> Important note:
> 
> The FOV between the two scans are exactly the same from the operator point of view. In fact, we use the scanner tool to copy/paste the FOV, and no manual action is performed on the FOV after it is copied. Moreover, you can see in the logs that the differences is in far decimals of the affine (compare `3.64958555e-01` to `3.64942998e-01`). This is an issue I have encountered many times and I think it has to do with numerical floating precision. I would suggest a fix where the affines are rounded to 3rd decimal - this would fix the above issue, potentially for other people as well - and very likely not be harmful for virtually all cases.
> 
> EDIT: actually rounding to 3rd decimal is not enough, and rounding more roughly seems dubious. I suggest instead that if a strict match fail, then on of the two images is resampled to the other using e.g. `nilearn.image.resample_to_img`.

**Comment by WillForan** [comment]
Also hitting this, but with values larger than a floating point rounding error (3mm in z).

Is the recommendation to reslice/affine align before giving to qsiprep?

```
tail -n 15  sub-*/log/*/crash-*.txt 

==> sub-11823/log/20260420-193526_3645b09a-8461-493c-8c03-6303a3f7c348/crash-20260420-193727-root-raw_rpe_concat-46f33b76-5221-46c5-80b2-6b596136bd49.txt <==
        array([[  -1.48648643,   -0.        ,   -0.        ,  111.85658264],
               [  -0.        ,    1.48648643,   -0.        , -100.85723877],
               [   0.        ,    0.        ,    4.5       ,  -55.75      ],
               [   0.        ,    0.        ,    0.        ,    1.        ]])
        Image affine:
        array([[  -1.48648643,   -0.        ,   -0.        ,  111.8565979 ],
               [  -0.        ,    1.48648643,   -0.        , -100.85722351],
               [   0.        ,    0.        ,    1.5       ,  -60.25      ],
               [   0.        ,    0.        ,    0.        ,    1.        ]])
        Reference shape:
        (148, 148, 28)
        Image shape:
        (148, 148, 84, 18)



==> sub-11882/log/20260420-200448_c90fe2f3-72ac-4811-9c2f-fd887331f2e3/crash-20260420-200624-root-raw_rpe_concat-dc1897bd-7e3c-4488-8fe6-0dbfac8631b5.txt <==
        array([[  -1.48648643,   -0.        ,   -0.        ,  110.00001526],
               [  -0.        ,    1.48648643,   -0.        , -103.06555176],
               [   0.        ,    0.        ,    4.5       ,  -57.75      ],
               [   0.        ,    0.        ,    0.        ,    1.        ]])
        Image affine:
        array([[  -1.48648643,   -0.        ,   -0.        ,  110.00003052],
               [  -0.        ,    1.48648643,   -0.        , -103.06559753],
               [   0.        ,    0.        ,    1.5       ,  -62.25      ],
               [   0.        ,    0.        ,    0.        ,    1.        ]])
        Reference shape:
        (148, 148, 28)
        Image shape:
        (148, 148, 84, 18)

```

```
3dinfo -dc3 -same_center -iname "${files[@]}" ; 
-2.599831       -8.399513       5.000000        0       sub-11823/ses-1ptx/dwi/sub-11823_ses-1ptx_dir-PA_dwi.nii.gz
-2.599846       -8.399529       2.000000        0       sub-11823/ses-1ptx/dwi/sub-11823_ses-1ptx_dir-AP_run-1_dwi.nii.gz
```

**Comment by arovai** [comment]
It seems in your case that the number of slices is very different from one image to the other (28 versus 84). So this is, I think, a different issue, though reslicing will solve this.
