### ISSUE TITLE
Unable to use GPU for eddy

### ISSUE THREAD

**Issue by meet10may** [PennLINC/qsiprep#243]
I am trying to use the GPUs for eddy, but it seems that QSIPrep is unable to invoke the GPU. I have the Tesla K40s. I have also tried with V100s, but when I check `nvidia-smi` there are no processes running and the QSIprep pipeline is also stuck at eddy. 
The json file has `CUDA_enabled=True`
My command is 

```
singularity run --nv -e -B /work/qsiprep:/work/qsiprep /work/scripts/qsiprep-0.13.0RC2.sif 
/work/data/subject-1/bids/ /work/subject-1/output-eddy/ 
participant --output-resolution 1.2 --dwi-only --denoise-method patch2self --unringing-method mrdegibbs 
--hmc_model eddy --eddy_config eddy_params.json --fs-license-file /work/scripts/license.txt 
-w /work/subject-1/output-eddy/ --participant_label test -vvv
```

This is the place where the pipeline is stuck.

```
[Node] Running "eddy" ("qsiprep.interfaces.eddy.ExtendedEddy"), a CommandLine Interface with command:
eddy_openmp  --cnr_maps --flm=linear --ff=10.0 --acqp=/work/subject-1/output-eddy/qsiprep_wf/single_subject_test_wf/dwi_preproc_wf/hmc_sdc_wf/gather_inputs/eddy_acqp.txt --bvals=/work/subject-1/bids/sub-test/dwi/sub-test_dwi.bval --bvecs=/work/subject-1/bids/sub-test/dwi/sub-test_dwi.bvec --imain=/work/subject-1/output-eddy/qsiprep_wf/single_subject_test_wf/dwi_preproc_wf/pre_hmc_wf/merge_and_denoise_wf/dwi_denoise_dwi_wf/biascorr/sub-test_dwi_denoised_patch2self_mrdegibbs_N4.nii.gz --index=/work/subject-1/output-eddy/qsiprep_wf/single_subject_test_wf/dwi_preproc_wf/hmc_sdc_wf/gather_inputs/eddy_index.txt --mask=/work/subject-1/output-eddy/qsiprep_wf/single_subject_test_wf/dwi_preproc_wf/hmc_sdc_wf/pre_eddy_b0_ref_wf/enhance_and_mask_b0/topup_imain_avg_mask.nii.gz --interp=spline --data_is_shelled --resamp=jac --niter=5 --nvoxhp=1000 --out=/work/subject-1/output-eddy/qsiprep_wf/single_subject_test_wf/dwi_preproc_wf/hmc_sdc_wf/eddy/eddy_corrected --repol --slm=linear
210415-10:08:01,945 nipype.workflow INFO:
	 [MultiProc] Running 1 tasks, and 1 jobs ready. Free memory (GB): 56.40/56.60, Free processors: 12/20.
                     Currently running:
                       * qsiprep_wf.single_subject_test_wf.dwi_preproc_wf.hmc_sdc_wf.eddy
```

This is my `nvidia-smi` output, but I believe since CUDA 9.1 is already installed inside the QSIPrep container, the local CUDA version should not have any effect on the processing:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.111                Driver Version: 384.111                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K40s          Off  | 00000000:03:00.0 Off |                    0 |
| N/A   26C    P0    49W / 225W |      0MiB / 11439MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

Am I missing anything?

**Comment by mattcieslak** [comment]
When we run QSIPrep on our cluster we definitely see it in nvidia-smi. It's possible your json file doesn't have the correct setting. You should have something like:

```json
{
  "flm": "linear",
  "slm": "linear",
  "fep": false,
  "interp": "spline",
  "nvoxhp": 1000,
  "fudge_factor": 10,
  "dont_sep_offs_move": false,
  "dont_peas": false,
  "niter": 5,
  "method": "jac",
  "repol": true,
  "num_threads": 1,
  "is_shelled": true,
  "use_cuda": true,
  "cnr_maps": true,
  "residuals": false,
  "output_type": "NIFTI_GZ",
  "args": ""
}
```

`CUDA_enabled` isn't a recognized option.

**Comment by meet10may** [comment]
Thanks, for the reply. Yes, I meant `"cude_cuda"` is set to `True`. I am using the default json file but with `use_cuda` set to `True`. But I realized that my pipeline is not running eddy as it is unable to find the fieldmaps. Although, I have set the `IntendedFor` which points to the correct AP and PA images. 
Here is the output when running `QSIPrep`

```
210416-03:27:13,935 nipype.workflow INFO:
	 Running with omp_nthreads=8, nthreads=20
210416-03:27:13,936 nipype.workflow IMPORTANT:
	 
    Running qsiprep version 0.13.0RC2:
      * BIDS dataset path: /work/subject-1/bids.
      * Participant list: ['test'].
      * Run identifier: 20210416-032712_0c14264d-52cd-4ece-9727-30465533a5e9.
    
210416-03:27:18,445 nipype.workflow INFO:
	 Combining all 1 dwis within the single available session
210416-03:27:18,977 nipype.workflow INFO:
	 [{'dwi_series': ['/work/bids/sub-test/dwi/sub-test_dwi.nii.gz'], 'fieldmap_info': {'suffix': None}, 'dwi_series_pedir': 'j-', 'concatenated_bids_name': 'sub-test'}]
210416-03:27:19,773 nipype.workflow IMPORTANT:
```  
Notice, the `fieldmap info` is `None`. This is how I have entered the `IntendedFor` field in my AP and PA fieldmaps.json files

`"IntendedFor": "sub-test/fmap/sub-test_acq-dwib0_dir-AP_epi.nii.gz", `

`"IntendedFor": "sub-test/fmap/sub-test_acq-dwib0_dir-PA_epi.nii.gz", `

The bids validator also seems to validate my data
```Making sure the input data is BIDS compliant (warnings can be ignored in most cases).
This dataset appears to be BIDS compatible.
```

Any suggestions on what is missing? Thanks!

**Comment by mattcieslak** [comment]
Oh wow, I just had an aha-moment. Your subject is triggering the doctest and not using real data because it looks like the subject's ID is "test". Is that the case? If so could you please try renaming your subject to something other than "test"?

**Comment by mattcieslak** [comment]
Regarding the CUDA libraries, our HPC system (also CentOS) requires us to load the correct CUDA libraries using the modules system with something like `module load cuda/9.1`. 

It's possible that eddy is running but for some reason not registering with your `nvidia-smi`. If eddy couldn't find a gpu to use it will throw an error and you will see it in the QSIPrep logs. What happens if you run qsiprep and on the same host, while it's seemingly hanging on eddy, run `singularity exec --nv /work/scripts/qsiprep-0.13.0RC2.sif nvidia-smi`?

**Comment by meet10may** [comment]
> Oh wow, I just had an aha-moment. Your subject is triggering the doctest and not using real data because it looks like the subject's ID is "test". Is that the case? If so could you please try renaming your subject to something other than "test"?

Thanks for the reply. Unfortunately,  it is the same with the real subject ID too.  :(

```
[{'dwi_series': ['/work/07798/tnath/stampede2/data/submissions/trav_human_scans/northshore_edited/bids/sub-travhuman/dwi/sub-travhuman_dwi.nii.gz'], 'fieldmap_info': {'suffix': None}, 'dwi_series_pedir': 'j-', 'concatenated_bids_name': 'sub-travhuman'}]
```

Regarding, the  CUDA, it creates a crash file in the logs. Please see below:

```
Node: qsiprep_wf.single_subject_travhuman_wf.dwi_preproc_wf.hmc_sdc_wf.eddy
Working directory: /work/07798/tnath/stampede2/data/submissions/trav_human_scans/northshore_edited/output-eddy-repeat/qsiprep_wf/single_subject_travhuman_wf/dwi_preproc_wf/hmc_sdc_wf/eddy

Node inputs:

args = 
cnr_maps = True
dont_peas = False
dont_sep_offs_move = False
environ = {'FSLOUTPUTTYPE': 'NIFTI_GZ', 'OMP_NUM_THREADS': '8'}
estimate_move_by_susceptibility = <undefined>
fep = False
field = <undefined>
field_mat = <undefined>
flm = linear
fudge_factor = 10.0
fwhm = <undefined>
in_acqp = <undefined>
in_bval = <undefined>
in_bvec = <undefined>
in_file = <undefined>
in_index = <undefined>
in_mask = <undefined>
in_topup_fieldcoef = <undefined>
in_topup_movpar = <undefined>
initrand = <undefined>
interp = spline
is_shelled = True
json = <undefined>
mbs_ksp = <undefined>
mbs_lambda = <undefined>
mbs_niter = <undefined>
method = jac
mporder = <undefined>
multiband_factor = <undefined>
multiband_offset = <undefined>
niter = 5
num_threads = 8
nvoxhp = 1000
out_base = eddy_corrected
outlier_nstd = <undefined>
outlier_nvox = <undefined>
outlier_pos = <undefined>
outlier_sqr = <undefined>
outlier_type = <undefined>
output_type = NIFTI_GZ
repol = True
residuals = False
session = <undefined>
slice2vol_interp = <undefined>
slice2vol_lambda = <undefined>
slice2vol_niter = <undefined>
slice_order = <undefined>
slm = linear
use_cuda = True

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 434, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/fsl/epi.py", line 996, in _run_interface
    runtime = super(Eddy, self)._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 829, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 760, in raise_exception
    ).format(**runtime.dictcopy())
RuntimeError: Command:
eddy_cuda9.1  --cnr_maps --flm=linear --ff=10.0 --acqp=/work/07798/tnath/stampede2/data/submissions/trav_human_scans/northshore_edited/output-eddy-repeat/qsiprep_wf/single_subject_travhuman_wf/dwi_preproc_wf/hmc_sdc_wf/gather_inputs/eddy_acqp.txt --bvals=/work/07798/tnath/stampede2/data/submissions/trav_human_scans/northshore_edited/bids/sub-travhuman/dwi/sub-travhuman_dwi.bval --bvecs=/work/07798/tnath/stampede2/data/submissions/trav_human_scans/northshore_edited/bids/sub-travhuman/dwi/sub-travhuman_dwi.bvec --imain=/work/07798/tnath/stampede2/data/submissions/trav_human_scans/northshore_edited/output-eddy-repeat/qsiprep_wf/single_subject_travhuman_wf/dwi_preproc_wf/pre_hmc_wf/merge_and_denoise_wf/dwi_denoise_dwi_wf/biascorr/sub-travhuman_dwi_denoised_patch2self_mrdegibbs_N4.nii.gz --index=/work/07798/tnath/stampede2/data/submissions/trav_human_scans/northshore_edited/output-eddy-repeat/qsiprep_wf/single_subject_travhuman_wf/dwi_preproc_wf/hmc_sdc_wf/gather_inputs/eddy_index.txt --mask=/work/07798/tnath/stampede2/data/submissions/trav_human_scans/northshore_edited/output-eddy-repeat/qsiprep_wf/single_subject_travhuman_wf/dwi_preproc_wf/hmc_sdc_wf/pre_eddy_b0_ref_wf/enhance_and_mask_b0/topup_imain_avg_mask.nii.gz --interp=spline --data_is_shelled --resamp=jac --niter=5 --nvoxhp=1000 --out=/work/07798/tnath/stampede2/data/submissions/trav_human_scans/northshore_edited/output-eddy-repeat/qsiprep_wf/single_subject_travhuman_wf/dwi_preproc_wf/hmc_sdc_wf/eddy/eddy_corrected --repol --slm=linear
Standard output:
EDDY:::  EddyGpuUtils::InitGpu: cudeGetDevice returned an unknown error code
EDDY:::  cuda/EddyGpuUtils.cu:::  static void EDDY::EddyGpuUtils::InitGpu(bool):  Exception thrown
EDDY:::  cuda/EddyGpuUtils.cu:::  static std::shared_ptr<EDDY::DWIPredictionMaker> EDDY::EddyGpuUtils::LoadPredictionMaker(const EDDY::EddyCommandLineOptions&, EDDY::ScanType, const EDDY::ECScanManager&, unsigned int, float, NEWIMAGE::volume<float>&, bool):  Exception thrown
EDDY:::  eddy.cpp:::  EDDY::ReplacementManager* EDDY::Register(const EDDY::EddyCommandLineOptions&, EDDY::ScanType, unsigned int, const std::vector<float, std::allocator<float> >&, EDDY::SecondLevelECModel, bool, EDDY::ECScanManager&, EDDY::ReplacementManager*, NEWMAT::Matrix&, NEWMAT::Matrix&):  Exception thrown
EDDY::: Eddy failed with message EDDY:::  eddy.cpp:::  EDDY::ReplacementManager* EDDY::DoVolumeToVolumeRegistration(const EDDY::EddyCommandLineOptions&, EDDY::ECScanManager&):  Exception thrown
Standard error:

Return code: 1

```

**Comment by meet10may** [comment]
The fieldmap issue was resolved by putting the `IntendedFor` just below `InPlanePhaseEncodingDirectionDICOM` and the path of the correct dwi image was passed as a list
i.e.
```
"InPlanePhaseEncodingDirectionDICOM": "COL",
    "IntendedFor": [
        "ses-PVP/dwi/sub-s043021_ses-PVP_dwi.nii.gz"
    ],
```

Regarding GPU usage, loading CUDA 10 resolved the issue and I was able to finish the processing in approx 3 hours. 
Thank @mattcieslak for your help!

**Comment by bwinsto2** [comment]
@meet10may glad you got this working!! I was struggling with the same step on those data and eventually gave up.
