### ISSUE TITLE
QSIPrep Stopped Abruplty

### ISSUE THREAD

**Issue by ShreyasFadnavis** [PennLINC/qsiprep#261]
Hi @mattcieslak!

I was running QSIPrep on ~100 subjects as follows:

```
qsiprep-docker /data_folder /deriv_folder --output-resolution 1.2  --fs-license-file $FREESURFER_HOME/license.txt -w /deriv_folder --use-syn-sdc --recon_spec mrtrix_singleshell_ss3t --force-syn
```

After 87 subjects, QSIPrep was randomly interrupted with the following error:
```
210624-20:47:54,213 nipype.workflow INFO:
	 [Node] Running "merge" ("qsiprep.interfaces.nilearn.Merge")
exception calling callback for <Future at 0x7f7acbf54320 state=finished raised BrokenProcessPool>
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
exception calling callback for <Future at 0x7f7acbd23ef0 state=finished raised BrokenProcessPool>
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

Not sure what the issue was. I am guessing something from `multiprocessing`. 

What would be your suggestion? Should I restart by running the above command? Will QSIPrep resume from where it failed?

edit: I mean would the NiPype nodes pick up the precomputed outputs?

Thanks in advance!
-Shreyas

**Comment by mattcieslak** [comment]
This usually happens when a process gets killed by the OS for requesting more memory than is available. As long as you still have the /deriv_folder available it will pick up where it crashed when you re-run it. Also, it might be a good idea to put the derivatives somewhere different from your working directory. I'm not sure it would cause problems to use the same directory for both, but I am often surprised.

To keep memory usage lower, you could set --n-threads to not use all available cpus on your machine at once.

**Comment by ShreyasFadnavis** [comment]
Thanks a lot @mattcieslak ! This answers my question. We may want to add this to the documentation. While it is obvious to people who have used NiPype before, it could be confusing to other folks I guess!

Closing this issue for now 👍🏽
