### ISSUE TITLE
Error running mrtrix.TrcGen on my machine - ?memory issue

### ISSUE THREAD

**Issue by meherlad** [PennLINC/qsiprep#278]
Hello

I was wondering if someone could help me. I've tried using qsiprep for the first time and was doing a test run. I've successfully managed to preprocess a scan but during the recon phase I get the following error (see below). I'm running it on Ubuntu 20.04 and have about 12GB free of memory. I have googled the error and noticed from other issues from fmriprep that this may potentially be an issue with memory? If so, do you know any way to get around this on my local machine?

Cheers

Meher

--------------------------------------------------------------------
```
[Node] Running "tractography" ("qsiprep.interfaces.mrtrix.TckGen"), a CommandLine Interface with command:
tckgen -act /tmp/work/qsirecon_wf/sub-A00008326_mrtrix_singleshell_ss3t/anat_ingress_wf/create_5tt/sub-A00008326_desc-preproc_T1w_5tt.mif -algorithm iFOD2 -backtrack -crop_at_gmwmi -maxlength 250.000000 -minlength 30.000000 -samples 4 -nthreads 7 -output_seeds out_seeds.nii.gz -power 0.330000 -seed_dynamic /tmp/work/qsirecon_wf/sub-A00008326_mrtrix_singleshell_ss3t/recon_wf/ss3t_csd/_dwi_file_..qsiprep-output..sub-A00008326..ses-ALGA..dwi..sub-A00008326_ses-ALGA_space-T1w_desc-preproc_dwi.nii.gz/intensity_norm/sub-A00008326_ses-ALGA_space-T1w_desc-preproc_dwi_wm_mtnorm.mif -select 10000000 /tmp/work/qsirecon_wf/sub-A00008326_mrtrix_singleshell_ss3t/recon_wf/ss3t_csd/_dwi_file_..qsiprep-output..sub-A00008326..ses-ALGA..dwi..sub-A00008326_ses-ALGA_space-T1w_desc-preproc_dwi.nii.gz/intensity_norm/sub-A00008326_ses-ALGA_space-T1w_desc-preproc_dwi_wm_mtnorm.mif tracked.tck
210728-13:38:55,723 nipype.workflow INFO:
	 b''
210728-13:38:55,723 nipype.workflow INFO:
	 b''
exception calling callback for <Future at 0x7fdb2e849ef0 state=finished raised BrokenProcessPool>
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
exception calling callback for <Future at 0x7fdb2e849828 state=finished raised BrokenProcessPool>
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

```

**Comment by mattcieslak** [comment]
It's possible this is a memory issue. Have you tried setting --nthreads 1? you may also need to edit the pipeline json file to create fewer streamlines

**Comment by meherlad** [comment]
Thanks so much for replying Matt! It didn't work. I ended up running the modules individually. I was just testing qsiprep out and hopefully when I get a pipeline on AWS working I can use it properly.
Really appreciate your time to respond to my query!
