### ISSUE TITLE
Error in node dwi_finalize_wf.series_qc 

### ISSUE THREAD

**Issue by fredrmag** [PennLINC/qsiprep#291]
qsiprep version: 0.12.1

I get the following crash report when running qsiprep with two dwis with opposite phase encoding:
```
Node: qsiprep_wf.single_subject_001ses01_wf.dwi_finalize_wf.series_qc
Working directory: /work/qsiprep_wf/single_subject_001ses01_wf/dwi_finalize_wf/series_qc

Node inputs:

confounds_file = <undefined>
mni_dice_score = <undefined>
mni_qc = <undefined>
output_file_name = sub-001ses01
pre_qc = <undefined>
t1_dice_score = <undefined>
t1_qc = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/legacymultiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 419, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/interfaces/reports.py", line 510, in _run_interface
    image_qc = _load_qc_file(self.inputs.pre_qc, prefix="raw_")
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/interfaces/reports.py", line 536, in _load_qc_file
    qc_data = pd.read_csv(fname).to_dict(orient='records')[0]
  File "/usr/local/miniconda/lib/python3.7/site-packages/pandas/io/parsers.py", line 697, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/miniconda/lib/python3.7/site-packages/pandas/io/parsers.py", line 408, in _read
    filepath_or_buffer, encoding, compression)
  File "/usr/local/miniconda/lib/python3.7/site-packages/pandas/io/common.py", line 232, in get_filepath_or_buffer
    raise ValueError(msg.format(_type=type(filepath_or_buffer)))
ValueError: Invalid file path or buffer object type: <class 'traits.trait_base._Undefined'>
```
using the following qsiprep command: 
![image](https://user-images.githubusercontent.com/21278572/131470283-7234a198-c809-42ce-a717-aaaac8c0bed9.png)

It looks like the workflow `dwi_qc_wf` is not ran when two dwis with opposite phase encoding are used as input.

**Comment by mattcieslak** [comment]
Hi @fredrmag this looks familiar. Just to be sure it didn't get fixed recently could you please try 0.14.2?

**Comment by fredrmag** [comment]
Thanks for the reply. I will try with 0.14.2 and report back

**Comment by fredrmag** [comment]
Running 0.14.2 does not produce the issue, so seems to be fixed. Closing the issue!
