### ISSUE TITLE
Gradient files not matching after rotation (macaque DWI) 

### ISSUE THREAD

**Issue by smeisler** [PennLINC/qsiprep#306]
Hello,
### Installation
QSIPrep 0.14.2 running on Linux HPC via Singularity
### Bug description
Referring #292 . I have macaque DWI/T1 images that have the wrong orientation labels in visualization software (e.g. fslview).
![image](https://user-images.githubusercontent.com/27028726/135954624-9c1a200b-d749-46d0-a4e6-e0c1b5a7a3a4.png)
I rotated them with MRIcroMtl to correct the labels, and exported new bval/vecs using MrTrix3 `dwigradcheck`. I tried to QSIPrep (infant mode, dwi only), and got an error:

```
Traceback (most recent call last):
File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
self.procs[jobid].run(updatehash=updatehash)
File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
result = self._run_interface(execute=True)
File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
return self._run_command(execute)
File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
result = self._interface.run(cwd=outdir)
File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 428, in run
runtime = self._run_interface(runtime)
File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/interfaces/confounds.py", line 61, in _run_interface
newpath=runtime.cwd,
File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/interfaces/confounds.py", line 171, in _gather_confounds
raise Exception("Gradients or original files don't match. File a bug report!")
Exception: Gradients or original files don't match. File a bug report!
```
HTML outputs are created, as well as the preprocessed image, but no QC metrics or eddy CNR images are saved out. When using the non-rotated original images, QSIPrep goes to completion. 

Also the brain mask is all 1s in both cases, but that's probably due to being in infant mode.

**Comment by mattcieslak** [comment]
This may work now, please reopen if there are still problems
