### ISSUE TITLE
Autorecon1 fails when including FLAIR images

### ISSUE THREAD

**Issue by ajschadler12** [PennLINC/qsiprep#316]
When running FreeSurfer through QSIprep for subjects who have FLAIR images, Autorecon1 encounters a runtime error:

```
Node: qsiprep_wf.single_subject_sub-01_wf.anat_preproc_wf.surface_recon_wf.autorecon1
Working directory: /home/user/BIDS/derivatives/qsiprep_work/qsiprep_wf/single_subject_sub-01_wf/anat_preproc_wf/surface_recon_wf/autorecon1

Node inputs:

FLAIR_file = <undefined>
T1_files = <undefined>
T2_file = <undefined>
args = <undefined>
big_ventricles = <undefined>
brainstem = <undefined>
directive = autorecon1
environ = {}
expert = <undefined>
flags = ['-noskullstrip']
hemi = <undefined>
hippocampal_subfields_T1 = <undefined>
hippocampal_subfields_T2 = <undefined>
hires = <undefined>
mprage = <undefined>
mri_aparc2aseg = <undefined>
mri_ca_label = <undefined>
mri_ca_normalize = <undefined>
mri_ca_register = <undefined>
mri_edit_wm_with_aseg = <undefined>
mri_em_register = <undefined>
mri_fill = <undefined>
mri_mask = <undefined>
mri_normalize = <undefined>
mri_pretess = <undefined>
mri_remove_neck = <undefined>
mri_segment = <undefined>
mri_segstats = <undefined>
mri_tessellate = <undefined>
mri_watershed = <undefined>
mris_anatomical_stats = <undefined>
mris_ca_label = <undefined>
mris_fix_topology = <undefined>
mris_inflate = <undefined>
mris_make_surfaces = <undefined>
mris_register = <undefined>
mris_smooth = <undefined>
mris_sphere = <undefined>
mris_surf2vol = <undefined>
mrisp_paint = <undefined>
openmp = 8
parallel = <undefined>
subject_id = recon_all
subjects_dir = <undefined>
talairach = <undefined>
use_FLAIR = <undefined>
use_T2 = <undefined>
xopts = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 521, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 639, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 751, in _run_command
    f"Exception raised while executing Node {self.name}.\n\n{result.runtime.traceback}"
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node autorecon1.

RuntimeError: subprocess exited with code 1.
```
Specifically, mri_normalize fails due to a missing brainmask.mgz in `derivatives/freesurfer/sub-01/mri`. Incidentally, the skullstrip workflow successfully creates the skull-stripped T1w and associated brainmask. Altogether, this makes me think there might be an issue in the niworkflows.interfaces.freesurfer.FSInjectBrainExtracted workflow module.

This might be more of an issue with either sMRIprep or niworkflows though. Can link this issue there if needed.

In the meantime, extending the `--ignore` flag to accept either `flair` or `t2w` may be helpful.

**Comment by ajschadler12** [comment]
Forgot to include, I rebuilt the singularity container using FreeSurfer 7.1.1
Can use the default 6.0.4 FreeSurfer instead, to see if the issue is FreeSurfer version.

**Comment by mattcieslak** [comment]
question - are you also running fmriprep on bold data for this project? If so I strongly suggest you use freesurfer during the fmriprep run. The freesurfer workflow in qsiprep is based on fmriprep 1.2.6 - it's super old. You can use the freesurfer outputs from fmriprep along with the dwi outputs from qsiprep to do some cool reconstructions. The preprocessing workflow doesn't really use the freesurfer output at all.
