### ISSUE TITLE
Problem with mrtrix_singleshell_ss3t

### ISSUE THREAD

**Issue by zhangxiaobai12345** [PennLINC/qsiprep#317]
Hi, I've run qsiprep with algorithm 'mrtrix_singleshell_ss3t', however I've got the error in the picture, I wonder how to solve it?

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
FileNotFoundError: /tmp/work/qsirecon_wf/sub-06_mrtrix_singleshell_ss3t_noACT/recon_wf/track_ifod2/_dwi_file_..out..qsiprep..sub-06..dwi..sub-06_space-T1w_desc-preproc_dwi.nii.gz/tractography/result_tractography.pklz

**Comment by mattcieslak** [comment]
This should be fixed in recent versions
