### ISSUE TITLE
JSON spec for MRtrix reconstruction pipeline 

### ISSUE THREAD

**Issue by student846** [PennLINC/qsiprep#348]
Good afternoon, 

I was wondering whether you might be able to provide some guidance on how to put the JSON spec file together to run the mrtrix_multishell_msmt_ACT-hsvs pipeline using only the Brainnetome atlas. Based on the dsistudio example provided in the documentation, this is what I've put together so far:

{
  "name": "mrtrix_multishell_pipeline”,
  "space": "T1w",
  "anatomical": ["mrtrix_5tt_hsvs"],
  "atlases": ["brainnetome246"],
  "nodes": [
    {
      "name": "mrtrix_multishell_msmt_ACT-hsvs”,
      "software": “MRtrix”,
      "action": "reconstruction",
      "input": "qsiprep",
      "output_suffix": “csd”,
      "parameters": {"method": “csd”}
    },
    {
      "name": "scalar_export",
      "software": “MRtrix”,
      "action": "export",
      "input": "mrtrix_multishell_msmt_ACT-hsvs",
      "output_suffix": “csd_scalar"
    }
  ]
}

However, when I try to run QSIprep using this specification, I receive these errors: 

Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/recon/base.py", line 243, in _load_recon_spec
    spec = json.load(f)
  File "/usr/local/miniconda/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/miniconda/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/miniconda/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/miniconda/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 2 column 40 (char 41)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/cli/run.py", line 1166, in build_recon_workflow
    sloppy=opts.sloppy
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/recon/base.py", line 92, in init_qsirecon_wf
    sloppy=sloppy
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/recon/base.py", line 156, in init_single_subject_wf
    spec = _load_recon_spec(recon_spec, sloppy=sloppy)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/recon/base.py", line 245, in _load_recon_spec
    raise Exception("Unable to read JSON spec. Check the syntax.")
Exception: Unable to read JSON spec. Check the syntax.

Any advice you can provide would be greatly appreciated!

**Comment by student846** [comment]
Thank you so much for your reply, I tried using the file as you suggested and now reconstruction is running. Thanks again for your help!

**Comment by mattcieslak** [comment]
Great! Happy to hear it worked for you
