### ISSUE TITLE
[BUG] LibQt5Core not working in singularity image

### ISSUE THREAD

**Issue by mattcieslak** [PennLINC/qsiprep#353]
moving from #304.

I think the dockerfile needs an ldconfig for it to work on singularity

**Comment by mattcieslak** [comment]
It works!! It was an issue that only appears when loading the libQt5Core.so.5 file from a centos host in singularity. Frank had already fixed this in the official dsi studio docker images [here](https://github.com/frankyeh/DSI-Studio/commit/6e64db0e37c0d5cbc5bf130702a50d3a29abaf91). Now it's in ours too:

```
(base) [rbc@cubic-sattertt1 ~]$ singularity shell --cleanenv qsiprep-0-15-0.sif
Singularity> ldd /opt/dsi-studio/dsi_studio_64/dsi_studio
        linux-vdso.so.1 (0x00007ffec3184000)
        libGLU.so.1 => /usr/lib/x86_64-linux-gnu/libGLU.so.1 (0x00007f39e4da6000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f39e4b89000)
        libQt5OpenGL.so.5 => /opt/qt512/lib/libQt5OpenGL.so.5 (0x00007f39e58a0000)
        libQt5Charts.so.5 => /opt/qt512/lib/libQt5Charts.so.5 (0x00007f39e49c9000)
        libQt5Widgets.so.5 => /opt/qt512/lib/libQt5Widgets.so.5 (0x00007f39e4355000)
        libQt5Gui.so.5 => /opt/qt512/lib/libQt5Gui.so.5 (0x00007f39e3d78000)
        libQt5Core.so.5 => /opt/qt512/lib/libQt5Core.so.5 (0x00007f39e37b3000)
        libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f39e3527000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f39e3308000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f39e2f7f000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f39e2be1000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f39e29c9000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f39e25d8000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f39e56db000)
        libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f39e23a6000)
        libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f39e2108000)
        libicui18n.so.60 => /usr/lib/x86_64-linux-gnu/libicui18n.so.60 (0x00007f39e1c67000)
        libicuuc.so.60 => /usr/lib/x86_64-linux-gnu/libicuuc.so.60 (0x00007f39e18af000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f39e16ab000)
        libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f39e1394000)
        libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007f39e1163000)
        libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007f39e0ead000)
        libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f39e0bf9000)
        libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f39e09cc000)
        libicudata.so.60 => /usr/lib/x86_64-linux-gnu/libicudata.so.60 (0x00007f39dee23000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f39debb1000)
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f39de879000)
        libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f39de651000)
        libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f39de44d000)
        libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f39de247000)
        libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f39de032000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f39dde2a000)
```

**Comment by smeisler** [comment]
testing now!

**Comment by smeisler** [comment]
I get to the recon stage now, but when `plot_peaks` begins I get an error:

	```
 [Node] Executing "plot_peaks" <qsiprep.interfaces.reports.ReconPeaksReport>
220223-15:54:10,929 nipype.workflow INFO:
	 b''
220223-15:54:10,929 nipype.workflow INFO:
	 b''
No protocol specified
Fatal Python error: Segmentation fault

Current thread 0x00002ba313f382c0 (most recent call first):
  File "/usr/local/miniconda/lib/python3.8/site-packages/fury/window.py", line 760 in record
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/niworkflows/viz/utils.py", line 847 in plot_peak_slice
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/niworkflows/viz/utils.py", line 867 in peak_slice_series
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/reports.py", line 758 in _run_interface
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 398 in run
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 715 in _run_command
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 639 in _run_interface
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 521 in run
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67 in run_node
  File "/usr/local/miniconda/lib/python3.8/concurrent/futures/process.py", line 239 in _process_worker
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108 in run
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315 in _bootstrap
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/spawn.py", line 129 in _main
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/forkserver.py", line 319 in _serve_one
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/forkserver.py", line 280 in main
  File "<string>", line 1 in <module>
exception calling callback for <Future at 0x2b2dd3f1c670 state=finished raised BrokenProcessPool>
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
exception calling callback for <Future at 0x2b2dd3fe9340 state=finished raised BrokenProcessPool>
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/miniconda/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

**Comment by mattcieslak** [comment]
Are you still running this with tons of memory and just one thread?

**Comment by smeisler** [comment]
This was 50GB and 32 cpu-per-task

**Comment by mattcieslak** [comment]
could you try in single threaded mode just to make sure it's a qsiprep issue? When I run these I usually launch one job per subject with 32GB memory and at most 6 cpus

**Comment by mattcieslak** [comment]
And I reverted a change that might be causing this segfault, so one more singularity build

**Comment by smeisler** [comment]
I get the segfault on multithreaded with the new container, trying with single.

**Comment by smeisler** [comment]
Looks like tractography is running in the single threaded case. Would you mind sharing what you specify for `--nthreads` and `--ompnthreads` when you run QSIPrep/Recon? I would like to do both steps in a single command not have _everything_ be single-threaded.

**Comment by mattcieslak** [comment]
if you're just testing, you can use the `--sloppy` flag and only a couple streamlines will be generated

**Comment by smeisler** [comment]
Recon proceeded to completion! 🚀 That was with the single thread, will try using 6 cpu like you use and see if I get a segfault. For clarification, is that your total nthread or ompnthread?

**Comment by mattcieslak** [comment]
That's wonderful news!! I can confirm that I was getting segfaults too but these went away when I bumped up the memory resource and reduced the number of threads. 

I thought that maybe there was some sort of graphics-related library missing in the new docker image, but it's just the odf/peak plotting itself that takes enormous amounts of memory. @cookpa how much memory are you requesting when your jobs are creating zombie xvfb processes? My single-thread run just finished with 32GB

**Comment by cookpa** [comment]
My LPC instance doesn't restrict memory usage, but I watched it run, the plot peaks used about 30Gb Virtual, 10Gb res.

**Comment by mattcieslak** [comment]
wow, that's kind of unusable. I'm going to see if I can get plot_peaks a lot more efficient and if not maybe I'll take it out for now.
