### ISSUE TITLE
Exception raised while executing Node concat

### ISSUE THREAD

**Issue by BNU-liuzhenzhao** [PennLINC/qsiprep#359]
@mattcieslak Hi, I am sorry for trubbling you again for a few problems.
The qsiprep pipeline crashed and throwed error:
`220228-06:04:19,44 nipype.workflow WARNING:
	 [Node] Error on "qsiprep_wf.single_subject_6148668_wf.dwi_preproc_wf.confounds_wf.concat" (/work/qsiprep_wf/single_subject_6148668_wf/dwi_preproc_wf/confounds_wf/concat)
220228-06:04:19,44 nipype.workflow ERROR:
	 Node concat failed to run on host 1d625f18f2d1.
220228-06:04:19,49 nipype.workflow ERROR:
	 Saving crash info to /out/qsiprep/sub-6148668/log/20220228-032215_da33df6a-cf8f-4ba1-ae19-357e3c5427d6/crash-20220228-060419-root-concat-bc7f3319-9b71-4336-a5ba-c87a66969554.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 521, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 639, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node concat.

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 398, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/confounds.py", line 53, in _run_interface
    combined_out, confounds_list = _gather_confounds(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/confounds.py", line 174, in _gather_confounds
    raise Exception("Original files don't match. File a bug report!")
Exception: Original files don't match. File a bug report!`

My command is:
`docker run -ti --rm --gpus all \
	-v /home/shulab/data2/liuzhenzhao/qsiprep/qsiprep-in/HCP-A:/data:ro \
	-v /home/shulab/data2/liuzhenzhao/qsiprep/qsiprep-out:/out \
	-v /home//shulab/data2/liuzhenzhao/qsiprep/qsiprep-work:/work \
	-v /home/shulab/data2/liuzhenzhao/qsiprep/qsiprep-conf:/qsiconfig \
	pennbbl/qsiprep:unstable \
	/data /out participant \
	--participant_label [ '6148668' ] \
	--output-resolution 1.5 \
	--skip_bids_validation \
	--eddy-config /qsiconfig/eddy_config.json \
	--fs-license-file /qsiconfig/license.txt \
	--recon_spec /qsiconfig/mrtrix_msmt_csd.json \
	--recon-input /out \
	--work_dir /work \
	--unringing-method mrdegibbs \
	--b0-to-t1w-transform Affine \
	--distortion-group-merge average \
	--nthreads 12 \
	--low-mem`
My docker image is pennbbl/qsiprep:unstable.

what's wrong with it?

**Comment by mattcieslak** [comment]
This suggests that you didn't collect two of the exact same dwi schemes in different phase encoding directions. If that's the case you should remove `--distortion-group-merge average`.
