### ISSUE TITLE
Processing HCP-like dataset

### ISSUE THREAD

**Issue by GalKepler** [PennLINC/qsiprep#385]
Hii all,
I'm trying to process an HCP-like dataset and would appreciate any tips regarding any specific flags that may be appropriate.

My DWI acquisition consists of 2 PE images that are **not** similar (and therefore not exactly the same as HCP's):

1. One DWI series (dir-FWD) is the "main" one, and consists of 186 volumes (4 shells).
2. Another DWI series (dir-REV) consists of 7 volumes (2 shells).

I'm having some trouble understanding which flags are appropriate in this case, and specifically wondering about these:

- `--denoise-after-combining`
- `--distortion-group-merge`

Would love any thoughts about this.
Thanks! (:

**Comment by cookpa** [comment]
I've not done anything but the default for denoising. For `--distortion-group-merge`, this must be "concat" unless you have the exact same sequence played out with opposite gradients. There must be a 1:1 match between every measurement dir-FWD and the same measurement dir-REV.

**Comment by GalBenZvi** [comment]
Thanks @cookpa, I'll give it a try.

**Comment by GalBenZvi** [comment]
It seems that the "DWI series" refers to the "dir-REV" acquisition, although, as described earlier, the main DWI image is the "dir-FWD".
Is it even important for the pipeline if `--distortion-group-merge concat` is passed?
And if it is - is there anyway to let the query know that the "dir-FWD" is the main DWI series?

**Comment by GalBenZvi** [comment]
I've tried following your suggestions and only passed `--distortion-group-merge concat`.
It encounters the following error (the full log is attached below):

```
indexed_gzip.indexed_gzip.IndexedGzipFile.__reduce__
  File "indexed_gzip/indexed_gzip.pyx", line 737, in indexed_gzip.indexed_gzip._IndexedGzipFile.export_index
AttributeError: '_io.BytesIO' object has no attribute 'mode'
```

@cookpa, Any thoughts? 

```
Node: qsiprep_wf.single_subject_14_wf.anat_preproc_wf.t1_2_mni
Working directory: /work/qsiprep_wf/single_subject_14_wf/anat_preproc_wf/t1_2_mni

Node inputs:

compress_report = auto
explicit_masking = True
flavor = precise
float = True
initial_moving_transform = <undefined>
lesion_mask = <undefined>
moving = T1w
moving_image = /work/qsiprep_wf/single_subject_14_wf/anat_preproc_wf/skullstrip_wf/rigid_acpc_resample_head/highres001_N4Corrected0_trans.nii.gz
moving_mask = /work/qsiprep_wf/single_subject_14_wf/anat_preproc_wf/skullstrip_wf/rigid_acpc_resample_mask/highres001_BrainExtractionMask_trans.nii.gz
num_threads = 8
orientation = LPS
out_report = report.svg
reference = T1w
reference_image = /usr/local/miniconda/lib/python3.8/site-packages/qsiprep/data/mni_1mm_t1w_lps_brain.nii.gz
reference_mask = <undefined>
settings = <undefined>
template = MNI152NLin2009cAsym
template_resolution = 1

Traceback (most recent call last):
  File "/home/groot/.local/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/home/groot/.local/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/home/groot/.local/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/home/groot/.local/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/groot/.local/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 429, in run
    runtime = self._post_run_hook(runtime)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/niworkflows/interfaces/registration.py", line 60, in _post_run_hook
    return super(RobustMNINormalizationRPT, self)._post_run_hook(runtime)
  File "/home/groot/.local/lib/python3.8/site-packages/nipype/interfaces/mixins/reporting.py", line 50, in _post_run_hook
    self._generate_report()
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/niworkflows/interfaces/report_base.py", line 55, in _generate_report
    mask_nii = threshold_img(fixed_image_nii, 1e-3)
  File "/home/groot/.local/lib/python3.8/site-packages/nilearn/image/image.py", line 824, in threshold_img
    img_data = _safe_get_data(img, ensure_finite=True, copy_data=copy)
  File "/home/groot/.local/lib/python3.8/site-packages/nilearn/_utils/niimg.py", line 51, in _safe_get_data
    img = copy.deepcopy(img)
  File "/usr/local/miniconda/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/miniconda/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/miniconda/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/miniconda/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/miniconda/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/miniconda/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/miniconda/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/miniconda/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/miniconda/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/miniconda/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/miniconda/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/miniconda/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/miniconda/lib/python3.8/copy.py", line 161, in deepcopy
    rv = reductor(4)
  File "indexed_gzip/indexed_gzip.pyx", line 956, in indexed_gzip.indexed_gzip.IndexedGzipFile.__reduce__
  File "indexed_gzip/indexed_gzip.pyx", line 737, in indexed_gzip.indexed_gzip._IndexedGzipFile.export_index
AttributeError: '_io.BytesIO' object has no attribute 'mode'
```

**Comment by mattcieslak** [comment]
I'm not sure what's happening here exactly, but it may help to use a new working directory with `-w` just in case there are some stale or missing files from your previous run
