### ISSUE TITLE
biascorr failed to run on host

### ISSUE THREAD

**Issue by levchenkoegor** [PennLINC/qsiprep#396]
Hello everyone!

I tried to run qsiprep (0.15.1) on my cluster computer on the open [OASIS-3](https://www.oasis-brains.org/) dataset. I would like to run minimal preprocessing and build a connectivity matrix. 

The command used to run qsiprep (where `$(awk "NR==$SUBJ_I" ~/Entropy/patients_dwi_list.txt)` is just picking the participant id from the .txt file):

```
#!/bin/bash
#SBATCH --time=3-0:0
#SBATCH --cpus-per-task=4
#SBATCH --nodes=1

module load singularity
singularity run ~/qsiprep-0.15.1.sif ~/Entropy/raw_data/patients/ ~/Entropy/derivatives_qsiprep/patients/ participant --participant-label $(awk "NR==$SUBJ_I" ~/Entropy/patients_dwi_list.txt) -w ~/Entropy/work_qsiprep/patients/ --fs-license-file ~/freesurfer/license.txt --skip_bids_validation --output-resolution 2.5 --recon_spec mrtrix_singleshell_ss3t_noACT
```

It returns an error (see the file attached to see a full log file):
```
...
220406-23:27:34,867 nipype.workflow ERROR:
	 Node biascorr failed to run on host cn-031.
220406-23:27:34,916 nipype.workflow ERROR:
	 Saving crash info to /home/elevchenko/Entropy/derivatives_qsiprep/patients/qsiprep/sub-OAS30013/log/20220406-230357_1c2fe9d2-1acf-42c1-a919-037382b4a1fd/crash-20220406-232734-elevchenko-biascorr-bb799e80-67a9-441a-bcd4-ea3ebaec0e08.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 521, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 639, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node biascorr.

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 399, in run
    runtime = self._post_run_hook(runtime)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/mixins/reporting.py", line 50, in _post_run_hook
    self._generate_report()
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/denoise.py", line 68, in _generate_report
    input_dwi, denoised_nii, field_nii = self._get_plotting_images()
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/mrtrix.py", line 999, in _get_plotting_images
    denoised_nii = load_img(ref_name)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nilearn/image/image.py", line 1246, in load_img
    return check_niimg(img, wildcards=wildcards, dtype=dtype)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nilearn/_utils/niimg_conversions.py", line 271, in check_niimg
    raise ValueError("File not found: '%s'" % niimg)
ValueError: File not found: '/home/elevchenko/Entropy/work_qsiprep/patients/qsiprep_wf/single_subject_OAS30013_wf/dwi_preproc_ses_d0102_wf/pre_hmc_wf/merge_and_denoise_wf/dwi_denoise_ses_d0102_dwi_wf/biascorr/sub-OAS30013_ses-d0102_dwi_denoised_N4.nii.gz'


220406-23:27:36,868 nipype.workflow ERROR:
	 could not run node: qsiprep_wf.single_subject_OAS30013_wf.anat_preproc_wf.skullstrip_wf.t1_skull_strip
220406-23:27:36,869 nipype.workflow ERROR:
	 could not run node: qsiprep_wf.single_subject_OAS30013_wf.dwi_preproc_ses_d0102_wf.pre_hmc_wf.merge_and_denoise_wf.dwi_denoise_ses_d0102_dwi_wf.biascorr
QSIPrep failed: 2 raised. Re-raising first.
RuntimeError: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 521, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 639, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node t1_skull_strip.

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 454, in aggregate_outputs
    setattr(outputs, key, val)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
    self.error(objekt, name, str(value))
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: The 'BrainExtractionLaplacian' trait of a BrainExtractionOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/home/elevchenko/Entropy/work_qsiprep/patients/qsiprep_wf/single_subject_OAS30013_wf/anat_preproc_wf/skullstrip_wf/t1_skull_strip/highres001_BrainExtractionLaplacian.nii.gz' <class 'str'> was specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 401, in run
    outputs = self.aggregate_outputs(runtime)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 461, in aggregate_outputs
    raise FileNotFoundError(msg)
FileNotFoundError: No such file or directory '/home/elevchenko/Entropy/work_qsiprep/patients/qsiprep_wf/single_subject_OAS30013_wf/anat_preproc_wf/skullstrip_wf/t1_skull_strip/highres001_BrainExtractionLaplacian.nii.gz' for output 'BrainExtractionLaplacian' of a BrainExtraction interface



The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/qsiprep", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/run.py", line 653, in main
    qsiprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 212, in run
    raise error from cause
RuntimeError: 2 raised. Re-raising first.
Sentry is attempting to send 6 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

There is a full output file here [output_qsiprep_pat1.txt](https://github.com/PennLINC/qsiprep/files/8452998/output_qsiprep_pat1.txt).

There are two files with crash info from derivatives log folder [crash-20220406-232734-elevchenko-biascorr-bb799e80-67a9-441a-bcd4-ea3ebaec0e08.txt](https://github.com/PennLINC/qsiprep/files/8453013/crash-20220406-232734-elevchenko-biascorr-bb799e80-67a9-441a-bcd4-ea3ebaec0e08.txt) and  [crash-20220406-232344-elevchenko-t1_skull_strip-b486799e-41e3-4a17-856c-fba2d7d1b5f7.txt](https://github.com/PennLINC/qsiprep/files/8453014/crash-20220406-232344-elevchenko-t1_skull_strip-b486799e-41e3-4a17-856c-fba2d7d1b5f7.txt)

On my HPC page I can check the memory consumption during the job and it looks like that there is no memory issue:

<img width="1124" alt="Screenshot 2022-04-08 at 16 02 30" src="https://user-images.githubusercontent.com/18507220/162469421-0a3abe2d-78b4-43f1-bc3c-55d5d0019d6b.png">

I tried the same command with the other 2 subjects, but the same problem occurs. The whole dataset is BIDS valid.

I am not sure why this problem occurs, so I would be thankful for any suggestion or advice!

Best,
Egor

**Comment by levchenkoegor** [comment]
I think I solved the issue using the `-e` flag for singularity.
