### ISSUE TITLE
"sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) disk I/O error" error raised in 0.14.3

### ISSUE THREAD

**Issue by sangfengchn** [PennLINC/qsiprep#399]
Hey developers! Thanks for all your work.

I run using singularity (version 2.4.6-dist) with the following command:

```bash
singularity exec -e ~/sangf/Envs/qsiprep-0.14.3.simg qsiprep /brain/babri_in/Desktop/TestQSIPrep/rawdata/ /brain/babri_in/Desktop/TestQSIPrep/derivatives/ participant -w /brain/babri_in/Desktop/TestQSIPrep/work --participant-label sub-0054 --output-resolution 1.0 --skip-bids-validation
```

And I got those message as followed. Any ideas?

Out:
```bash
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: disk I/O error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/cli/run.py", line 813, in build_qsiprep_workflow
    re.compile(r"^\.")))
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py", line 152, in __init__
    database_path, reset_database, config, init_args)
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/db.py", line 48, in __init__
    self.reset_database(init_args, config)
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/db.py", line 106, in reset_database
    Base.metadata.drop_all(self.engine)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 4691, in drop_all
    ddl.SchemaDropper, self, checkfirst=checkfirst, tables=tables
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2095, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1656, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 889, in visit_metadata
    unsorted_tables = [t for t in tables if self._can_drop_table(t)]
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 889, in <listcomp>
    unsorted_tables = [t for t in tables if self._can_drop_table(t)]
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 982, in _can_drop_table
    self.connection, table.name, schema=effective_schema
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/dialects/sqlite/base.py", line 1669, in has_table
    connection, "table_info", table_name, schema=schema
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/dialects/sqlite/base.py", line 2183, in _get_table_pragma
    cursor = connection.execute(statement)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1178, in _execute_text
    parameters,
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) disk I/O error
[SQL: PRAGMA main.table_info("layout_info")]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

**Comment by cookpa** [comment]
Singularity needs mount points to read and write outside the container.

If `/brain/babri_in/Desktop` is a path that exists on your machine, you would do

```
singularity exec \
  -e \
  -B /brain/babri_in/Desktop:/input
  ~/sangf/Envs/qsiprep-0.14.3.simg \
  qsiprep \
    /input/TestQSIPrep/rawdata \
    /input/TestQSIPrep/derivatives \
    participant \
   -w /input/TestQSIPrep/work \
   --participant-label sub-0054 \
   --output-resolution 1.0 \
   --skip-bids-validation
```
