### ISSUE TITLE
estimate_fod failed to run

### ISSUE THREAD

**Issue by levchenkoegor** [PennLINC/qsiprep#402]
Hi

I am working with open DTI dataset OASIS-3 and trying to preprocess and build connectomes it using `qsiprep 0.15.1`

I work on HPC computer and run the job using the next command:
```
#!/bin/bash
#SBATCH --time=2-0:0
#SBATCH --cpus-per-task=4

module load singularity
singularity run -e ~/qsiprep-0.15.1.sif ~/Entropy/raw_data/patients/ ~/Entropy/derivatives_qsiprep/patients/ participant --participant-label $(awk "NR==$SUBJ_I" ~/Entropy/patients_dwi_list.txt) -w ~/Entropy/work_qsiprep/patients/ --fs-license-file ~/freesurfer/license.txt --output-resolution 2 --skip_bids_validation --resource-monitor --hmc_model 3dSHORE --recon_spec mrtrix_singleshell_ss3t_noACT
```

Looks like the qsiprep workflow is working okay, but during the reconstruction the problem with node ```estimate_fod``` appears:
```
	 [Node] Error on "qsirecon_wf.sub-OAS30076_mrtrix_singleshell_ss3t_noACT.sub_OAS30076_ses_d1735_space_T1w_desc_preproc_recon_wf.ss3t_csd.estimate_fod" (/home/elevchenko/Entropy/work_qsiprep/patients/qsirecon_wf/sub-OAS30076_mrtrix_singleshell_ss3t_noACT/sub_OAS30076_ses_d1735_space_T1w_desc_preproc_recon_wf/ss3t_csd/estimate_fod)
220420-22:07:53,10 nipype.workflow ERROR:
	 Node estimate_fod failed to run on host cn-032.
220420-22:07:53,13 nipype.workflow ERROR:
	 Saving crash info to /home/elevchenko/Entropy/derivatives_qsiprep/patients/qsirecon/sub-OAS30076/log/20220420-215638_d5493310-3193-4d23-b791-d04e68c71566/crash-20220420-220753-elevchenko-estimate_fod-b57ee6b1-7992-4d2c-b0a2-985beb669bfa.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 521, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 639, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node estimate_fod.

RuntimeError: subprocess exited with code 1.

220420-22:07:55,13 nipype.workflow ERROR:
	 could not run node: qsirecon_wf.sub-OAS30076_mrtrix_singleshell_ss3t_noACT.sub_OAS30076_ses_d1735_space_T1w_desc_preproc_recon_wf.ss3t_csd.estimate_fod
QSIRecon failed: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 521, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 639, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node estimate_fod.

RuntimeError: subprocess exited with code 1.

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/qsiprep", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/run.py", line 727, in main
    qsirecon_post_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 212, in run
    raise error from cause
RuntimeError: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 521, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 639, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node estimate_fod.

RuntimeError: subprocess exited with code 1.

Sentry is attempting to send 4 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

I attached the full output log file [output_qsiprep_pat11.txt](https://github.com/PennLINC/qsiprep/files/8524800/output_qsiprep_pat11.txt) and the crash file [crash_file.txt](https://github.com/PennLINC/qsiprep/files/8524809/crash-20220420-220753-elevchenko-estimate_fod-b57ee6b1-7992-4d2c-b0a2-985beb669bfa.txt)

This problem appears in most of the subjects in the dataset.
Any advice is helpful!

Best,
Egor

**Comment by mattcieslak** [comment]
We've been running qsiprep on the oasis dataset with v0.19.1. This should be fixed
