### ISSUE TITLE
MRtrix SS3T recon question

### ISSUE THREAD

**Issue by araikes** [PennLINC/qsiprep#404]
Hi @mattcieslak,

Three things:

1. Following on from #400, it appears that omitting the `--output-space` and `--output-resolution` when running reconstruction workflows produces the ODF plots in the HTML file. I've confirmed with both the AMICO NODDI work flow and the SS3T workflow.

2. It used to be that the tractography-based workflow HTML reports had plots for the ROI-to-ROI connectivity for each atlas. Has that behavior changed because, for the SS3T reconstruction, I'm only getting ODF plots or is this a consequence of not having the flags for the output space? I don't specifically care either way, just making sure I haven't unintentionally broken something else by excluding flags.

3. Likewise, it used to be that the co-registered atlases were saved to the output folder. Right now, I appear to get relevant files except for the specific atlas spaces (they are still in the `--work` directory). As long as this is working as intended, I'm good. Here's the outputs from the workflow in `dwi/`:

```
sub-971_space-T1w_desc-preproc_desc-csfFOD_ss3tcsd.txt
sub-971_space-T1w_desc-preproc_desc-csfFODmtnormed_ss3tcsd.mif.gz
sub-971_space-T1w_desc-preproc_desc-gmFOD_ss3tcsd.txt
sub-971_space-T1w_desc-preproc_desc-gmFODmtnormed_ss3tcsd.mif.gz
sub-971_space-T1w_desc-preproc_desc-mtinliermask_ss3tcsd.nii.gz
sub-971_space-T1w_desc-preproc_desc-mtnorm_ss3tcsd.nii.gz
sub-971_space-T1w_desc-preproc_desc-siftweights_ifod2.csv
sub-971_space-T1w_desc-preproc_desc-tracks_ifod2.tck
sub-971_space-T1w_desc-preproc_desc-wmFOD_ss3tcsd.txt
sub-971_space-T1w_desc-preproc_desc-wmFODmtnormed_ss3tcsd.mif.gz
sub-971_space-T1w_desc-preproc_dhollanderconnectome.mat
```

**Comment by mattcieslak** [comment]
I think a few things broke in the update to 0.15. The AAL alignment definitely looks off, I'll look into this soon

**Comment by araikes** [comment]
Sounds good. 

FYI: All atlases are misaligned.

Question: Is there anything obviously broken on the prep side of things or only on the recon workflow side of things?

**Comment by araikes** [comment]
Quick glance at the code and maybe here:

https://github.com/PennLINC/qsiprep/blob/7603d66c12039278905c467b5424a0f998bf0ca1/qsiprep/workflows/recon/anatomical.py#L599

Everything else is using `'dwi_file'`

**Comment by sangfengchn** [comment]
I have the same issue that t1w  misaligned  with all atlases in 0.15.3.

**Comment by mattcieslak** [comment]
Taking a look at this now, can either of you tell if the connectivity matrices look very different from version 0.14.3? 0.15.x brought a bunch of changes to how anatomical data is handled during reconstruction workflows and it looks like some of it needs to be reconfigured

**Comment by araikes** [comment]
I deleted my run of it to free up some space, but I'll run it again today and let you know.

**Comment by mattcieslak** [comment]
@araikes @sangfengchn was the data preprocessed with 0.15.x too? Or an earlier version?

**Comment by mattcieslak** [comment]
I don't have a great intuition on how to interpret log transformed sift weights. Any chance you could do the non-sift-weighted streamline counts? Either way, I'm doing this test as well

**Comment by araikes** [comment]
![qsiprep-0 14 3](https://user-images.githubusercontent.com/18663624/168907921-d7a52c10-43b3-4b0c-90b8-f4701a06e1d3.png) 
![qsiprep-0 15 3](https://user-images.githubusercontent.com/18663624/168907936-af8750f2-ec28-4649-8687-6eec93945858.png)
![sift_diff](https://user-images.githubusercontent.com/18663624/168907947-3b6e990d-50d8-485f-a914-c074a72021e5.png)

**Comment by mattcieslak** [comment]
ok, so a pretty massive difference

**Comment by sangfengchn** [comment]
sorry for the late reply. I havn't yet run it with 0.14.x, but found many zero value in connection matrix generated by 0.15.3. I checked the atlas file registered subject's space, and found the misaligned like this.

![1181652851785_ pic](https://user-images.githubusercontent.com/22000326/168964074-1a6d6157-e0ca-4924-aedf-be08a0ea93ee.jpg)

**Comment by araikes** [comment]
One further test just for the sake of doing so. I used the preprocessed outputs from 0.14.3 and ran the reconstruction pipeline (ss3t + ACT + FAST) using 0.15.3 to minimize the potentially confounding effect of the preprocessing. No real differences in the overall outcomes. See new plots below for comparison to the previous plots where all preprocessing and reconstruction were from a single version.

![qsiprep-0 14 3_v2](https://user-images.githubusercontent.com/18663624/168974341-3cd49766-ee43-4967-a95b-d67e1cef6422.png)
![qsiprep-0 15 3_v2](https://user-images.githubusercontent.com/18663624/168974403-b49307a7-dd2c-4307-b006-2909d02f3d0c.png)
![sift_diff_v2](https://user-images.githubusercontent.com/18663624/168974421-cb0234e6-e3df-42a2-ab3f-9f38be0638c7.png)

**Comment by mattcieslak** [comment]
@araikes @sangfengchn when you get a chance could you try out version 0.15.4 and let me know if the alignment looks better?

**Comment by sangfengchn** [comment]
> 

ok, I am trying 0.15.4, and I will append the alignment results when it's done.

**Comment by araikes** [comment]
Likewise.

**Comment by araikes** [comment]
Spatial alignment looks better. Can't eyeball if it's exactly the same but good enough (at least to show that atlases are regridding correctly) and I'll be more detailed tomorrow. 

AAL aligned via 0.14.3:
![snapshot0001(2)](https://user-images.githubusercontent.com/18663624/169214148-c5dea9e2-8c06-4807-9b9f-cc100a188732.png)

AAL aligned via 0.15.4
![snapshot0002](https://user-images.githubusercontent.com/18663624/169214199-accb92d0-4123-4262-91a3-5302d5ca7d1f.png)

Connectivity matrices:
![qsiprep-0 14 3_v3](https://user-images.githubusercontent.com/18663624/169214249-7bc91e03-cb65-4057-8454-49e5901a779f.png)
![qsiprep-0 15 4](https://user-images.githubusercontent.com/18663624/169214740-49892aa2-3b1f-4d79-afb1-152396a4ae18.png)
![sift_diff_v3](https://user-images.githubusercontent.com/18663624/169214314-71253710-dd1b-4272-ae3d-faf67af184c1.png)

Note: Original range of differences ran from a little over 40000 (0.14.3 > 0.15.4) to -80000 (0.14.3 < 0.15.4). Truncated the viewing range to a symmetric 40k.

**Comment by mattcieslak** [comment]
ok, I think we've fixed this one! Huge thanks @araikes and @sangfengchn. I'm going to deprecate the other 0.15 releases and release 0.16.0 (which will have PyAFQ workflows!) in the next couple days.

**Comment by araikes** [comment]
Thanks @mattcieslak

**Comment by sangfengchn** [comment]
Thanks so much. @mattcieslak @araikes

**Comment by sangfengchn** [comment]
> @araikes @sangfengchn when you get a chance could you try out version 0.15.4 and let me know if the alignment looks better?

I didn't finished reconstruction with the same script as the version 0.15.3. The crash information is as follows.

```bash
Node: qsirecon_wf.sub-0054_mrtrix_singleshell_ss3_hsvst.sub_0054_run_01_space_T1w_desc_preproc_recon_wf.track_ifod2.tractography
Working directory: /home/sangfeng/Desktop/Prep/work_qsiprep-0.15.4/qsirecon_wf/sub-0054_mrtrix_singleshell_ss3_hsvst/sub_0054_run_01_space_T1w_desc_preproc_recon_wf/track_ifod2/tractography

Node inputs:

act_file = <undefined>
algorithm = iFOD2
angle = <undefined>
args = <undefined>
backtrack = True
bval_scale = <undefined>
crop_at_gmwmi = True
cutoff = <undefined>
cutoff_init = <undefined>
downsample = <undefined>
environ = {}
grad_file = <undefined>
grad_fsl = <undefined>
in_bval = <undefined>
in_bvec = <undefined>
in_file = <undefined>
init_dir = <undefined>
max_length = 250.0
max_seed_attempts = <undefined>
max_tracks = <undefined>
min_length = 30.0
n_samples = 4
n_tracks = <undefined>
n_trials = <undefined>
noprecompt = <undefined>
nthreads = 5
out_bval = <undefined>
out_bvec = <undefined>
out_file = tracked.tck
out_seeds = out_seeds.nii.gz
power = 0.33
roi_excl = <undefined>
roi_incl = <undefined>
roi_mask = <undefined>
seed_dynamic = <undefined>
seed_gmwmi = <undefined>
seed_grid_voxel = <undefined>
seed_image = <undefined>
seed_rejection = <undefined>
seed_rnd_voxel = <undefined>
seed_sphere = <undefined>
select = 10000000
sph_trait = <undefined>
step_size = <undefined>
stop = <undefined>
unidirectional = <undefined>
use_rk4 = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node tractography.

RuntimeError: subprocess exited with code 1.
```

The script for preprocessing and reconstruction is 

```bash
#! /bin/bash

proj=/home/sangfeng/Desktop/Prep
raw=$proj/rawdata
der=$proj/der_qsiprep-0.15.4
work=$proj/work_qsiprep-0.15.4
simg=$proj/../Envs/qsiprep-0.15.4

# preprocess
singularity exec -e $simg qsiprep \
    $raw $der participant \
    -w $work \
    --participant-label sub-0054 \
    --output-space template \
    --output-resolution 1.0 \
    --force-syn \
    -v \
    --write-graph \
    --skip-bids-validation \
    --stop-on-first-crash \
    --fs-license-file $proj/../Envs/license.txt 

# recon
singularity exec -e $simg qsiprep \
    $raw $der participant \
    -w $work \
    --participant-label sub-0054 \
    --recon-only \
    --recon-input $der/qsiprep \
    --recon-spec mrtrix_singleshell_ss3t_ACT-hsvs \
    --output-resolution 1.0 \
    --freesurfer-input $der/freesurfer \
    --fs-license-file $proj/../Envs/license.txt

echo 'Congratulatoin! The job has been finished.'
```

**Comment by araikes** [comment]
@sangfengchn,

Is your preprocessed freesurfer data located in "der_qsiprep-0.15.4/freesurfer"? 

Also:

1.  `--participant-label` should just be 0054
2. I'm pretty sure that `--output-space template` is no longer valid. The only valid output space is T1w. @mattcieslak can correct me.

**Comment by sangfengchn** [comment]
> 

@araikes  Thanks so much. The preprocessed freesurfer is in der_qsiprep-0.15.4/freesurfer. There is no error in the report of preprocessing, and the error raise in reconstruction. I will try reconstruction again with 0054 as ```--participant-label```.

**Comment by sangfengchn** [comment]
> @sangfengchn,
> 
> Is your preprocessed freesurfer data located in "der_qsiprep-0.15.4/freesurfer"?
> 
> Also:
> 
> 1. `--participant-label` should just be 0054
> 2. I'm pretty sure that `--output-space template` is no longer valid. The only valid output space is T1w. @mattcieslak can correct me.

After correcting the -participant-label, there is still the same error in reconstruction.
```
Node: qsirecon_wf.sub-0054_mrtrix_singleshell_ss3_hsvst.sub_0054_run_01_space_T1w_desc_preproc_recon_wf.track_ifod2.tractography
Working directory: /home/sangfeng/Desktop/Prep/work_qsiprep-0.15.4/qsirecon_wf/sub-0054_mrtrix_singleshell_ss3_hsvst/sub_0054_run_01_space_T1w_desc_preproc_recon_wf/track_ifod2/tractography

Node inputs:

act_file = /home/sangfeng/Desktop/Prep/work_qsiprep-0.15.4/qsirecon_wf/sub-0054_mrtrix_singleshell_ss3_hsvst/anat_ingress_wf/apply_header_to_5tt/sub-0054_5tt_hdrxform.nii.gz
algorithm = iFOD2
angle = <undefined>
args = <undefined>
backtrack = True
bval_scale = <undefined>
crop_at_gmwmi = True
cutoff = <undefined>
cutoff_init = <undefined>
downsample = <undefined>
environ = {}
grad_file = <undefined>
grad_fsl = <undefined>
in_bval = <undefined>
in_bvec = <undefined>
in_file = /home/sangfeng/Desktop/Prep/work_qsiprep-0.15.4/qsirecon_wf/sub-0054_mrtrix_singleshell_ss3_hsvst/sub_0054_run_01_space_T1w_desc_preproc_recon_wf/ss3t_csd/intensity_norm/sub-0054_run-01_space-T1w_desc-preproc_dwi_wm_mtnorm.mif
init_dir = <undefined>
max_length = 250.0
max_seed_attempts = <undefined>
max_tracks = <undefined>
min_length = 30.0
n_samples = 4
n_tracks = <undefined>
n_trials = <undefined>
noprecompt = <undefined>
nthreads = 5
out_bval = <undefined>
out_bvec = <undefined>
out_file = tracked.tck
out_seeds = out_seeds.nii.gz
power = 0.33
roi_excl = <undefined>
roi_incl = <undefined>
roi_mask = <undefined>
seed_dynamic = /home/sangfeng/Desktop/Prep/work_qsiprep-0.15.4/qsirecon_wf/sub-0054_mrtrix_singleshell_ss3_hsvst/sub_0054_run_01_space_T1w_desc_preproc_recon_wf/ss3t_csd/intensity_norm/sub-0054_run-01_space-T1w_desc-preproc_dwi_wm_mtnorm.mif
seed_gmwmi = <undefined>
seed_grid_voxel = <undefined>
seed_image = <undefined>
seed_rejection = <undefined>
seed_rnd_voxel = <undefined>
seed_sphere = <undefined>
select = 10000000
sph_trait = <undefined>
step_size = <undefined>
stop = <undefined>
unidirectional = <undefined>
use_rk4 = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node tractography.

RuntimeError: subprocess exited with code 1.
```

**Comment by sangfengchn** [comment]
> @sangfengchn,
> 
> Is your preprocessed freesurfer data located in "der_qsiprep-0.15.4/freesurfer"?
> 
> Also:
> 
> 1. `--participant-label` should just be 0054
> 2. I'm pretty sure that `--output-space template` is no longer valid. The only valid output space is T1w. @mattcieslak can correct me.

@araikes Hi, I just want to you know the above issue is done. It was caused by command and parameters. But I don't know the more detailed reasons. It doesn't matter. 

The alignment looks well in 0.15.4. Thank you so much. @araikes @mattcieslak  

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/22000326/170849327-ee78cfa1-2c61-4ddf-b3d9-5a1f52f4b8ee.png">
