### ISSUE TITLE
Running qsiprep-docker on windows: log file output is not clear, need help!

### ISSUE THREAD

**Issue by Vasudevayo** [PennLINC/qsiprep#406]
```
Node: qsiprep_wf.single_subject_214057_wf.dwi_preproc_wf.pre_hmc_wf.merge_and_denoise_wf.raw_merge
Working directory: /scratch/qsiprep_wf/single_subject_214057_wf/dwi_preproc_wf/pre_hmc_wf/merge_and_denoise_wf/raw_merge

Node inputs:

compress = True
dtype = f4
header_source = <undefined>
in_files = <undefined>
is_dwi = True

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 521, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 639, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node raw_merge.

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 398, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/nilearn.py", line 134, in _run_interface
    new_nii = concat_imgs(self.inputs.in_files, dtype=self.inputs.dtype)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nilearn/_utils/niimg_conversions.py", line 484, in concat_niimgs
    for index, (size, niimg) in enumerate(zip(lengths, _iter_check_niimg(
  ### File "/usr/local/miniconda/lib/python3.8/site-packages/nilearn/_utils/niimg_conversions.py", line 159, in _iter_check_niimg
    raise ValueError(
**ValueError: Field of view of image #1 is different from reference FOV.**
Reference affine:
array([[  -2.        ,    0.        ,   -0.        ,  110.        ],
       [  -0.        ,    2.        ,   -0.        , -100.83050537],
       [   0.        ,    0.        ,    2.        ,  -46.40678024],
       [   0.        ,    0.        ,    0.        ,    1.        ]])
Image affine:
array([[ -2.        ,   0.        ,  -0.        , 110.        ],
       [ -0.        ,   2.        ,  -0.        , -98.11865234],
       [  0.        ,   0.        ,   2.        , -72.16949463],
       [  0.        ,   0.        ,   0.        ,   1.        ]])
Reference shape:
(110, 110, 69)
Image shape:
(110, 110, 69, 73)
```

**Comment by tsalo** [comment]
Apologies for not responding in a timely manner. I'm going to close this due to inactivity (not your fault), but for posterity it looks like the problem is that the DWI images did not have the same affines, which typically happens if the bounding box is changed between scans.
