### ISSUE TITLE
Node t1_2_mni failed to run

### ISSUE THREAD

**Issue by GalKepler** [PennLINC/qsiprep#408]
Hi,
I'm trying to run qsiprep version 0.15.3 and I receive the following error:

Node: qsiprep_wf.single_subject_211_wf.anat_preproc_wf.t1_2_mni
Working directory: /work/qsiprep_wf/single_subject_211_wf/anat_preproc_wf/t1_2_mni

Node inputs:

compress_report = auto
explicit_masking = True
flavor = precise
float = True
initial_moving_transform = <undefined>
lesion_mask = <undefined>
moving = T1w
moving_image = <undefined>
moving_mask = <undefined>
num_threads = 8
orientation = LPS
out_report = report.svg
reference = T1w
reference_image = /usr/local/miniconda/lib/python3.8/site-packages/qsiprep/data/mni_1mm_t1w_lps_brain.nii.gz
reference_mask = <undefined>
settings = <undefined>
template = MNI152NLin2009cAsym
template_resolution = 1

Traceback (most recent call last):
  File "/home/groot/.local/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/home/groot/.local/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/home/groot/.local/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/home/groot/.local/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/groot/.local/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 429, in run
    runtime = self._post_run_hook(runtime)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/niworkflows/interfaces/registration.py", line 60, in _post_run_hook
    return super(RobustMNINormalizationRPT, self)._post_run_hook(runtime)
  File "/home/groot/.local/lib/python3.8/site-packages/nipype/interfaces/mixins/reporting.py", line 50, in _post_run_hook
    self._generate_report()
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/niworkflows/interfaces/report_base.py", line 55, in _generate_report
    mask_nii = threshold_img(fixed_image_nii, 1e-3)
  File "/home/groot/.local/lib/python3.8/site-packages/nilearn/image/image.py", line 824, in threshold_img
    img_data = _safe_get_data(img, ensure_finite=True, copy_data=copy)
  File "/home/groot/.local/lib/python3.8/site-packages/nilearn/_utils/niimg.py", line 51, in _safe_get_data
    img = copy.deepcopy(img)
  File "/usr/local/miniconda/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/miniconda/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/miniconda/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/miniconda/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/miniconda/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/miniconda/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/miniconda/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/miniconda/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/miniconda/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/miniconda/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/miniconda/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/miniconda/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/miniconda/lib/python3.8/copy.py", line 161, in deepcopy
    rv = reductor(4)
  File "indexed_gzip/indexed_gzip.pyx", line 956, in indexed_gzip.indexed_gzip.IndexedGzipFile.__reduce__
  File "indexed_gzip/indexed_gzip.pyx", line 737, in indexed_gzip.indexed_gzip._IndexedGzipFile.export_index
AttributeError: '_io.BytesIO' object has no attribute 'mode'

Did anyone encounter something similar and know how to handle it?

Thanks in advance!

**Comment by mattcieslak** [comment]
are you running this on a system with memory limits? Is it in a docker or singularity container?

**Comment by GalBenZvi** [comment]
It's a singularity container, and the execution doesn't reach the memory limit as far as I can tell.

**Comment by mattcieslak** [comment]
The many threads may be causing memory to run out too. An update to a newer version likely would fix this too
