### ISSUE TITLE
Custom atlases in 0.15.4

### ISSUE THREAD

**Issue by isangfeng** [PennLINC/qsiprep#427]
Hi,

I added some new atlases into `/atlas/qsirecon_atlases/` and add the atlases information into the `atlas_config.json` in the qsiprep image with singularity sandbox format and reconstructed the structural connectome matrix, but those matrixes from the new atlases were not generated.

I tried adding a new atlas path as the input of ```--custom-atlases```, but the parameter is not supported in 0.15.4. I also tried to set the atlas path as the environment variable **QSIRECON_ATLAS**, but the matrixes from new atlases are still not generated.

I guess the '/atals/qsirecon_atlases/atlas_config.json' is not working, so I deleted the '/atlas/qsireon_atlases/' and get the error ```...FileNotFoundError: [Errno 2] No such file or directory: '/atlas/qsirecon_atlases/atlas_config.json...```. And I restored the ```/atlas/qsirecon_atlases/```, deleted the default atlas name from the  **atlas_config.json**, and added some new atlas names into the **atlas_config.json**. I got the error message as follows:

```
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/qsiprep", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/run.py", line 733, in main
    qsirecon_post_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 187, in run
    self._send_procs_to_workers(updatehash=updatehash, graph=graph)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 347, in _send_procs_to_workers
    self._clean_queue(
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 244, in _clean_queue
    raise RuntimeError("".join(result["traceback"]))
RuntimeError: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node get_atlases.

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 398, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/utils.py", line 47, in _run_interface
    atlas_configs = get_atlases(atlas_names)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/utils/atlases.py", line 26, in get_atlases
    raise Exception("Atlas %s not found in atlas_config.json" % atlas_name)
Exception: Atlas aicha384 not found in atlas_config.json
```

**Comment by sangfengchn** [comment]
Hi @mattcieslak,

Do you know how to correct the bug or add a new atlas to the reconstruction process?

**Comment by mattcieslak** [comment]
Hi @sangfengchn here is the notebook where I created the current set of atlases in 0.16.0RC1: https://github.com/PennLINC/qsiprep-atlas/blob/main/QSIRecon%20atlases.ipynb.

**Comment by mattcieslak** [comment]
I think your issue is that the reconstruction workflow you are running is looking for an atlas that's not in your atlas config. consider editing the reconstruction workflow line like here https://github.com/PennLINC/qsiprep/blob/master/qsiprep/data/pipelines/mrtrix_multishell_msmt_ACT-fast.json#L4 so it matches the keys in your atlas config

**Comment by sangfengchn** [comment]
> 

Thank you so much, @mattcieslak. I'll try again.
