### ISSUE TITLE
PyAFQ w/ MrTrix Error

### ISSUE THREAD

**Issue by smeisler** [PennLINC/qsiprep#433]
## Description
I am preprocessing HCP-like acquisitions using QSIPrep 0.16.0RC3, running both preprocessing and reconstruction in a single command. My recon-spec is custom, but starts by doing DKI and NODDI modeling (no modification), runs tractography from MrTrix MSMT HSVS (no connectivity workflows), and passes that into PyAFQ. I get an error as described below during PyAFQ; all outputs from other steps look okay.

Singularity 3.9.5, CentOs 7.6, 48 GB, 16 CPU

### Command
`singularity run -B $IMG $BIDS $DERIVATIVES participant --participant_label $SUB -w $WORK --fs-license-file $LICENSE --unringing_method mrdegibbs --denoise-method patch2self --skip-bids-validation --output_resolution 1.25 --$FS_DIR --skip-odf-reports --stop-on-first-crash --notrack --recon-spec /$CODE/pyafq_mrtrix_multishell_msmt_ACT-hsvs_DKI_NODDI.json --mem-mb 47500`

### Recon Spec
```
{
  "name": "pyafq_mrtrix_multishell_msmt_ACT-hsvs_DKI_NODDI",
  "space": "T1w",
  "atlases": [],
  "anatomical": [
    "mrtrix_5tt_hsvs"
  ],
  "nodes": [
  {
      "name": "fit_noddi",
      "action": "fit_noddi",
      "software": "AMICO",
      "input": "qsiprep",
      "output_suffix": "NODDI",
      "parameters": {
        "isExvivo": false,
        "dPar": 1.7E-3,
        "dIso": 3.0E-3
      }
    },
   {
      "name": "dki_recon",
      "software": "Dipy",
      "action": "DKI_reconstruction",
      "input": "qsiprep",
      "output_suffix": "DKI",
      "parameters": {
        "write_mif": false,
        "write_fibgz": false
      }
    },
    {
      "name": "msmt_csd",
      "software": "MRTrix3",
      "action": "csd",
      "output_suffix": "msmtcsd",
      "input": "qsiprep",
      "parameters": {
        "mtnormalize": true,
        "response": {
          "algorithm": "dhollander"
        },
        "fod": {
          "algorithm": "msmt_csd",
          "max_sh": [
            8,
            8,
            8
          ]
        }
      }
    },
    {
      "name": "track_ifod2",
      "software": "MRTrix3",
      "action": "tractography",
      "output_suffix": "ifod2",
      "input": "msmt_csd",
      "parameters": {
        "use_5tt": true,
        "method_5tt": "hsvs",
        "use_sift2": true,
        "tckgen": {
          "algorithm": "iFOD2",
          "select": 10000000,
          "max_length": 250,
          "min_length": 30,
          "power": 0.33,
          "crop_at_gmwmi": true,
          "backtrack": true
        },
        "sift2": {}
      }
    },
	{
            "name": "pyAFQ_full",
            "software": "pyAFQ",
            "action": "pyAFQ_full",
            "input": "track_ifod2",
            "output_suffix": "PYAFQ_FULL_ET",
            "parameters": {
                "use_external_tracking": true,
                "directions": "prob",
                "max_angle": 30.0,
                "sphere": "",
                "seed_mask": "",
                "seed_threshold": 0,
                "n_seeds": 1,
                "random_seeds": false,
                "rng_seed": "",
                "stop_mask": "",
                "stop_threshold": 0,
                "step_size": 0.5,
                "min_length": 10,
                "max_length": 1000,
                "odf_model": "CSD",
                "tracker": "local",
                "nb_points": false,
                "nb_streamlines": false,
                "seg_algo": "AFQ",
                "reg_algo": "",
                "clip_edges": false,
                "parallel_segmentation": "{'n_jobs': -1, 'engine': 'joblib', 'backend': 'loky'}",
                "progressive": true,
                "greater_than": 50,
                "rm_small_clusters": 50,
                "model_clust_thr": 1.25,
                "reduction_thr": 25,
                "refine": false,
                "pruning_thr": 12,
                "b0_threshold": 50,
                "prob_threshold": 0,
                "roi_dist_tie_break": false,
                "dist_to_waypoint": "",
                "rng": "",
                "return_idx": false,
                "presegment_bundle_dict": "",
                "presegment_kwargs": "{}",
                "filter_by_endpoints": true,
                "dist_to_atlas": 4,
                "save_intermediates": "",
                "n_points": 100,
                "clean_rounds": 5,
                "distance_threshold": 5,
                "length_threshold": 4,
                "min_sl": 20,
                "stat": "mean",
                "min_bval": "",
                "max_bval": "",
                "filter_b": true,
                "robust_tensor_fitting": false,
                "csd_response": "",
                "csd_sh_order": "",
                "csd_lambda_": 1,
                "csd_tau": 0.1,
                "gtol": 0.01,
                "brain_mask_definition": "",
                "bundle_info": "",
                "reg_template_spec": "mni_T1",
                "mapping_definition": "",
                "reg_subject_spec": "power_map",
                "profile_weights": "gauss",
                "scalars": "['dti_fa', 'dti_md']",
                "import_tract": "",
                "sbv_lims_bundles": "[None, None]",
                "volume_opacity_bundles": 0.3,
                "n_points_bundles": 40,
                "sbv_lims_indiv": "[None, None]",
                "volume_opacity_indiv": 0.3,
                "n_points_indiv": 40,
                "viz_backend_spec": "plotly_no_gif",
                "virtual_frame_buffer": false
            }
        }
  ]
}
```
## Relevant Log Output
```
	 [Node] Executing "run_afq" <qsiprep.interfaces.pyafq.PyAFQRecon>
INFO:nipype.workflow:[Node] Executing "run_afq" <qsiprep.interfaces.pyafq.PyAFQRecon>
220616-16:14:25,177 nipype.workflow INFO:
	 [Node] Finished "tck_sift2", elapsed time 1109.829533s.

  0%|          | 0/779288.0 [00:00<?, ?it/s]
  0%|          | 1/779288.0 [00:00<34:36:54,  6.25it/s]
....... (REMOVED FOR SPACE)
100%|█████████▉| 779093/779288.0 [03:16<00:00, 3616.20it/s]
100%|██████████| 779288/779288.0 [03:16<00:00, 3967.21it/s]ERROR:concurrent.futures:exception calling callback for <Future at 0x2b54cabafd90 state=finished raised BrokenProcessPool>
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
/usr/local/miniconda/lib/python3.8/site-packages/joblib/externals/loky/backend/resource_tracker.py:318: UserWarning: resource_tracker: There appear to be 6 leaked semlock objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
/usr/local/miniconda/lib/python3.8/site-packages/joblib/externals/loky/backend/resource_tracker.py:318: UserWarning: resource_tracker: There appear to be 2 leaked folder objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

## More information
PyAFQ wf has output CSD and DTI models, and then the job appears to hang. It did not automatically error out. Job did not hit walltime. As of right now, all subjects that have made it this far run into the same error.

**Comment by smeisler** [comment]
I just realized that the streamline count for PyAFQ in the input_trk spec is usually 1million, not 10million (like the default MrTrix tracking)! I will restart the jobs but reduce the streamline count from HSVS tracking, will close if it works.

**Comment by smeisler** [comment]
It finished without errors on a smaller connectome. Closing.
