### ISSUE TITLE
Error loading  yml plugin  using 0.16.ORc3

### ISSUE THREAD

**Issue by WilliamFCB** [PennLINC/qsiprep#438]
Hi Matt,
I started trying out  0.16.ORC3

The script apparently halted already when it tried to load a ..qsiprep_plugin.yml file

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/run.py", line 851, in build_qsiprep_workflow
    plugin_settings = loadyml(f)
TypeError: load() missing 1 required positional argument: 'Loader'

A quick and dirty web search suggested that this might be solved by using 
 yaml.safe_load(f) instead of  yaml.load(f)

thanks
William

**Comment by mattcieslak** [comment]
@WilliamFCB could you try pennbbl/qsiprep:unstable? This has the fix you proposed and should solve this issue

**Comment by WilliamFCB** [comment]
Hi Matt,

Many thanks, I will give it a go!

**Comment by mattcieslak** [comment]
Closing for now, please reopen if it's not resolved
