### ISSUE TITLE
PhaseEncodingDirection and TotalReadoutTime missing

### ISSUE THREAD

**Issue by alex-reardon** [PennLINC/qsiprep#458]
I am processing a (Phillips) dataset, and in the dwi.json sidecars there is no TotalReadoutTime (also no EstimatedTotalReadoutTime).  There is also no "PhaseEncodingDirection", however I do have "PhaseEncodingAxis".  Is there a way to run qsiprep without these values or any other way to get these parameters prior to running qsiprep?

**Comment by alex-reardon** [comment]
If I fill in PhaseEncodingDirection with the PhaseEncodingAxis value, I am able to pass bids validation however I'm not sure if this is allowed/propagating issues as I get the following error after doing that : 

  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node biascorr.

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 399, in run
    runtime = self._post_run_hook(runtime)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/mixins/reporting.py", line 50, in _post_run_hook
    self._generate_report()
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/denoise.py", line 68, in _generate_report
    input_dwi, denoised_nii, field_nii = self._get_plotting_images()
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/mrtrix.py", line 999, in _get_plotting_images
    denoised_nii = load_img(ref_name)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nilearn/image/image.py", line 1247, in load_img
    return check_niimg(img, wildcards=wildcards, dtype=dtype)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nilearn/_utils/niimg_conversions.py", line 271, in check_niimg
    raise ValueError("File not found: '%s'" % niimg)
ValueError: File not found: '/tmp/work/qsiprep_wf/single_subject_43083_wf/dwi_preproc_ses_I1530592_wf/pre_hmc_wf/merge_and_denoise_wf/dwi_denoise_ses_I1530592_dwi_wf/biascorr/sub-43083_ses-I1530592_dwi_denoised_N4.nii.gz'


QSIPrep failed: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node biascorr.

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 399, in run
    runtime = self._post_run_hook(runtime)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/mixins/reporting.py", line 50, in _post_run_hook
    self._generate_report()
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/denoise.py", line 68, in _generate_report
    input_dwi, denoised_nii, field_nii = self._get_plotting_images()
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/mrtrix.py", line 999, in _get_plotting_images
    denoised_nii = load_img(ref_name)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nilearn/image/image.py", line 1247, in load_img
    return check_niimg(img, wildcards=wildcards, dtype=dtype)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nilearn/_utils/niimg_conversions.py", line 271, in check_niimg
    raise ValueError("File not found: '%s'" % niimg)
ValueError: File not found: '/tmp/work/qsiprep_wf/single_subject_43083_wf/dwi_preproc_ses_I1530592_wf/pre_hmc_wf/merge_and_denoise_wf/dwi_denoise_ses_I1530592_dwi_wf/biascorr/sub-43083_ses-I1530592_dwi_denoised_N4.nii.gz'


Traceback (most recent call last):
  File "/usr/local/miniconda/bin/qsiprep", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/run.py", line 659, in main
    qsiprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 166, in run
    self._clean_queue(jobid, graph, result=result)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 244, in _clean_queue
    raise RuntimeError("".join(result["traceback"]))
RuntimeError: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node biascorr.

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 399, in run
    runtime = self._post_run_hook(runtime)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/mixins/reporting.py", line 50, in _post_run_hook
    self._generate_report()
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/denoise.py", line 68, in _generate_report
    input_dwi, denoised_nii, field_nii = self._get_plotting_images()
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/mrtrix.py", line 999, in _get_plotting_images
    denoised_nii = load_img(ref_name)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nilearn/image/image.py", line 1247, in load_img
    return check_niimg(img, wildcards=wildcards, dtype=dtype)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nilearn/_utils/niimg_conversions.py", line 271, in check_niimg
    raise ValueError("File not found: '%s'" % niimg)
ValueError: File not found: '/tmp/work/qsiprep_wf/single_subject_43083_wf/dwi_preproc_ses_I1530592_wf/pre_hmc_wf/merge_and_denoise_wf/dwi_denoise_ses_I1530592_dwi_wf/biascorr/sub-43083_ses-I1530592_dwi_denoised_N4.nii.gz'


Sentry is attempting to send 4 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
qsiprep: Please report errors to https://github.com/pennbbl/qsiprep/issues

**Comment by alex-reardon** [comment]
Following up.  Can you please advise?  

Thanks!
Alex

**Comment by ShreyasFadnavis** [comment]
Hi @alex-reardon -- quick question: do you have AP-PA data? What distortion correction option from QSIPrep are you using? If using SyN to do SDC, I don't think the Phase Encoding direction and ReadOut time matters as much. @mattcieslak please correct me if I'm wrong.

**Comment by mattcieslak** [comment]
If you only have PhaseEncodingAxis, you should check with the person who acquired the scans as to which scan contained which phase encoding direction. Supposing the PhaseEncodingAxis is `j`, you can decide something arbitrary but consistent like "AP will be `"PhaseEncodingDirection": "j"` and PA will be `"PhaseEncodingDirection": "j-"`. As long as you're consistent you will have good results with TOPUP/eddy

**Comment by alex-reardon** [comment]
Thank you for your responses @mattcieslak and @ShreyasFadnavis .  If I use SyN to do SDC and fill in arbitrary values for PhaseEncodingDirection and TotalReadoutTime, I get a node biascorr error.  Is this due to filling out these parameters with values that are "wrong"?  If I were to check with the person who acquired the scans and get the correct parameter values do you know if I would still get this error?  Trying to figure out if this error is related to these parameters.  I only get this error on scans acquired on Philips scanners so I'm assuming it has something to do with the dwi.json file. 


ValueError: File not found: '/tmp/work/qsiprep_wf/single_subject_43083_wf/dwi_preproc_ses_I1530592_wf/pre_hmc_wf/merge_and_denoise_wf/dwi_denoise_ses_I1530592_dwi_wf/biascorr/sub-43083_ses-I1530592_dwi_denoised_N4.nii.gz'
