### ISSUE TITLE
mtnormalize : tissue balance factors : -nan -nan -nan error. 

### ISSUE THREAD

**Issue by dyhan316** [PennLINC/qsiprep#489]
Hello!

 I am trying to run qsiprep on some data (with freesurfer data already computed), but got an `mtnormalize` error. I couldn't find this error in the issues, so I thought I might raise one!

The command I used was : 

```
singularity run --cleanenv -B ${data_pth}/:/data:ro,${sub_save_dir}/:/out,${supp_dir}:/freesurfer,${fs_dir}:/fs_input ${sing_img_dir} /data /out participant -w /out/tmp --output_resolution 1.2 --denoise_after_combining --unringing_method mrdegibbs --b0_to_t1w_transform Affine --intramodal_template_transform SyN --fs-license-file /freesurfer/license.txt --skip_bids_validation --freesurfer-input /fs_input --recon-spec mrtrix_multishell_msmt_ACT-hsvs --omp-nthreads 53
```

The error I got was :
```
Node: qsirecon_wf.sub-150901_mrtrix_multishell_msmt_hsvs.sub_150901_space_T1w_desc_preproc_recon_wf.msmt_csd.intensity_norm
Working directory: /out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/msmt_csd/intensity_norm

Node inputs:

args = <undefined>
bval_scale = <undefined>
csf_normed_odf = <undefined>
csf_odf = <undefined>
environ = {}
gm_normed_odf = <undefined>
gm_odf = <undefined>
grad_file = <undefined>
grad_fsl = <undefined>
in_bval = <undefined>
in_bvec = <undefined>
inlier_mask = inliers.nii.gz
mask_file = <undefined>
norm_image = norm.nii.gz
nthreads = 53
out_bval = <undefined>
out_bvec = <undefined>
wm_normed_odf = <undefined>
wm_odf = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node intensity_norm.

Cmdline:
	mtnormalise /out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_fod/sub-150901_space-T1w_desc-preproc_dwi_wm.mif sub-150901_space-T1w_desc-preproc_dwi_wm_mtnorm.mif /out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_fod/sub-150901_space-T1w_desc-preproc_dwi_gm.mif sub-150901_space-T1w_desc-preproc_dwi_gm_mtnorm.mif /out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/msmt_csd/estimate_fod/sub-150901_space-T1w_desc-preproc_dwi_csf.mif sub-150901_space-T1w_desc-preproc_dwi_csf_mtnorm.mif -check_mask inliers.nii.gz -mask /out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-150901_desc-brain_mask_resample.nii.gz -check_norm norm.nii.gz -nthreads 53
Stdout:

Stderr:
	
	mtnormalise: [  3%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [  5%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [  8%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 10%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 13%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 15%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 18%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 21%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 23%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 26%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 28%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 31%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 33%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 36%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 38%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 41%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 44%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 46%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 49%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 51%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 54%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 56%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 59%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 62%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 64%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 67%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 69%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 72%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 74%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 77%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 79%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 82%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 85%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 87%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 90%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 92%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 95%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [ 97%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [100%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-15
	mtnormalise: [100%] uncompressing image "/out/tmp/qsirecon_wf/sub-150901_mrtrix_multishell_msmt_hsvs/sub_150901_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/resample_mask/sub-150901_desc-brain_mask_resample.nii.gz"

	mtnormalise: [100%] performing log-domain intensity normalisation
	mtnormalise: [ERROR] Non-positive tissue balance factor was computed. Balance factors: -nan -nan -nan
Traceback:
	RuntimeError: subprocess exited with code 1.
``` 
Thank you :)

**Comment by smeisler** [comment]
Hi, I doubt this is a QSIPrep-specific error, and is probably more related to your image and how MRTrix is interacting with it. I would read more on the MRtrix community site about this error ([e.g. here](https://community.mrtrix.org/t/mtnormalise-nan-values-as-balance-factors/4552)) and see if anything you read there can help debug.

Best,
Steven

**Comment by dyhan316** [comment]
Thank you for your reply :)

**Comment by liubinpla** [comment]
Hi, I have the same problem. Have you figured out the reason and resolution? Thanks!
