### ISSUE TITLE
Import errors

### ISSUE THREAD

**Issue by araikes** [PennLINC/qsiprep#509]
Hi @mattcieslak 

I'm trying to process some test data from a new protocol we're setting up. I've had v. 016.0RC3 forever but when I run these particular data, I get the following immediately after the BIDS validator.

```
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/run.py", line 775, in build_qsiprep_workflow
    from ..workflows.base import init_qsiprep_wf
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/base.py", line 26, in <module>
    from ..interfaces import (BIDSDataGrabber, BIDSInfo, BIDSFreeSurferDir,
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/__init__.py", line 10, in <module>
    from .images import (
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/images.py", line 18, in <module>
    from dipy.io import read_bvals_bvecs
  File "/groups/adamraikes/git_repos/dipy/dipy/io/__init__.py", line 5, in <module>
    from .bvectxt import (read_bvec_file, ornt_mapping, reorient_vectors,
  File "/groups/adamraikes/git_repos/dipy/dipy/io/bvectxt.py", line 5, in <module>
    from dipy.core import gradients
  File "/groups/adamraikes/git_repos/dipy/dipy/core/gradients.py", line 10, in <module>
    from dipy.core.sphere import disperse_charges, HemiSphere
  File "/groups/adamraikes/git_repos/dipy/dipy/core/sphere.py", line 9, in <module>
    from dipy.reconst.recspeed import remove_similar_vertices
  File "dipy/reconst/recspeed.pyx", line 1, in init dipy.reconst.recspeed
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 232 from C header, got 216 from PyObject
```

I tried upgrading to 0.16.1 but get this error:

```
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/run.py", line 780, in build_qsiprep_workflow
    from ..workflows.base import init_qsiprep_wf
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/base.py", line 26, in <module>
    from ..interfaces import (BIDSDataGrabber, BIDSInfo, BIDSFreeSurferDir,
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/__init__.py", line 9, in <module>
    from ..niworkflows.interfaces.images import (TemplateDimensions, MatchHeader)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/niworkflows/interfaces/__init__.py", line 6, in <module>
    from .masks import BETRPT as BET
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/niworkflows/interfaces/masks.py", line 23, in <module>
    from . import report_base as nrc
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/niworkflows/interfaces/report_base.py", line 13, in <module>
    from ..viz.utils import cuts_from_bbox, compose_view
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/niworkflows/viz/__init__.py", line 6, in <module>
    from .plots import plot_carpet
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/niworkflows/viz/plots.py", line 16, in <module>
    from nilearn.plotting import plot_img
  File "/home/u26/adamraikes/.local/lib/python3.8/site-packages/nilearn/plotting/__init__.py", line 54, in <module>
    from .matrix_plotting import (plot_matrix, plot_contrast_matrix,
  File "/home/u26/adamraikes/.local/lib/python3.8/site-packages/nilearn/plotting/matrix_plotting.py", line 9, in <module>
    from matplotlib.tight_layout import get_renderer
ImportError: cannot import name 'get_renderer' from 'matplotlib.tight_layout' (/usr/local/miniconda/lib/python3.8/site-packages/matplotlib/tight_layout.py)
```

Any thoughts?

**Comment by araikes** [comment]
Just a note, I am using the `--cleanenv` flag for singularity but it seems like it's trying to grab nilearn from my local libraries...

**Comment by mattcieslak** [comment]
This is strange. Can you try using --containall?

**Comment by araikes** [comment]
That fixed it. Weird... never had to do that before... but it works.

Thanks.
