### ISSUE TITLE
Missing libc.so.6: version `GLIBC_2.34' and  –denoised-image-sdc  flag

### ISSUE THREAD

**Issue by WilliamFCB** [PennLINC/qsiprep#536]
Hi Matt,

I am running the latest qsiprep... apparently, version 17.0.? At least that's the version our system administrator found when generating a singularity sif.

Anyway, I got the error that libc.so.6: version `GLIBC_2.34' was not found (see below  ##################)
See the command to run qsiprep below.

An additional issue is in what circumstances would one set the  "–denoised-image-sdc" flag? Or would the "new" default behavior be recommendable for most data?  (could not find issue #449 as references in the "docs")

Cheers
William

My command is:

export SINGULARITYENV_ANTS_RANDOM_SEED=999

if [ ! -e ${DERIV_DIR} ]; then
    mkdir -p ${DERIV_DIR}
fi

time singularity run --cleanenv --contain --nv \
-B ${TOOLS_DIR} \
-B ${BIDS_DIR_TMP}/:/data_in \
-B ${RAWDATA_DIR}/:${RAWDATA_DIR} \
-B ${SCRIPTS_DIR}/:${SCRIPTS_DIR} \
-B ${DERIV_DIR}:/data_out \
-B ${WORK_DIR}:/work \
-B /tmp:/tmp \
${qsiprep_sif} \
/data_in \
/data_out \
participant \
-w /work \
--participant-label ${sub}${ses/-/} \
--skip_bids_validation \
--use-plugin ${SCRIPTS_DIR}/tmp/qsiprep_plugin/${sub}_${ses}_qsiprep_plugin.yml \
--fs-license-file ${TOOLS_DIR}/freesurfer/freesurfer.6.0.0/license.txt \
--unringing-method mrdegibbs \
--dwi-denoise-window 5 \
--output-resolution ${res} \
--hmc-model eddy \
--eddy_config ${SCRIPTS_DIR}/tmp/eddy_params/${sub}_${ses}_eddy_params.json \
--skip-t1-based-spatial-normalization \
--output-space T1w \
--nthreads  ${SLURM_CPUS_PER_TASK} \
--write-graph \
-vv

##### ERROR ###########################

Cmdline:
	dsi_studio --action=src  --bval=/work/qsiprep_wf/single_subject_via157ses01CFINskyra_wf/dwi_finalize_acq_hardi_run_01_wf/transform_dwis_t1/rotate_gradients/rotated.bval --bvec=/work/qsiprep_wf/single_subject_via157ses01CFINskyra_wf/dwi_finalize_acq_hardi_run_01_wf/transform_dwis_t1/rotate_gradients/rotated.bvec --source=/work/qsiprep_wf/single_subject_via157ses01CFINskyra_wf/dwi_finalize_acq_hardi_run_01_wf/transform_dwis_t1/merge/vol0000_trans_merged.nii --thread_count=2 --output=/work/qsiprep_wf/single_subject_via157ses01CFINskyra_wf/dwi_finalize_acq_hardi_run_01_wf/transform_dwis_t1/calculate_qc/raw_src/vol0000_trans_merged.src.gz
Stdout:

Stderr:
	dsi_studio: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /.singularity.d/libs/libGLX.so.0)
	dsi_studio: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /.singularity.d/libs/libGLdispatch.so.0)
Traceback:
	RuntimeError: subprocess exited with code 1.

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/qsiprep", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/run.py", line 671, in main
    qsiprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 212, in run
    raise error from cause
RuntimeError: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/legacymultiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node raw_src.

**Comment by mattcieslak** [comment]
Hi William, I'd hold off on using 0.17.0 for now. This should be marked as a pre-release because a bunch of the libraries are new. @richford did you run into any GLIBC issues when running 0.17.0 on your system? It's possible you need to load a more recent glibc before running singularity with this version. 

We found in ABCD that the previous QSIPrep default would result in TOPUP failing for ~10% of the subjects. If you need newer qsiprep features but want to stick closely to the behavior of the previous qsiprep version you can use the  "–denoised-image-sdc" flag. I would recommend just using the new default behavior, though.

**Comment by WilliamFCB** [comment]
Hi Matt,

Many thanks for the clarification. 
I guess the 16.1 version our system administrator installed was also a prerelease as I can see it was created on January 23rd, and the "official one was released last month as I understand. Maybe that's why I had issues running it. I can't recall what the problem was though. I will ask them to install the "real" 16.1 version 

The new default TOPUp it is  :-)
Cheers

**Comment by WilliamFCB** [comment]
Just tried the "16.1" version we installed.

I get the following error:
FATAL:   could not open image /data_in: failed to retrieve path for /data_in: lstat /data_in: no such file or directory

This is strange as 17.0 had no problems.
Is this a know "bug"?

Anyway, will ask them to install the "real" 16.1

**Comment by WilliamFCB** [comment]
Hi Matt,

Where to get the 16.1 version with the latest commits? The one on https://hub.docker.com/r/pennbbl/qsiprep/tags
is 5 months old

Cheers

**Comment by mattcieslak** [comment]
Sorry for the confusion here. 0.16.1 is 5 months old but the software release on github was only posted recently. Usually I do a better job of keeping these synchronized, but this one was very late. 

I'm not sure what's going on with /data_in, are you using a special wrapper to run qsiprep? I don't see `data_in` in the qsiprep codebase, what does your command look like?

**Comment by WilliamFCB** [comment]
See script below. Using the same script, but using qsiprep 17 ran without issues:

#SBATCH -J qsi_CPU
#SBATCH --cpus-per-task=3
#SBATCH --mem-per-cpu=8GB
#SBATCH --time=24:00:00
#SBATCH --output logs/slurm-%j.txt
#SBATCH --partition=HPC

slurmid=${SLURM_ARRAY_TASK_ID}
BIDS_DIR=${1}
RAWDATA_DIR=${BIDS_DIR}/rawdata
SCRIPTS_DIR=${2}
site=${3}
data_file=${4}


qiprep_sif="/mnt/depot64/singularity/site/qsiprep-0.16.1.sif"
DERIV_DIR="/mnt/scratch/VIA_BIDS/qsiprep/${site}_derivatives"

TOOLS_DIR="/mnt/depot64/"
WORK_DIR="/mnt/scratch/VIA_BIDS/qsiprep/qsiprep_work_${site}"

if [ ! -e ${WORK_DIR} ]; then
        mkdir -p ${WORK_DIR}
    fi

if [ ${site} == "DRCMR" ]
then
    res="1.8"
elif [ ${site} == "CFIN" ]
then
    res="2"
fi

BIDS_DIR_TMP="/mnt/scratch/VIA_BIDS/qsiprep/bids_qsiprep_${site}_tmp"

echo $RAWDATA_DIR $BIDS_DIR_TMP $SCRIPTS_DIR $WORK_DIR ${slurmid} ${site}

## ensure no header line and double quote arround variable. The latter can happen when saving csv file in libreoffice
line=$(awk "NR==${slurmid}" ${SCRIPTS_DIR}/${data_file})
sub=$(echo $line | awk -F"," '{print $1}')
ses=$(echo $line | awk -F"," '{print $2}')

log=logs/slurm.qsiprep.${sub}.${ses}-cpu.log
lock=lock/${sub}_${ses}.lock


if [ ! -e ${DERIV_DIR}/qsiprep/${sub}${ses/-/} ] && [ ! -e $log ] && [ ! -e $lock ]; then
    echo $sub $ses $i

    mv logs/slurm-${SLURM_JOBID}.txt $log

    # Create symlinks
    # This was done separately
    #echo "Create symlinks"
    #bash utils/create_symlinks.sh ${BIDS_DIR} ${BIDS_DIR_TMP} ${sub} ${ses}

    # Create eddy_param file, slspec_file and qsiprep_plugin.yml
    echo "Create eddy_param file, slspec_file and qsiprep_plugin.yml"
    bash utils/create_tmp_files.sh ${RAWDATA_DIR} ${SCRIPTS_DIR} ${sub} ${ses} --use_cuda

    #RUN QSIPREP
    export SINGULARITYENV_ANTS_RANDOM_SEED=999

    if [ ! -e ${DERIV_DIR} ]; then
        mkdir -p ${DERIV_DIR}
    fi

    time singularity run --cleanenv --contain \
    -B ${TOOLS_DIR} \
    -B ${BIDS_DIR_TMP}/:/data_in \
    -B ${RAWDATA_DIR}/:${RAWDATA_DIR} \
    -B ${SCRIPTS_DIR}/:${SCRIPTS_DIR} \
    -B ${DERIV_DIR}:/data_out \
    -B ${WORK_DIR}:/work \
    -B /tmp:/tmp \
    ${qsiprep_sif} \
    /data_in \
    /data_out \
    participant \
    -w /work \
    --participant-label ${sub}${ses/-/} \
    --skip_bids_validation \
    --use-plugin ${SCRIPTS_DIR}/tmp/qsiprep_plugin/${sub}_${ses}_qsiprep_plugin.yml \
    --fs-license-file ${TOOLS_DIR}/freesurfer/freesurfer.6.0.0/license.txt \
    --unringing-method mrdegibbs \
    --dwi-denoise-window 5 \
    --output-resolution ${res} \
    --hmc-model eddy \
    --eddy_config ${SCRIPTS_DIR}/tmp/eddy_params/${sub}_${ses}_eddy_params.json \
    --skip-t1-based-spatial-normalization \
    --output-space T1w \
    --nthreads  ${SLURM_CPUS_PER_TASK} \
    --write-graph \
    -vv

fi

**Comment by WilliamFCB** [comment]
can see the formatting is off when pasting the code here

**Comment by cookpa** [comment]
Enclose inline scripts in triple backquotes

```
script *without* markdown problems
```

**Comment by WilliamFCB** [comment]
Hi Again,

I tested 16.1, but got the same error:  " /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found " (see below ########)

Tried to run singularity without the "--contain" flag, but that did not change anything

Any ideas?

Thanks again!
 


 
singularity run --cleanenv --nv \
-B ${TOOLS_DIR} \
-B ${BIDS_DIR_TMP}:/data_in \
-B ${RAWDATA_DIR}:${RAWDATA_DIR} \
-B ${SCRIPTS_DIR}:${SCRIPTS_DIR} \
-B ${DERIV_DIR}:/data_out \
-B ${WORK_DIR}:/work \
-B /tmp:/tmp \
${qsiprep_sif} \
/data_in \
/data_out \
participant \
-w /work \
--participant-label ${sub}${ses/-/} \
--skip_bids_validation \
--use-plugin ${SCRIPTS_DIR}/tmp/qsiprep_plugin/${sub}_${ses}_qsiprep_plugin.yml \
--fs-license-file ${TOOLS_DIR}/freesurfer/freesurfer.6.0.0/license.txt \
--unringing-method mrdegibbs \
--dwi-denoise-window 5 \
--output-resolution ${res} \
--hmc-model eddy \
--eddy_config ${SCRIPTS_DIR}/tmp/eddy_params/${sub}_${ses}_eddy_params.json \
--output-space T1w \
--nthreads  ${SLURM_CPUS_PER_TASK} \
--write-graph \
-vv





####################
230323-15:24:29,833 nipype.workflow ERROR:
	 could not run node: qsiprep_wf.single_subject_via214ses01CFINskyra_wf.dwi_finalize_acq_hardi_run_01_wf.transform_dwis_t1.calculate_qc.raw_src
230323-15:24:29,841 nipype.workflow INFO:
	 crashfile: /data_out/qsiprep/sub-via214ses01CFINskyra/log/20230323-151136_d042ff75-7417-4de0-8613-eecb3b692854/crash-20230323-152034-wimb-raw_src-36104fe1-abc0-4e3d-87eb-0ad5a120d543.txt
230323-15:24:29,841 nipype.workflow INFO:
	 ***********************************
QSIPrep failed: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/legacymultiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node raw_src.

Cmdline:
	dsi_studio --action=src  --bval=/work/qsiprep_wf/single_subject_via214ses01CFINskyra_wf/dwi_finalize_acq_hardi_run_01_wf/transform_dwis_t1/rotate_gradients/rotated.bval --bvec=/work/qsiprep_wf/single_subject_via214ses01CFINskyra_wf/dwi_finalize_acq_hardi_run_01_wf/transform_dwis_t1/rotate_gradients/rotated.bvec --source=/work/qsiprep_wf/single_subject_via214ses01CFINskyra_wf/dwi_finalize_acq_hardi_run_01_wf/transform_dwis_t1/merge/vol0000_trans_merged.nii --thread_count=1 --output=/work/qsiprep_wf/single_subject_via214ses01CFINskyra_wf/dwi_finalize_acq_hardi_run_01_wf/transform_dwis_t1/calculate_qc/raw_src/vol0000_trans_merged.src.gz
Stdout:

Stderr:
	dsi_studio: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /.singularity.d/libs/libGLX.so.0)
	dsi_studio: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /.singularity.d/libs/libGLdispatch.so.0)
Traceback:
	RuntimeError: subprocess exited with code 1.

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/qsiprep", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/run.py", line 664, in main
    qsiprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 212, in run
    raise error from cause
RuntimeError: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/legacymultiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node raw_src.

Cmdline:
	dsi_studio --action=src  --bval=/work/qsiprep_wf/single_subject_via214ses01CFINskyra_wf/dwi_finalize_acq_hardi_run_01_wf/transform_dwis_t1/rotate_gradients/rotated.bval --bvec=/work/qsiprep_wf/single_subject_via214ses01CFINskyra_wf/dwi_finalize_acq_hardi_run_01_wf/transform_dwis_t1/rotate_gradients/rotated.bvec --source=/work/qsiprep_wf/single_subject_via214ses01CFINskyra_wf/dwi_finalize_acq_hardi_run_01_wf/transform_dwis_t1/merge/vol0000_trans_merged.nii --thread_count=1 --output=/work/qsiprep_wf/single_subject_via214ses01CFINskyra_wf/dwi_finalize_acq_hardi_run_01_wf/transform_dwis_t1/calculate_qc/raw_src/vol0000_trans_merged.src.gz
Stdout:

Stderr:
	dsi_studio: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /.singularity.d/libs/libGLX.so.0)
	dsi_studio: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /.singularity.d/libs/libGLdispatch.so.0)
Traceback:
	RuntimeError: subprocess exited with code 1.

Sentry is attempting to send 4 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit

**Comment by mattcieslak** [comment]
You may want to check with the system admin to see if there is a way to load a newer glibc in your environment. I've been able to get around issues like this on older CentOS machines by `module load`ing devtoolsets with newer gccs in them before running singularity

**Comment by WilliamFCB** [comment]
Oke, thanks
should I drop the "--contain" flag in this case?

**Comment by mattcieslak** [comment]
--contain should be fine, it will prevent mapping some directories like /tmp and $HOME but shouldn't affect system libraries

**Comment by WilliamFCB** [comment]
great, thanks again!

**Comment by cookpa** [comment]
I don't know if this will help, but if you want multiple library paths, you need

```
  --env LD_LIBRARY_PATH=/drcmrlib:\$LD_LIBRARY_PATH
```

This lets you append, rather than replace, `LD_LIBRARY_PATH` in the container.

One reason you are seeing this error and others are not may be that you are running with `--nv`, which requests system libraries get mapped into the container, including libGL.

**Comment by WilliamFCB** [comment]
Here are our eddy settings (see below)
Previously we successfully used qsiprep 12, patched at that time with a patch from Jesper Anderson, as the fsl was not updated to do these at the time (some years back). 


{
  "flm": "quadratic",
  "slm": "none",
  "fep": false,
  "interp": "spline",
  "nvoxhp": 1000,
  "fudge_factor": 10,
  "dont_sep_offs_move": false,
  "dont_peas": false,
  "niter": 8,
  "method": "jac",
  "repol": true,
  "num_threads": 3,
  "is_shelled": false,
  "use_cuda": true,
  "cnr_maps": true,
  "residuals": false,
  "output_type": "NIFTI_GZ",
  "args": "--very_verbose --fwhm=10,6,4,2,0,0,0,0 --ol_type=both --mporder=8 --s2v_niter=8 --slspec=/mnt/projects/VIA_BIDS/scripts/qsiprep/tmp/slspec_files/sub-via218_ses-01DRCMRprisma_slspec.txt --estimate_move_by_susceptibility"
}

**Comment by WilliamFCB** [comment]
Ok, many thanks... will try again!

**Comment by mattcieslak** [comment]
I checked in the image and there are no missing libraries for dsi studio or glibc:

```
root@b137bc3906ad:/opt/dsi-studio/dsi_studio_64# ldd dsi_studio
	linux-vdso.so.1 (0x00007fff4abcc000)
	libGLU.so.1 => /usr/lib/x86_64-linux-gnu/libGLU.so.1 (0x00007f5b7a630000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f5b7a413000)
	libQt5OpenGL.so.5 => /opt/qt512/lib/libQt5OpenGL.so.5 (0x00007f5b7b12a000)
	libQt5Charts.so.5 => /opt/qt512/lib/libQt5Charts.so.5 (0x00007f5b7a253000)
	libQt5Widgets.so.5 => /opt/qt512/lib/libQt5Widgets.so.5 (0x00007f5b79bdf000)
	libQt5Gui.so.5 => /opt/qt512/lib/libQt5Gui.so.5 (0x00007f5b79602000)
	libQt5Core.so.5 => /opt/qt512/lib/libQt5Core.so.5 (0x00007f5b7903d000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f5b78db1000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5b78b92000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5b78785000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5b783e7000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5b781cf000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5b77dde000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5b7af65000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f5b77bac000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f5b7790e000)
	libicui18n.so.60 => /usr/lib/x86_64-linux-gnu/libicui18n.so.60 (0x00007f5b7746d000)
	libicuuc.so.60 => /usr/lib/x86_64-linux-gnu/libicuuc.so.60 (0x00007f5b770b5000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5b76eb1000)
	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f5b76b9a000)
	libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007f5b76969000)
	libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007f5b766b3000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f5b763ff000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f5b761d2000)
	libicudata.so.60 => /usr/lib/x86_64-linux-gnu/libicudata.so.60 (0x00007f5b74629000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f5b743b8000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f5b74080000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f5b73e58000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f5b73c54000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f5b73a4e000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f5b73839000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f5b73631000)
root@b137bc3906ad:/opt/dsi-studio/dsi_studio_64# ldd /usr/lib/x86_64-linux-gnu/libGLX.so.0
	linux-vdso.so.1 (0x00007ffe13346000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fafddcff000)
	libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007fafdda49000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fafdd845000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fafdd626000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fafdd235000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fafdd00d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fafde268000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fafdce09000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fafdcc03000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fafdc9ee000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fafdc7e6000)
```

I think this might be an issue with your gpu/cuda setup. We're stuck with whichever cuda version FSL is using, which in our case is 10. I noticed you're using version 11, which may be ok. There are some other singularity [issues](https://github.com/apptainer/apptainer/issues/598) that might be related. Could you try out the solution from there?

**Comment by WilliamFCB** [comment]
Hi Matt,
Thanks, I will take it up with our system administrator 
Have a great weekend

**Comment by WilliamFCB** [comment]
Hi Matt,

Deleting libGLX.so(.0)`, `libglx.so(.0)`, and `libGLdispatch.so`, from `nvliblist.conf` in the singularity installation directory (in our setup .../singularity/3.11.1-ce/etc/singularity/nvliblist.conf) solved the issue

Many thanks!
