### ISSUE TITLE
"enhance_and_mask_b0" error

### ISSUE THREAD

**Issue by marcelzwiers** [PennLINC/qsiprep#547]
I have a BIDS 1.8 dataset that I tried to run using the latest 0.16.1 qsiprep (docker->singularity) image. First, through some try-out cycles I figured that qsiprep does not support BIDS 1.8 and 1.7. After downgrading/stripping my data to BIDS 1.6 I got this simple (multi-shell) test DWI dataset:

```console
$ tree bids_test/
bids_test/
|-- README
|-- participants.json
|-- participants.tsv
`-- sub-003
    |-- anat
    |   |-- sub-003_acq-MPRAGE_rec-biascorr_run-1_T1w.json
    |   |-- sub-003_acq-MPRAGE_rec-biascorr_run-1_T1w.nii.gz
    |   |-- sub-003_acq-TSE_rec-biascorr_run-1_T2w.json
    |   `-- sub-003_acq-TSE_rec-biascorr_run-1_T2w.nii.gz
    `-- dwi
        |-- sub-003_acq-HARDI_run-1_dwi.bval
        |-- sub-003_acq-HARDI_run-1_dwi.bvec
        |-- sub-003_acq-HARDI_run-1_dwi.json
        |-- sub-003_acq-HARDI_run-1_dwi.nii.gz
        |-- sub-003_acq-HARDI_run-1_sbref.json
        `-- sub-003_acq-HARDI_run-1_sbref.nii.gz
```
Unfortunately, when I ran qsiprep 0.16.1 I got this error (in short):
```logtalk 
    Running qsiprep version 0.16.1:
      * BIDS dataset path: /project/3015046.06/bids_test.
      * Participant list: ['003'].
      * Run identifier: 20230414-105803_820b66b8-9a16-4a57-b6bb-551b3fc1e35e.
    
230414-10:58:06,679 nipype.workflow INFO:
         Combining all 1 dwis within the single available session
230414-10:58:06,692 nipype.workflow INFO:
         [{'dwi_series': ['/project/3015046.06/bids_test/sub-003/dwi/sub-003_acq-HARDI_run-1_dwi.nii.gz'],
 'fieldmap_info': {'suffix': None}, 'dwi_series_pedir': 'j-', 'concatenated_bids_name': 'sub-003_acq-HARDI
_run-1'}]
230414-10:58:06,806 nipype.workflow IMPORTANT:
         Creating dwi processing workflow "dwi_preproc_acq_HARDI_run_1_wf" to produce output sub-003_acq-HARDI_run-1 (1.26 GB / 193 DWIs). Memory resampled/largemem=2.03/2.50 GB.
230414-10:58:06,808 nipype.workflow INFO:
         Automatically using 5, 5, 5 window for dwidenoise
[...]
230414-14:09:48,857 nipype.workflow INFO:
         [Node] "_mni_tpms1" found cached.
230414-14:09:48,858 nipype.workflow INFO:
         [Node] Setting-up "_mni_tpms2" in "/scratch/marzwi/48920514.dccn-l029.dccn.nl/sub-003/qsiprep_wf/
single_subject_003_wf/anat_preproc_wf/mni_tpms/mapflow/_mni_tpms2".
230414-14:09:48,859 nipype.workflow INFO:
         [Node] Cached "_mni_tpms2" - collecting precomputed outputs
230414-14:09:48,859 nipype.workflow INFO:
         [Node] "_mni_tpms2" found cached.
230414-14:09:52,418 nipype.workflow INFO:
         [Node] Finished "enhance_and_mask_b0", elapsed time 11.587746s.
230414-14:09:52,418 nipype.workflow WARNING:
         Storing result file without outputs
230414-14:09:52,418 nipype.workflow WARNING:
         [Node] Error on "qsiprep_wf.single_subject_003_wf.dwi_preproc_acq_HARDI_run_1_wf.hmc_sdc_wf.pre_eddy_b0_ref_wf.enhance_and_mask_b0" (/scratch/marzwi/48920514.dccn-l029.dccn.nl/sub-003/qsiprep_wf/single_subject_003_wf/dwi_preproc_acq_HARDI_run_1_wf/hmc_sdc_wf/pre_eddy_b0_ref_wf/enhance_and_mask_b0)
230414-14:09:52,690 nipype.workflow ERROR:
         Node enhance_and_mask_b0 failed to run on host dccn-c053.dccn.nl.
230414-14:09:52,702 nipype.workflow ERROR:
         Saving crash info to /project/3015046.06/bids_test/derivatives/qsiprep/sub-003/log/20230414-105803_820b66b8-9a16-4a57-b6bb-551b3fc1e35e/crash-20230414-140952-marzwi-enhance_and_mask_b0-6203a59a-c619-4d64-af92-951750e1499c.txt
Traceback (most recent call last):
  File "/home/mrphys/marzwi/.local/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/home/mrphys/marzwi/.local/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/home/mrphys/marzwi/.local/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/home/mrphys/marzwi/.local/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node enhance_and_mask_b0.

Traceback:
        Traceback (most recent call last):
          File "/home/mrphys/marzwi/.local/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 398, in run
            runtime = self._run_interface(runtime)
          File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/nilearn.py", line 178, in _run_interface
            mask_img = watershed_refined_b0_mask(input_img, show_plot=False,
          File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/nilearn.py", line 509, in watershed_refined_b0_mask
            calculate_gradmax_b0_mask(b0_nii, show_plot=show_plot, quantile_max=quantile_max, cwd=cwd)
          File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/nilearn.py", line 436, in calculate_gradmax_b0_mask
            opening_values = np.array([2, 4, 6, 8, 10, 12], dtype=np.int)
          File "/home/mrphys/marzwi/.local/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
            raise AttributeError(__former_attrs__[attr])
        AttributeError: module 'numpy' has no attribute 'int'.
        `np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
        The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
            https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations


230414-14:09:54,690 nipype.workflow ERROR:
         could not run node: qsiprep_wf.single_subject_003_wf.dwi_preproc_acq_HARDI_run_1_wf.hmc_sdc_wf.pre_eddy_b0_ref_wf.enhance_and_mask_b0
```
However, it all works without error if I use qsiprep 0.14.3

**Comment by smeisler** [comment]
Hi @marcelzwiers, thank you for opening this issue. I just opened a PR to replace the deprecated flag throughout the repo.
