### ISSUE TITLE
Error in T2 to T1 registration

### ISSUE THREAD

**Issue by nseider** [PennLINC/qsiprep#567]
Hey everyone.  I updated my qsiprep docker image last week, and now see the following error. Previously T2w images were ignored (I think) if a T1w was available. QSIPrep also doesn't quit when this error occurs, just hangs until manually canceled (24+ hrs allowed to hang). If the T2w NIFTI is removed from the BIDS folder, this error does not occur. 

QSIPrep version: Preprocessing was performed using *QSIPrep* 0.17.0+129.gaf71e95

230501-21:22:58,323 nipype.workflow WARNING:
         [Node] Error on "qsiprep_wf.single_subject_CC110098ss_wf.anat_preproc_wf.t2w_preproc_wf.t2_brain_to_t1_brain" (/work/qsiprep_wf/single_subject_CC110098ss_wf/anat_preproc_wf/t2w_preproc_wf/t2_brain_to_t1_brain)
exception calling callback for <Future at 0x7f0d8cf56280 state=finished raised FileNotFoundError>
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 722, in _run_command
    result = self._interface.run(cwd=outdir, ignore_exception=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 388, in run
    self._check_mandatory_inputs()
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 275, in _check_mandatory_inputs
    raise ValueError(msg)
ValueError: Registration requires a value for input 'metric'. For a list of required inputs, see Registration.help()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 70, in run_node
    result["result"] = node.result
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 223, in result
    return _load_resultfile(
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/utils.py", line 291, in load_resultfile
    raise FileNotFoundError(results_file)
FileNotFoundError: /work/qsiprep_wf/single_subject_CC110098ss_wf/anat_preproc_wf/t2w_preproc_wf/t2_brain_to_t1_brain/result_t2_brain_to_t1_brain.pklz
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
FileNotFoundError: /work/qsiprep_wf/single_subject_CC110098ss_wf/anat_preproc_wf/t2w_preproc_wf/t2_brain_to_t1_brain/result_t2_brain_to_t1_brain.pklz

**Comment by mattcieslak** [comment]
#565 should fix this, could you try using pennbbl/qsiprep:unstable and let me know if that works?

**Comment by nseider** [comment]
@mattcieslak All good now! Must have gotten a pull of qsiprep right between updates. Thanks!
