### ISSUE TITLE
Failure to process >1 T1w anat

### ISSUE THREAD

**Issue by mrribbits** [PennLINC/qsiprep#570]
Hi!  I have 2  sessions for a subject, each session has its own T1w.  I can process a single T1w no problem with a bids filter:
`"t1w": { "session": "01" }`
However if I remove that line from the bids filter, QSIprep crashes, unable to process two T1w scans. I expect the behavior should be to create a non-biased T1w for registration, based on the two.

```
230512-15:19:46,89 nipype.workflow INFO:
	 Running with omp_nthreads=8, nthreads=24
230512-15:19:46,90 nipype.workflow IMPORTANT:
	 
    Running qsiprep version 0.17.0+132.g796ebba:
      * BIDS dataset path: /data.
      * Participant list: ['97T'].
      * Run identifier: 20230512-151940_09b5f1c5-04cd-480b-a51e-06ce6858b262.
    
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/run.py", line 950, in build_qsiprep_workflow
    retval['workflow'] = init_qsiprep_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/base.py", line 228, in init_qsiprep_wf
    single_subject_wf = init_single_subject_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/base.py", line 576, in init_single_subject_wf
    anat_preproc_wf = init_anat_preproc_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/anatomical/volume.py", line 224, in init_anat_preproc_wf
    anat_reference_wf = init_anat_template_wf(longitudinal=longitudinal,
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/anatomical/volume.py", line 661, in init_anat_template_wf
    workflow.connect([
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 239, in connect
    raise Exception("\n".join(["Some connections were not found"] + infostr))
Exception: Some connections were not found
Module anat_merge_wf has no input called b0_images

Module anat_merge_wf has no output called final_template

Module anat_merge_wf has no output called final_template

Module anat_merge_wf has no output called forward_transforms
```

Running unstable version. Here's my command for reference:
```
singularity run --cleanenv \
    -B /data/bids:/data:ro \
    -B /data/bids/derivatives:/out \
    -B /work:/work \
    -B /data/license.txt:/opt/freesurfer/license.txt \
    qsiprep-unstable.sif \
    /data /out participant \
    --fs-license-file /opt/freesurfer/license.txt \
    --work_dir /work \
    --participant_label 97T \
    --stop-on-first-crash \
    --anat_only \
    --anat-modality T1w \
    --anatomical-template MNI152NLin2009cAsym \
    --bids-filter-file /data/bids-filter.json \
    --output-resolution 2.4 \
    --longitudinal \
    --verbose
```

**Comment by mattcieslak** [comment]
I just ran into this too, patch will be in on Monday

**Comment by smeisler** [comment]
Thanks, preprocessing worked for me on the alpha version when I have two time points (both with DWI and T1w), but I run into an issue when beginning QSIRecon that I do not get when processing a single timepoint data.

### CMD
`singularity run -B ${scratch},${templateflow_dir} $qsiprep_IMG --participant_label ${subject:4} -w $scratch --output_resolution 1.25 --longitudinal --unringing-method rpg --denoise_method patch2self --recon-spec $scratch/recon_spec.json --skip-bids-validation --freesurfer-input $scratch/data/derivatives/freesurfer/ --fs-license-file ${scratch}/license.txt --use-syn-sdc --skip-odf-reports --notrack --mem_mb 120000 --nthreads 16 --omp-nthreads 8 --stop-on-first-crash $scratch/data/ $scratch/data/derivatives participant
`
### ERR
```
IMPORTANT:nipype.workflow:
    Running qsirecon version 0.18.0alpha0:
      * BIDS dataset path: /om2/scratch/Fri/smeisler/READER_qsiprep/sub-reader013/data.
      * Participant list: ['reader013'].
      * Run identifier: 20230610-131757_d87cee1a-1651-463b-b148-1228473a021b.
    
230610-13:17:59,744 nipype.workflow INFO:
	 found ['/om2/scratch/Fri/smeisler/READER_qsiprep/sub-reader013/data/derivatives/qsiprep/sub-reader013/ses-post/dwi/sub-reader013_ses-post_run-1_space-T1w_desc-preproc_dwi.nii.gz', '/om2/scratch/Fri/smeisler/READER_qsiprep/sub-reader013/data/derivatives/qsiprep/sub-reader013/ses-pre/dwi/sub-reader013_ses-pre_run-1_space-T1w_desc-preproc_dwi.nii.gz'] in /om2/scratch/Fri/smeisler/READER_qsiprep/sub-reader013/data/derivatives/qsiprep
INFO:nipype.workflow:found ['/om2/scratch/Fri/smeisler/READER_qsiprep/sub-reader013/data/derivatives/qsiprep/sub-reader013/ses-post/dwi/sub-reader013_ses-post_run-1_space-T1w_desc-preproc_dwi.nii.gz', '/om2/scratch/Fri/smeisler/READER_qsiprep/sub-reader013/data/derivatives/qsiprep/sub-reader013/ses-pre/dwi/sub-reader013_ses-pre_run-1_space-T1w_desc-preproc_dwi.nii.gz'] in /om2/scratch/Fri/smeisler/READER_qsiprep/sub-reader013/data/derivatives/qsiprep
230610-13:17:59,745 nipype.workflow INFO:
	 Missing T1w QSIPrep outputs found: /om2/scratch/Fri/smeisler/READER_qsiprep/sub-reader013/data/derivatives/qsiprep/sub-reader013/anat/sub-reader013_desc-preproc_T1w.nii.gz
INFO:nipype.workflow:Missing T1w QSIPrep outputs found: /om2/scratch/Fri/smeisler/READER_qsiprep/sub-reader013/data/derivatives/qsiprep/sub-reader013/anat/sub-reader013_desc-preproc_T1w.nii.gz
230610-13:17:59,746 nipype.workflow INFO:
	 Found T1w-to-template transforms
INFO:nipype.workflow:Found T1w-to-template transforms
230610-13:17:59,747 nipype.workflow INFO:
	 Freesurfer directory /om2/scratch/Fri/smeisler/READER_qsiprep/sub-reader013/data/derivatives/freesurfer/sub-reader013 exists for reader013
INFO:nipype.workflow:Freesurfer directory /om2/scratch/Fri/smeisler/READER_qsiprep/sub-reader013/data/derivatives/freesurfer/sub-reader013 exists for reader013
230610-13:17:59,750 nipype.workflow INFO:
	 FreeSurfer data will be used to create a HSVS 5tt image.
INFO:nipype.workflow:FreeSurfer data will be used to create a HSVS 5tt image.
230610-13:17:59,751 nipype.workflow INFO:
	 Anatomical (T1w) available for recon: {'has_qsiprep_5tt_hsvs': False, 'has_freesurfer_5tt_hsvs': True, 'has_freesurfer': True, 'has_qsiprep_t1w': False, 'has_qsiprep_t1w_transforms': True}
INFO:nipype.workflow:Anatomical (T1w) available for recon: {'has_qsiprep_5tt_hsvs': False, 'has_freesurfer_5tt_hsvs': True, 'has_freesurfer': True, 'has_qsiprep_t1w': False, 'has_qsiprep_t1w_transforms': True}
Process Process-20:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 129, in validate
    value = Path(value)  # Use pathlib's validation
  File "/usr/local/miniconda/lib/python3.8/pathlib.py", line 1042, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/local/miniconda/lib/python3.8/pathlib.py", line 683, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/local/miniconda/lib/python3.8/pathlib.py", line 667, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/run.py", line 1180, in build_recon_workflow
    retval['workflow'] = init_qsirecon_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/recon/base.py", line 89, in init_qsirecon_wf
    single_subject_wf = init_single_subject_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/recon/base.py", line 232, in init_single_subject_wf
    dwi_recon_wfs[dwi_file] = init_dwi_recon_workflow(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/recon/build_workflow.py", line 50, in init_dwi_recon_workflow
    registered_anat_wf, available_anatomical_data = init_dwi_recon_anatomical_workflow(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/recon/anatomical.py", line 411, in init_dwi_recon_anatomical_workflow
    nio.FreeSurferSource(
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 202, in __init__
    self.inputs.trait_set(**inputs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/has_traits.py", line 1520, in trait_set
    setattr(self, name, value)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 131, in validate
    self.error(objekt, name, str(value))
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: The 'subjects_dir' trait of a FSSourceInputSpec instance must be a pathlike object or string representing an existing directory, but a value of 'None' <class 'str'> was specified.
```
### Other info
The `recon_spec` is a custom one with PYAFQ tractometry using a HSVS MRTrix tractogram input. But I get this error also with just `pyafq_tractometry` input.

Additionally, the preprocessed T1w image is not gzipped when doing multiple time points, not sure if that's related...
