### ISSUE TITLE
Error when using `--recon-only`

### ISSUE THREAD

**Issue by marcelzwiers** [PennLINC/qsiprep#581]
Due to a v0.16.1 issue (https://github.com/PennLINC/qsiprep/issues/547), I have preprocessed my data using v0.14.3, but now I fail to do a reconstruction. For instance when I run this (most notably `--recon-spec mrtrix_multishell_msmt_pyafq_tractometry --recon-only`):

```console
unset PYTHONPATH; export PYTHONNOUSERSITE=1
singularity run --cleanenv  --bind \$TMPDIR:/tmp /opt/qsiprep/0.14.3/qsiprep-0.14.3.sif bids bids/derivatives participant --output-resolution 1.8 -w \$TMPDIR/sub-001 --participant-label 001  --fs-license-file /opt_host/fmriprep/license.txt --mem_mb 20000 --omp-nthreads 2 --nthreads 2  --recon-spec mrtrix_multishell_msmt_pyafq_tractometry --recon-only
```
I get:

```console
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/cli/run.py", line 1166, in build_recon_workflow
    sloppy=opts.sloppy
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/recon/base.py", line 92, in init_qsirecon_wf
    sloppy=sloppy
  File "/usr/local/miniconda/lib/python3.7/site-packages/qsiprep/workflows/recon/base.py", line 147, in init_single_subject_wf
    if not op.exists(op.join(recon_input, subject_dir)):
  File "/usr/local/miniconda/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

If I try doing the reconstruction with v0.16.1 (I hope that's possible, just trying), then I get the same error:

```console
IMPORTANT:nipype.workflow:
    Running qsirecon version 0.16.1:
      * BIDS dataset path: /project/3015046.06/bids.
      * Participant list: ['001'].
      * Run identifier: 20230602-133701_d1590545-5b7c-4161-bbf5-7e669a3ea484.
    
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/run.py", line 1175, in build_recon_workflow
    retval['workflow'] = init_qsirecon_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/recon/base.py", line 89, in init_qsirecon_wf
    single_subject_wf = init_single_subject_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/recon/base.py", line 158, in init_single_subject_wf
    if not op.exists(op.join(recon_input, subject_dir)):
  File "/usr/local/miniconda/lib/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

If I leave the `--recon-only` option out (in v0.14.3) I don't get that error, but the reconstruction exceeds the maximum walltime of our cluster, i.e. 72 hour. Is that normal or is there anything I can do to fix this?

**Comment by marcelzwiers** [comment]
Btw, I also tried with a voxel size of 8 (to speed things up) and also using `--recon-spec amico_noddi` (but that also exceeded 72 hour)

**Comment by smeisler** [comment]
Hi @marcelzwiers,

In your `recon-only` version of the command, add the `--recon-input` flag, that should map to `$bids/derivatives`. I believe **both** flags are needed to skip preprocessing and go directly to recon.

In terms of your runtime, it would help to know your RAM, and you can also try upping your CPU count to something greater than 2.

Best,
Steven

**Comment by marcelzwiers** [comment]
Hi Steven, thanks a lot, using `--recon-input bids/derivatives/qsiprep` did the trick. It seems to me that the `--recon-only` flag is redundant, as it can only be used in conjunction with the `--recon-input` flag?

My NODDI reconstructions now finished rapidly, however, if I try `--recon-spec mrtrix_multishell_msmt_pyafq_tractometry` I get:

```console
IMPORTANT:nipype.workflow:
    Running qsirecon version 0.16.1:
      * BIDS dataset path: /project/3015046.06/bids.
      * Participant list: ['003'].
      * Run identifier: 20230605-142231_28e9cfc5-85d6-4ac8-9c41-2e0bc7150dbf.
    
INFO:nipype.workflow:sub-003 not in /project/3015046.06/bids/derivatives, trying recon_input=/project/3015046.06/bids/derivatives/qsiprep
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/run.py", line 1175, in build_recon_workflow
    retval['workflow'] = init_qsirecon_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/recon/base.py", line 89, in init_qsirecon_wf
    single_subject_wf = init_single_subject_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/recon/base.py", line 168, in init_single_subject_wf
    spec = _load_recon_spec(recon_spec, sloppy=sloppy)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/recon/base.py", line 257, in _load_recon_spec
    raise Exception("{} is not a file that exists or in {}".format(spec_name, prepackaged))
Exception: mrtrix_multishell_msmt_pyafq_tractometry is not a file that exists or in ['amico_noddi', 'csdsi_3dshore', 'dipy_3dshore', 'dipy_dki', 'dipy_mapmri', 'dsi_studio_gqi', 'mrtrix_multishell_msmt_ACT-fast', 'mrtrix_multishell_msmt_ACT-hsvs', 'mrtrix_multishell_msmt_noACT', 'mrtrix_singleshell_ss3t_ACT-fast', 'mrtrix_singleshell_ss3t_ACT-hsvs', 'mrtrix_singleshell_ss3t_noACT', 'mrtrix_tckglobal', 'multishell_scalarfest', 'pyafq', 'pyafq_input_trk', 'reorient_fslstd']
```

**Comment by smeisler** [comment]
In that version I think it was called `pyafq_input_trk` but in 0.17.0 it was renamed. There’s not an issue with upgrading a container just for reconstruction. That is, you wouldn’t have to preprocess data with that newer container.

**Comment by marcelzwiers** [comment]
I'm not sure if upgrading the container for reconstruction only isn't complicating this GitHub issue too much, but I tried what you suggested. Using `0.18.0alpha0` in combination with `--recon-spec mrtrix_multishell_msmt_pyafq_tractometry` I get:
```console
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/run.py", line 1055, in build_recon_workflow
    from ..workflows.recon import init_qsirecon_wf
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/recon/__init__.py", line 18, in <module>
    from .base import init_qsirecon_wf
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/recon/base.py", line 29, in <module>
    from .build_workflow import init_dwi_recon_workflow
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/recon/build_workflow.py", line 6, in <module>
    from qsiprep.interfaces import anatomical
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/__init__.py", line 10, in <module>
    from .images import (
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/images.py", line 19, in <module>
    from dipy.io import read_bvals_bvecs
  File "/usr/local/miniconda/lib/python3.8/site-packages/dipy/io/__init__.py", line 4, in <module>
    from .dpy import Dpy
  File "/usr/local/miniconda/lib/python3.8/site-packages/dipy/io/dpy.py", line 12, in <module>
    import h5py
  File "/usr/local/miniconda/lib/python3.8/site-packages/h5py/__init__.py", line 46, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py/h5t.pxd", line 14, in init h5py._conv
  File "h5py/h5t.pyx", line 293, in init h5py.h5t
  File "/home/mrphys/marzwi/.local/lib/python3.8/site-packages/numpy/__init__.py", line 320, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'typeDict'
```
Using `0.16.3` in combination with `--recon-spec pyafq_input_trk` I get much more output and errors, which I attached below
[qsiprep_sub-002.e49264394.txt](https://github.com/PennLINC/qsiprep/files/11677788/qsiprep_sub-002.e49264394.txt)
[qsiprep_sub-002.o49264394.txt](https://github.com/PennLINC/qsiprep/files/11677790/qsiprep_sub-002.o49264394.txt)

**Comment by smeisler** [comment]
Hi, you can see that it is using YOUR numpy installation:
```
File "/home/mrphys/marzwi/.local/lib/python3.8/site-packages/numpy/__init__.py", line 320, in __getattr__
    raise AttributeError("module {!r} has no attribute "
```
Can you add `--containall` to the after the `--cleanenv` flag and try again?

**Comment by marcelzwiers** [comment]
I think python should never use `.local`, it's an endless source of misery
