### ISSUE TITLE
Request for test dataset that works with QSI prep

### ISSUE THREAD

**Issue by LikithaBommasani** [PennLINC/qsiprep#587]
Hi,
I would like to request the test dataset compatible with QSI Prep as I am experiencing difficulties with my current datasets while using QSI Prep. I am unsure if the problem lies with the software or the dataset itself. Therefore, I would appreciate if you could provide me with a test dataset to determine the source of the issue and ensure proper functionality with my system. Thank you.

**Comment by mattcieslak** [comment]
Hi @LikithaBommasani, If you read through [this script](https://github.com/PennLINC/qsiprep/blob/master/.circleci/get_data.sh#L331) there are a couple locations where our testing data is downloaded from Box. There are a couple different test datasets available for you to try

**Comment by LikithaBommasani** [comment]
Thank you for your reply. I have tested it with the dataset(DSDTI) you provided. 
Even then I'm facing these errors. Could you let me know where the problem lies
 Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node synthstrip.

Cmdline:
	mri_synthstrip -i /tmp/work/qsiprep_wf/single_subject_PNC_wf/anat_preproc_wf/pad_anat_reference_wf/resample_skulled_to_reference/sub-PNC_T1w_trans.nii.gz -o sub-PNC_T1w_trans_brain.nii.gz -m sub-PNC_T1w_trans_mask.nii.gz
Stdout:

Stderr:
	Killed
Traceback:
	Traceback (most recent call last):
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 397, in run
	    runtime = self._run_interface(runtime)
	  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/freesurfer.py", line 605, in _run_interface
	    raise Exception("mri_synthstrip failed!")
	Exception: mri_synthstrip failed!


QSIPrep failed: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node synthstrip.

Cmdline:
	mri_synthstrip -i /tmp/work/qsiprep_wf/single_subject_PNC_wf/anat_preproc_wf/pad_anat_reference_wf/resample_skulled_to_reference/sub-PNC_T1w_trans.nii.gz -o sub-PNC_T1w_trans_brain.nii.gz -m sub-PNC_T1w_trans_mask.nii.gz
Stdout:

Stderr:
	Killed
Traceback:
	Traceback (most recent call last):
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 397, in run
	    runtime = self._run_interface(runtime)
	  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/freesurfer.py", line 605, in _run_interface
	    raise Exception("mri_synthstrip failed!")
	Exception: mri_synthstrip failed!


Traceback (most recent call last):
  File "/usr/local/miniconda/bin/qsiprep", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/run.py", line 677, in main
    qsiprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 178, in run
    self._clean_queue(jobid, graph, result=result)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 256, in _clean_queue
    raise RuntimeError("".join(result["traceback"]))
RuntimeError: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node synthstrip.

Cmdline:
	mri_synthstrip -i /tmp/work/qsiprep_wf/single_subject_PNC_wf/anat_preproc_wf/pad_anat_reference_wf/resample_skulled_to_reference/sub-PNC_T1w_trans.nii.gz -o sub-PNC_T1w_trans_brain.nii.gz -m sub-PNC_T1w_trans_mask.nii.gz
Stdout:

Stderr:
	Killed
Traceback:
	Traceback (most recent call last):
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 397, in run
	    runtime = self._run_interface(runtime)
	  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/freesurfer.py", line 605, in _run_interface
	    raise Exception("mri_synthstrip failed!")
	Exception: mri_synthstrip failed!


230612-19:47:57,436 nipype.workflow INFO:
	 [Node] Finished "topup", elapsed time 174.869838s.

**Comment by mattcieslak** [comment]
this looks like you're running out of memory. What are the specs on the machine you're using and what is your exact qsiprep command?

**Comment by LikithaBommasani** [comment]
The QSI prep command :  lbommasani5860$ docker run -i --rm \
> -v /Users/lbommasani5860/Desktop/DSDTI:/data:ro \
> -v /Users/lbommasani5860/Desktop/DSDTI_processed:/out \
> -v /Users/lbommasani5860/Downloads/license.txt:/out/license.txt \
> pennbbl/qsiprep:latest /data /out participant \
> --output_resolution 3 \
> --fs-license-file /out/license.txt \
> --freesurfer-input /out/sourcedata/freesurfer

**Comment by LikithaBommasani** [comment]
I do have low storage space of about 30GB right now

**Comment by mattcieslak** [comment]
by memory I mean RAM. If you're on a mac you may need to change the docker settings so at least 12GB is available

**Comment by LikithaBommasani** [comment]
got it. 
<img width="1440" alt="Screen Shot 2023-06-12 at 1 05 00 PM" src="https://github.com/PennLINC/qsiprep/assets/112617127/87354869-24dd-48c3-ab02-5f2852f172df">

**Comment by mattcieslak** [comment]
with only 8gb memory available you may want to reduce the number of cpus to 1 so multiple tasks don't run concurrently. Depending on your data 8gb may not be enough

**Comment by LikithaBommasani** [comment]
Okay thank you I'll try

**Comment by mattcieslak** [comment]
Could you try using pennbbl/qsiprep:0.18.0 as the image? I added those citations in the tagged version. This warning shouldn't affect your results other than the methods boilerplate in the html report
