### ISSUE TITLE
QSIPrep failed: 'DynamicTraitedSpec' object has no attribute 'btable_t1'

### ISSUE THREAD

**Issue by cookpa** [PennLINC/qsiprep#593]
On qsiprep 0.18.0, HCP-style dMRI data with RPE series. It fails with the error if I include `--distortion-group-merge average`.

This runs OK (so far):

```
singularity run   --cleanenv   --no-home   \
  -B /scratch/qsiprep.20746781.5YqJPRJQ.tmpdir:/tmp   \
  -B /project/ftdc_pipeline/templateflow:/opt/templateflow   \
  -B /appl/freesurfer-7.1.1:/freesurfer   \
  -B /project/picsl/cookpa/anx/bids:/data/input   \
  -B /project/picsl/cookpa/anx/preps/output:/data/output   \
  -B /project/picsl/cookpa/anx/preps/eddy_params_prisma.json:/config/eddy_params_prisma.json  \
  /project/ftdc_pipeline/ftdc-picsl/pmacsPreps-0.2.2/containers/qsiprep-0.18.0.sif   \
  /data/input /data/output participant   \
  --fs-license-file /freesurfer/license.txt  \
  --notrack   --nthreads 2   --omp-nthreads 2  \
   --work-dir /tmp   --stop-on-first-crash   --verbose   \
   --participant_label NDARPA762UGZ --output-resolution 1.5 \
  --eddy-config /config/eddy_params_prisma.json
```

but if I add `--distortion-group-merge average` I get

```
230623-15:15:24,384 nipype.workflow INFO:
	 Workflow qsiprep_wf settings: ['check', 'execution', 'logging', 'monitoring']
QSIPrep failed: 'DynamicTraitedSpec' object has no attribute 'btable_t1'
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/qsiprep", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/run.py", line 677, in main
    qsiprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 628, in run
    execgraph = generate_expanded_graph(deepcopy(flatgraph))
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/utils.py", line 967, in generate_expanded_graph
    graph_in = _remove_nonjoin_identity_nodes(graph_in, keep_iterables=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/utils.py", line 847, in _remove_nonjoin_identity_nodes
    _remove_identity_node(graph, node)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/utils.py", line 873, in _remove_identity_node
    _propagate_internal_output(graph, node, field, connections, portinputs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/utils.py", line 945, in _propagate_internal_output
    value = getattr(node.inputs, field)
AttributeError: 'DynamicTraitedSpec' object has no attribute 'btable_t1'
```

**Comment by mattcieslak** [comment]
Looks like a regression - should be a quick fix

**Comment by mattcieslak** [comment]
@cookpa could you try patching in the fix/concat-avg-btable branch? 

Also, why are you mounting the local freesurfer?

**Comment by cookpa** [comment]
Thanks! I'll check out the patch later.

Freesurfer was just for the license, I guess it's bad form to mount the entire thing, I'll change my script.

**Comment by cookpa** [comment]
Now getting a different error

```
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/run.py", line 950, in build_qsiprep_workflow
    retval['workflow'] = init_qsiprep_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/base.py", line 228, in init_qsiprep_wf
    single_subject_wf = init_single_subject_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/base.py", line 645, in init_single_subject_wf
    merging_group_workflows[merged_group] = init_distortion_group_merge_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/dwi/distortion_group_merge.py", line 194, in init_distortion_group_merge_wf
    workflow.connect([
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 239, in connect
    raise Exception("\n".join(["Some connections were not found"] + infostr))
Exception: Some connections were not found
Module btab_t1 has no output called btable_t1
```

**Comment by mattcieslak** [comment]
oof I clearly need to add some CI tests for this option. Just fixed this error, hopefully that will solve it

**Comment by cookpa** [comment]
That seems to have got it, running normally now. Thanks!
