### ISSUE TITLE
Exception: Gradients don't match. File a bug report!

### ISSUE THREAD

**Issue by kellychang4** [PennLINC/qsiprep#600]
Hello! 

I am getting an error when attempting to run QSIprep-0.18.1 on my dataset. 
```
Traceback:
	Traceback (most recent call last):
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 397, in run
	    runtime = self._run_interface(runtime)
	  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/confounds.py", line 53, in _run_interface
	    combined_out, confounds_list = _gather_confounds(
	  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/interfaces/confounds.py", line 178, in _gather_confounds
	    raise Exception("Gradients don't match. File a bug report!")
	Exception: Gradients don't match. File a bug report!
```
Full crash log: [crash-20230717-232945-root-concat-601b636a-1182-4e49-a25e-1487b7a3d661.txt](https://github.com/PennLINC/qsiprep/files/12074847/crash-20230717-232945-root-concat-601b636a-1182-4e49-a25e-1487b7a3d661.txt)

The dataset consists of 2 DWI acquisitions, each with 125 volumes, collected in the AP and the PA directions. The dataset was collected on a Philips machine and DICOMs were converted to NIfTIs with `dcm2niix`, I also manually added the PhaseEncodingDirection and TotalReadoutTime fields into the JSON sidecars. The error leads me to believe something is wrong with my metadata, but I am unsure. 

My call to `qsiprep` via Docker: 

```
docker run -it --rm \
    --platform "linux/amd64" \
    -v "${fs_license}:/license.txt" \
    -v "${paths_data}:/data" \
    -v "${paths_out}:/out" \
    -v "${paths_work}:/work" \
    pennbbl/qsiprep:0.18.1 \
    /data /out participant \
    --participant-label "${participant_label}" \
    --unringing-method mrdegibbs \
    --anatomical-template MNI152NLin2009cAsym \
    --output-resolution 1.8 \
    --fs-license-file /license.txt \
    --work-dir /work \
    -vv
```

Here is an example of the AP direction DWI JSON file:
(The only difference in the PA direction was that `"PhaseEncodingDirection": "j"`)

```
{
  "Modality": "MR",
  "MagneticFieldStrength": 3,
  "ImagingFrequency": 127.768,
  "Manufacturer": "Philips",
  "ManufacturersModelName": "Ingenia Elition X",
  "InstitutionName": "University of washington",
  "InstitutionalDepartmentName": "MRI",
  "InstitutionAddress": "1959 NE Pacific  Street",
  "DeviceSerialNumber": "45179",
  "StationName": "PHILIPS-2JLMOH3",
  "BodyPartExamined": "BRAIN",
  "PatientPosition": "HFS",
  "ProcedureStepDescription": "AIR",
  "SoftwareVersions": "5.7.1\\5.7.1.2",
  "MRAcquisitionType": "2D",
  "SeriesDescription": "DTI_APP_NEW",
  "ProtocolName": "WIP DTI_APP_NEW",
  "ScanningSequence": "SE",
  "SequenceVariant": "SK",
  "ScanOptions": "FS",
  "PulseSequenceName": "DwiSE",
  "ImageType": [
    "ORIGINAL",
    "PRIMARY",
    "M",
    "SE",
    "M",
    "SE"
  ],
  "SeriesNumber": 601,
  "AcquisitionTime": "12:33:54.790000",
  "AcquisitionNumber": 6,
  "PhilipsRWVSlope": 0.928938,
  "PhilipsRWVIntercept": 0,
  "PhilipsRescaleSlope": 0.928938,
  "PhilipsRescaleIntercept": 0,
  "PhilipsScaleSlope": 0.0296546,
  "UsePhilipsFloatNotDisplayScaling": 1,
  "SliceThickness": 2.2,
  "SpacingBetweenSlices": 2.42,
  "SAR": 0.153994,
  "EchoTime": 0.089033,
  "RepetitionTime": 3.5,
  "MTState": false,
  "FlipAngle": 90,
  "CoilString": "MULTI COIL",
  "PercentPhaseFOV": 100,
  "PercentSampling": 100,
  "EchoTrainLength": 75,
  "PartialFourierDirection": "PHASE",
  "PartialFourierEnabled": "YES",
  "PhaseEncodingStepsNoPartialFourier": 112,
  "AcquisitionMatrixPE": 112,
  "ReconMatrixPE": 112,
  "ParallelReductionFactorInPlane": 1.5,
  "ParallelAcquisitionTechnique": "MBSENSE",
  "ParallelReductionOutOfPlane": 3,
  "WaterFatShift": 21.7322,
  "EstimatedEffectiveEchoSpacing": 0.00044476,
  "EstimatedTotalReadoutTime": 0.0493683,
  "AcquisitionDuration": 467.39,
  "PixelBandwidth": 2116,
  "PhaseEncodingAxis": "j",
  "ImageOrientationPatientDICOM": [
    1,
    0,
    0,
    0,
    1,
    0
  ],
  "InPlanePhaseEncodingDirectionDICOM": "COL",
  "ConversionSoftware": "dcm2niix",
  "ConversionSoftwareVersion": "v1.0.20220720",
  "Dcm2bidsVersion": "2.1.7",
  "PhaseEncodingDirection": "j-",
  "TotalReadoutTime": 0.0493683
}
```

If you need more details, I am happy to provide them. 

Thank you, 
Kelly

**Comment by kellychang4** [comment]
I went digging a little more in the crash message and read through a [similar issue post](https://github.com/PennLINC/qsiprep/issues/503). 

It looks the`original_bval` and `bval` columns from [denoising.csv](https://github.com/PennLINC/qsiprep/files/12089813/denoising.csv) and [confounds_data.csv](https://github.com/PennLINC/qsiprep/files/12089883/confounds_data.csv), respectively, are failing the  `np.closeall` check. The difference was that the `original_bval` were 0.1s,  whereas, the `bval` were represented as 0s.

Currently, re-running the processing after rounding the b-values in the `*.bval` files to integers following the suggestions from the previous [thread](https://github.com/PennLINC/qsiprep/issues/503#issuecomment-1368138757).

**Comment by mattcieslak** [comment]
@kellychang4 thank you for opening such a detailed issue! Did your bval files come out of dcm2niix with decimals?

**Comment by kellychang4** [comment]
The `*.bval` fiels came from `dcm2niix`(version v1.0.20220720). Which were accurately reflecting the original DICOM information.  

<img width="352" alt="Screenshot 2023-07-18 at 5 37 08 PM" src="https://github.com/PennLINC/qsiprep/assets/18428145/94ccd911-2aa7-4e92-92c8-69d055f4cec5">

(Screenshot of the issue causing near-zero b-value.)

Update on processing: The same QSIPrep call from [above](https://github.com/PennLINC/qsiprep/issues/600#issue-1808883322) was completed successfully as expected after rounding the near-zero b-values to 0 (as int).

**Comment by mattcieslak** [comment]
ok great, glad to hear that it ultimately worked. Looking toward a fix for this issue do you think it would make sense to allow decimals in the bvals? Or would it be better to force the bvals to integers? I know @cookpa has also run into this

**Comment by kellychang4** [comment]
I am not sure, but @arokem might have thoughts on this point.

**Comment by arokem** [comment]
Hey! Thanks for the tag. I have been meaning to chime in here. I can't think if a reason not to allow b-values to be floating point. I believe that it will have very little impact in subsequent steps. But I might be missing something.

**Comment by mattcieslak** [comment]
My main worry is whether the decimals are worth it. Currently we have settings like `--b0-threshold 50` that suggest that the b-values can be incorrect by up to 50. 

The most important decision would be to decide how many decimals to include in the bvecs, which I don't have an intuition on. Does BIDS demand an integer for bvecs?

**Comment by arokem** [comment]
Got it. Yes, that's a good point. I think that the decimals will hardly have any effect on the final result (assuming the units are always s/mm^2). In this case, 0.1 would be treated as though it's 0 in most subsequent analysis (or the difference is miniscule), so consistently casting to int would be fine.

**Comment by cookpa** [comment]
I don't think BIDS demands an integer for bvals. It does require s/mm^2 units, so I think we should be safe to use integers.

It seems there's also questions about how precise the reported bvals are:

https://github.com/rordenlab/dcm2niix/issues/649
