### ISSUE TITLE
QSIPREP preprocessing pipeline "AttributeError: Can only use .str accessor with string values!"

### ISSUE THREAD

**Issue by Magic-Ludo** [PennLINC/qsiprep#610]
Hello everyone,

I'm putting this message here, but I'm not sure it's really a problem with QSIPREP as such...

I am trying to use qsiprep to create my own preprocessing pipeline, but the execution crashes pretty fast... I'm running the command on a compute cluster using singularity.

qsiprep 0.18.1
freesurfer-linux-centos8_x86_64-7.4.1-20230613-7eb8460
singularity 1.1.6-1.el7

Here's the command:

```EcriPark="/scratch/lcorcos/EcriPark"
sub="sub-CTR01"

source .bashrc

singularity run --cleanenv \
    -B ${HOME}/EcriPark_Code:/code,${EcriPark}:/data,/scratch/lcorcos/EcriPark_QSIPREP:/out,${FREESURFER_HOME}/license.txt,/scratch/lcorcos/Temp_QSIPREP:/tmp \
    --nv ${HOME}/qsiprep-0.18.1.sif /data/ \
    /out/ participant --participant_label ${sub} \
    --fs_license_file ${FREESURFER_HOME}/license.txt \
    --skip_bids_validation \
    --work_dir /tmp/ \
    --output_resolution 1.8 \
    --eddy_config ${HOME}/EcriPark_Code/eddy_params.json \
    --verbose \
    --anat_modality T2w \
    --b0_threshold 50 \
    --dwi_denoise_window 5 \
    --denoise-method dwidenoise \
    --unringing-method mrdegibbs \
    --distortion_group_merge average \
    --anatomical-template MNI152NLin2009cAsym \
    --bo_motion_corr_to iterative \
    --hmc_transform Affine \
    --hmc_model eddy \
    --skull_strip_template OASIS \
    --write_graph
```
Output log:
```
230809-15:13:26,886 nipype.workflow INFO:
         Running with omp_nthreads=8, nthreads=32
230809-15:13:26,895 nipype.workflow IMPORTANT:
         
    Running qsiprep version 0.18.1:
      * BIDS dataset path: /data.
      * Participant list: ['CTR01'].
(base) bash-4.2$ ./qsiprep.sh
Switching to home... Launching QSIPREP...
230809-15:25:19,451 nipype.workflow INFO:
         Running with omp_nthreads=8, nthreads=32
230809-15:25:19,459 nipype.workflow IMPORTANT:
         
    Running qsiprep version 0.18.1:
      * BIDS dataset path: /data.
      * Participant list: ['CTR01'].
      * Run identifier: 20230809-151721_144e3b1b-1514-4beb-b929-28db4f42a5ff.
    
230809-15:30:09,986 nipype.workflow INFO:
         Running nonlinear normalization to template
230809-15:30:15,33 nipype.workflow INFO:
         Combining all dwi files within each available session:
230809-15:30:15,33 nipype.workflow INFO:
                - 2 scans in session 01
230809-15:30:15,33 nipype.workflow INFO:
                - 0 scans in session pre
230809-15:30:15,33 nipype.workflow INFO:
                - 0 scans in session pst
230809-15:30:15,81 nipype.workflow INFO:
         [{'dwi_series': ['/data/sub-CTR01/ses-01/dwi/sub-CTR01_ses-01_dir-PA_dwi.nii.gz'], 'dwi_series_pedir': 'j', 'fieldmap_info': {'suffix': 'rpe_series', 'rpe_series': ['/data/sub-CTR01/ses-01/dwi/sub-CTR01_ses-01_dir-AP_dwi.nii.gz']}, 'concatenated_bids_name': 'sub-CTR01_ses-01'}]
230809-15:30:16,224 nipype.workflow IMPORTANT:
         Creating dwi processing workflow "dwi_preproc_ses_01_wf" to produce output sub-CTR01_ses-01 (1.17 GB / 119 DWIs). Memory resampled/largemem=1.66/1.84 GB.
Process Process-2:
```

Error log: 
```
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/run.py", line 950, in build_qsiprep_workflow
    retval['workflow'] = init_qsiprep_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/base.py", line 228, in init_qsiprep_wf
    single_subject_wf = init_single_subject_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/base.py", line 709, in init_single_subject_wf
    dwi_preproc_wf = init_dwi_preproc_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/dwi/base.py", line 315, in init_dwi_preproc_wf
    pre_hmc_wf = init_dwi_pre_hmc_wf(scan_groups=scan_groups,
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/dwi/pre_hmc.py", line 143, in init_dwi_pre_hmc_wf
    merge_plus = init_merge_and_denoise_wf(raw_dwi_files=plus_files,
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/dwi/merge.py", line 153, in init_merge_and_denoise_wf
    dwi_df = get_acq_parameters_df(raw_dwi_files)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/dwi/merge.py", line 506, in get_acq_parameters_df
    merged_acq_params['PhaseEncodingDirection'].str.replace("-","")
  File "/usr/local/miniconda/lib/python3.8/site-packages/pandas/core/generic.py", line 5902, in __getattr__
    return object.__getattribute__(self, name)
  File "/usr/local/miniconda/lib/python3.8/site-packages/pandas/core/accessor.py", line 182, in __get__
    accessor_obj = self._accessor(obj)
  File "/usr/local/miniconda/lib/python3.8/site-packages/pandas/core/strings/accessor.py", line 181, in __init__
    self._inferred_dtype = self._validate(data)
  File "/usr/local/miniconda/lib/python3.8/site-packages/pandas/core/strings/accessor.py", line 235, in _validate
    raise AttributeError("Can only use .str accessor with string values!")
AttributeError: Can only use .str accessor with string values!
```

Thank you for your help!

**Comment by mattcieslak** [comment]
could you try running with --containall instead of --cleanenv?

**Comment by Magic-Ludo** [comment]
Same error :/

I've also tried to delete this two options:
```
--hmc_transform Affine \
--hmc_model eddy \
```

But still the same error

**Comment by mattcieslak** [comment]
The problem seems to be in your json sidecars. The PhaseEncodingDirection needs to be a string. More details are [here](https://bids-specification.readthedocs.io/en/stable/glossary.html#objects.metadata.PhaseEncodingDirection) I strongly suggest not using `--skip-bids-validation` when you're trying out qsiprep on new data
