### ISSUE TITLE
`qsiprep` says BIDS dir does not exist

### ISSUE THREAD

**Issue by jhlegarreta** [PennLINC/qsiprep#612]
I would like to use `qsiprep` to preprocess some dMRI data.

I am using a sandbox-built Singularity image (as building the image failed otherwise), and I am calling `qsiprep` using the following script:

```
#!/bin/bash

fs_license_path=/usr/local/freesurfer/license.txt

singularity_image_path=/mnt/data/containers/qsiprep/qsiprep-0.19.0.sif
in_bids_path=/mnt/data/my/path/
participant="0001"
out_path=/mnt/data/test_qsiprep/

recon_input=$bids_path
output_resolution=1

work_dir=/mnt/data/workdir/

singularity run --cleanenv \
  --bind $in_bids_path:/data:ro \
  --bind $out_path:/out \
  --bind $fs_license_path:/opt/freesurfer/license.txt \
  --bind $work_dir \
  $singularity_image_path \
  $in_bids_path \
  $out_path \
  participant \
  --output-resolution $output_resolution \
  --fs-license-file /opt/freesurfer/license.txt \
  --work_dir $work_dir \
```
The script yields:

```
Making sure the input data is BIDS compliant (warnings can be ignored in most cases).
/mnt/data/my/path/ does not exist
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/qsiprep", line 8, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/run.py", line 607, in main
    validate_bids(opts)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/run.py", line 552, in validate_bids
    validate_input_dir(os.name, opts.bids_dir, opts.participant_label)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/utils/bids.py", line 299, in validate_input_dir
    subprocess.check_call(['bids-validator', bids_dir, '-c', temp.name])
  File "/usr/local/miniconda/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bids-validator', PosixPath('/mnt/data/my/path/'), '-c', '/tmp/tmpg23aj4lu']' returned non-zero exit status 2.
```

I know I can bypass the BIDS compliance step, but I want to check it. A few notes:
- I have previously validated the BIDS directory with the JS BIDS validator, with a successful result:
```
$ bids-validator /mnt/data/my/path/
bids-validator@1.12.0
This dataset appears to be BIDS compatible.
        Summary:                  Available Tasks:        Available Modalities: 
        21 Files, 512.32MB                                MRI
        1 - Subject 
        1 - Session

	If you have any questions, please post on https://neurostars.org/tags/bids.
```
- The path `/mnt/data/my/path/` does exist. If I do
```
mypath="/mnt/data/my/path/"
res = Path.exists(Path(mypath))
```
in Python, it returns true.
- *Note*: `/mnt/data/my/path/` is a renamed path for illustrative purposes.

What am I missing?

**Comment by jhlegarreta** [comment]
When skipping the bids-validation, as expected, the pipeline fails down the line:
```
(...)
  --skip_bids_validation
```

results in
```
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/run.py", line 833, in build_qsiprep_workflow
    layout = BIDSLayout(
  File "/usr/local/miniconda/lib/python3.8/site-packages/bids/layout/layout.py", line 135, in __init__
    root, description = validate_root(root, validate)
  File "/usr/local/miniconda/lib/python3.8/site-packages/bids/layout/validation.py", line 70, in validate_root
    raise ValueError("BIDS root does not exist: %s" % root)
ValueError: BIDS root does not exist: /mnt/data/my/path/
```

**Comment by jhlegarreta** [comment]
@mattcieslak do you have any suggestion ? Thanks.

**Comment by mattcieslak** [comment]
I think the issue is that you're mounting the inputs and outputs under different names. Maybe if you try

```
singularity run --cleanenv \
  --bind $in_bids_path \
  --bind $out_path \
  --bind $fs_license_path:/opt/freesurfer/license.txt \
  --bind $work_dir \
  $singularity_image_path \
  $in_bids_path \
  $out_path \
  participant \
  --output-resolution $output_resolution \
  --fs-license-file /opt/freesurfer/license.txt \
  --work_dir $work_dir \
```

**Comment by jhlegarreta** [comment]
@mattcieslak thanks for the suggestion. That worked: maybe I was too naïve when following the instructions in here:
https://qsiprep.readthedocs.io/en/latest/installation.html#singularity-container

Let me know if the target directory should be removed (same in Docker instructions maybe?), and I'll open a PR.

**Comment by mattcieslak** [comment]
I think those instructions are still correct, which part would you suggest changing?

**Comment by jhlegarreta** [comment]
> I think those instructions are still correct, which part would you suggest changing?

Following your answer in https://github.com/PennLINC/qsiprep/issues/612#issuecomment-1686926858, I had to remove the destination folders
```
(...)
  --bind $in_bids_path:/data:ro \
  --bind $out_path:/out \
(...)
```
to
```
(...)
  --bind $in_bids_path \
  --bind $out_path \
(...)
```

The read-only flag would have probably been OK, but specifying the target folders within the singularity image seemed to cause the issue.

**Comment by mattcieslak** [comment]
ah, yes I agree this is a better way to do it. A PR would be much appreciated, thank you!

**Comment by jhlegarreta** [comment]
OK. Will do Matt before the end of the week. I'm closing the issue.
