### ISSUE TITLE
dipy_3dshore crashes for qsiprep 0.19

### ISSUE THREAD

**Issue by dkp** [PennLINC/qsiprep#636]
Environment: HPC apptainer
Although I successfully ran dipy_3dshore on the HPC with qsiprep 0.18, it now crashes with qsiprep 0.19:

```
export RECON_SPEC=dipy_3dshore

apptainer run --cleanenv \
--bind ${DATA}:/data:ro \
--bind ${APP_PREP_DERIV_DIR}:/qsiprep-output:ro \
--bind ${APP_DERIV_DIR}:/out \
--bind ${WORK_DIR}:/work \
${APP} /data /out participant \
--participant_label ${Subject} \
--recon-input /qsiprep-output \
--recon-spec ${RECON_SPEC} \
--stop-on-first-crash \
--output-resolution 1.3 -w /work -v -v  \
--n-cpus 16 --omp-nthreads 15 \
--skip-odf-reports --recon-only \
--fs-license-file ${HOME}/license.txt \
--freesurfer_input ${FREESURFER_DIR}
```

The SLURM log says:
```
INFO:    underlay of /etc/localtime required more than 50 (103) bind mounts
230913-12:04:06,98 nipype.workflow IMPORTANT:
         
    Running qsirecon version 0.19.0:
      * BIDS dataset path: /data.
      * Participant list: ['CAM003'].
      * Run identifier: 20230913-120403_cabe0c58-9f70-4ccc-bd8d-2dbdd6bac3ac.
    
IMPORTANT:nipype.workflow:
    Running qsirecon version 0.19.0:
      * BIDS dataset path: /data.
      * Participant list: ['CAM003'].
      * Run identifier: 20230913-120403_cabe0c58-9f70-4ccc-bd8d-2dbdd6bac3ac.
    
230913-12:04:06,351 nipype.workflow INFO:
         found ['/qsiprep-output/sub-CAM003/ses-01brain/dwi/sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_dwi.nii.gz'] in /qsiprep-output
INFO:nipype.workflow:found ['/qsiprep-output/sub-CAM003/ses-01brain/dwi/sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_dwi.nii.gz'] in /qsiprep-output
230913-12:04:06,352 nipype.workflow INFO:
         Found usable QSIPrep-preprocessed T1w image and mask.
INFO:nipype.workflow:Found usable QSIPrep-preprocessed T1w image and mask.
230913-12:04:06,353 nipype.workflow INFO:
         Found T1w-to-template transforms
INFO:nipype.workflow:Found T1w-to-template transforms
230913-12:04:06,364 nipype.workflow INFO:
         Freesurfer directory /groups/dkp/Batch/CAM003_bids_data/derivatives/fmriprep_dev/sourcedata/freesurfer/sub-CAM003 exists for CAM003
INFO:nipype.workflow:Freesurfer directory /groups/dkp/Batch/CAM003_bids_data/derivatives/fmriprep_dev/sourcedata/freesurfer/sub-CAM003 exists for CAM003
230913-12:04:06,391 nipype.workflow INFO:
         Anatomical (T1w) available for recon: {'has_qsiprep_5tt_hsvs': False, 'has_freesurfer_5tt_hsvs': False, 'has_freesurfer': True, 'has_qsiprep_t1w': True, 'has_qsiprep_t1w_transforms': True}
INFO:nipype.workflow:Anatomical (T1w) available for recon: {'has_qsiprep_5tt_hsvs': False, 'has_freesurfer_5tt_hsvs': False, 'has_freesurfer': True, 'has_qsiprep_t1w': True, 'has_qsiprep_t1w_transforms': True}
230913-12:04:06,395 nipype.workflow INFO:
         Transforming ODF ROIs into DWI space for visual report.
INFO:nipype.workflow:Transforming ODF ROIs into DWI space for visual report.
230913-12:04:06,466 nipype.interface INFO:
         skipping ODF plots for recon_3dshore
INFO:nipype.interface:skipping ODF plots for recon_3dshore
230913-12:04:06,472 nipype.interface INFO:
         skipping ODF plots for tractography
INFO:nipype.interface:skipping ODF plots for tractography
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/run.py", line 1180, in build_recon_workflow
    retval['workflow'] = init_qsirecon_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/recon/base.py", line 89, in init_qsirecon_wf
    single_subject_wf = init_single_subject_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/recon/base.py", line 232, in init_single_subject_wf
    dwi_recon_wfs[dwi_file] = init_dwi_recon_workflow(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/recon/build_workflow.py", line 85, in init_dwi_recon_workflow
    new_node = workflow_from_spec(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/recon/build_workflow.py", line 186, in workflow_from_spec
    return init_dsi_studio_tractography_wf(**kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/recon/dsi_studio.py", line 198, in init_dsi_studio_tractography_wf
    DSIStudioTracking(
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 629, in __init__
    super(CommandLine, self).__init__(**inputs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 202, in __init__
    self.inputs.trait_set(**inputs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/has_traits.py", line 1520, in trait_set
    setattr(self, name, value)
traits.trait_errors.TraitError: **Cannot set the undefined 'method' attribute of a 'DSIStudioTrackingInputSpec' object.**
Detailed performance metrics for this job will be available at https://metrics.hpc.arizona.edu/#job_viewer?action=show&realm=SUPREMM&resource_id=4&local_job_id=1620893 by 8am on 2023/09/14.
```

**Comment by dkp** [comment]
**csdsi_3dshore** also fails with a slightly different message:
 
```
INFO:    underlay of /etc/localtime required more than 50 (103) bind mounts
230913-12:15:26,943 nipype.workflow IMPORTANT:
         
    Running qsirecon version 0.19.0:
      * BIDS dataset path: /data.
      * Participant list: ['CAM003'].
      * Run identifier: 20230913-121524_f6133a85-15f8-40dd-af2f-ac5c2edbc9ee.
    
IMPORTANT:nipype.workflow:
    Running qsirecon version 0.19.0:
      * BIDS dataset path: /data.
      * Participant list: ['CAM003'].
      * Run identifier: 20230913-121524_f6133a85-15f8-40dd-af2f-ac5c2edbc9ee.
    
230913-12:15:27,184 nipype.workflow INFO:
         found ['/qsiprep-output/sub-CAM003/ses-01brain/dwi/sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_dwi.nii.gz'] in /qsiprep-output
INFO:nipype.workflow:found ['/qsiprep-output/sub-CAM003/ses-01brain/dwi/sub-CAM003_ses-01brain_dir-AP_space-T1w_desc-preproc_dwi.nii.gz'] in /qsiprep-output
230913-12:15:27,186 nipype.workflow INFO:
         Found usable QSIPrep-preprocessed T1w image and mask.
INFO:nipype.workflow:Found usable QSIPrep-preprocessed T1w image and mask.
230913-12:15:27,187 nipype.workflow INFO:
         Found T1w-to-template transforms
INFO:nipype.workflow:Found T1w-to-template transforms
230913-12:15:27,199 nipype.workflow INFO:
         Freesurfer directory /groups/dkp/Batch/CAM003_bids_data/derivatives/fmriprep_dev/sourcedata/freesurfer/sub-CAM003 exists for CAM003
INFO:nipype.workflow:Freesurfer directory /groups/dkp/Batch/CAM003_bids_data/derivatives/fmriprep_dev/sourcedata/freesurfer/sub-CAM003 exists for CAM003
230913-12:15:27,223 nipype.workflow INFO:
         Anatomical (T1w) available for recon: {'has_qsiprep_5tt_hsvs': False, 'has_freesurfer_5tt_hsvs': False, 'has_freesurfer': True, 'has_qsiprep_t1w': True, 'has_qsiprep_t1w_transforms': True}
INFO:nipype.workflow:Anatomical (T1w) available for recon: {'has_qsiprep_5tt_hsvs': False, 'has_freesurfer_5tt_hsvs': False, 'has_freesurfer': True, 'has_qsiprep_t1w': True, 'has_qsiprep_t1w_transforms': True}
230913-12:15:27,228 nipype.workflow INFO:
         Transforming ODF ROIs into DWI space for visual report.
INFO:nipype.workflow:Transforming ODF ROIs into DWI space for visual report.
230913-12:15:27,298 nipype.interface INFO:
         skipping ODF plots for csdsi_3dshore
INFO:nipype.interface:skipping ODF plots for csdsi_3dshore
230913-12:15:27,304 nipype.interface INFO:
         skipping ODF plots for streamline_connectivity
INFO:nipype.interface:skipping ODF plots for streamline_connectivity
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/cli/run.py", line 1180, in build_recon_workflow
    retval['workflow'] = init_qsirecon_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/recon/base.py", line 89, in init_qsirecon_wf
    single_subject_wf = init_single_subject_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/recon/base.py", line 232, in init_single_subject_wf
    dwi_recon_wfs[dwi_file] = init_dwi_recon_workflow(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/recon/build_workflow.py", line 85, in init_dwi_recon_workflow
    new_node = workflow_from_spec(
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/recon/build_workflow.py", line 188, in workflow_from_spec
    return init_dsi_studio_connectivity_wf(**kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/workflows/recon/dsi_studio.py", line 408, in init_dsi_studio_connectivity_wf
    DSIStudioAtlasGraph(num_threads=omp_nthreads, **params),
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 563, in __init__
    super(SimpleInterface, self).__init__(
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 202, in __init__
    self.inputs.trait_set(**inputs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/has_traits.py", line 1520, in trait_set
    setattr(self, name, value)
traits.trait_errors.TraitError: **Cannot set the undefined 'method' attribute of a 'DSIStudioAtlasGraphInputSpec' object.**
Detailed performance metrics for this job will be available at https://metrics.hpc.arizona.edu/#job_viewer?action=show&realm=SUPREMM&resource_id=4&local_job_id=1620895 by 8am on 2023/09/14.
```

**Comment by mattcieslak** [comment]
Ah! There is an update to the DSI Studio in qsiprep. You can copy the json file from [here](https://github.com/PennLINC/qsiprep/blob/fix/csdsi_dsi_studio/qsiprep/data/pipelines/csdsi_3dshore.json) or [here](https://github.com/PennLINC/qsiprep/blob/fix/csdsi_dsi_studio/qsiprep/data/pipelines/dipy_3dshore.json), bind them into your container and point `--recon-spec` to the location of the json file in the container.

I missed this bug because I don't have these workflows being CI tested. I figured no one was going to use them. Are you collecting CSDSI data? If so - awesome! There may be other places in this json file you could change to improve performance depending on your acquisition.

**Comment by dkp** [comment]
Honestly, I'm just trying to learn what each of these reconstruction techniques does, in an effort to improve my understanding.  Is CSDSI data "cartesian" data?  If so, perhaps my test data (3 shell) is not appropriate?
I will try the alternative JSON files you have provided.  Thank you!

**Comment by mattcieslak** [comment]
CSDSI is usually a random subset of a cartesian acquisition that you extrapolate into a full cartesian or shelled dataset. The method is [one of my favorites](https://www.biorxiv.org/content/10.1101/2023.02.22.529546v1.abstract) but is very rare still.

**Comment by dkp** [comment]
**dipy_3dshore**
This is better than it was.  It finishes and creates all the same output files as qsiprep018, but it produces a crash log complaining about the schaefer100 atlas.  I'm attaching the crash log.  After the crash, it just ran until the SLURM job timed out. 

I'm trying again just to see if it might be happier.

[crash-20231004-152921-dkp-calc_connectivity-ac479fbe-13c1-4788-9846-6fb819e9acf9.txt](https://github.com/PennLINC/qsiprep/files/12821076/crash-20231004-152921-dkp-calc_connectivity-ac479fbe-13c1-4788-9846-6fb819e9acf9.txt)

**Comment by dkp** [comment]
**csdsi_3dshore.json**
The revised version crashes immediately, like its predecessor. It does not even get a chance to write a log, but I'm attaching the slurm log.

Here's the apptainer command I use for all of these tests:
apptainer run --cleanenv \
--bind ${DATA}:/data:ro \
--bind ${APP_PREP_DERIV_DIR}:/qsiprep-output:ro \
--bind ${APP_DERIV_DIR}:/out \
--bind ${WORK_DIR}:/work \
${APP} /data /out participant \
--participant_label ${Subject} \
--recon-input /qsiprep-output \
--recon-spec ${RECON_SPEC} \
--stop-on-first-crash \
--output-resolution 1.3 -w /work -v -v  \
--n-cpus 16 --omp-nthreads 15 \
--skip-odf-reports --recon-only \
--fs-license-file ${HOME}/license.txt \
--freesurfer_input ${FREESURFER_DIR}

[slurm-1639048_csdsi_3dshore_crash.txt](https://github.com/PennLINC/qsiprep/files/12821258/slurm-1639048_csdsi_3dshore_crash.txt)

**Comment by mattcieslak** [comment]
I think this is actually a new feature in DSI Studio that I didn't know about:

```
[1;34mpost-tracking analysis[0m
		│ │ │ connectivity=/work/qsirecon_wf/sub-CAM003_convert_shore_recons/sub_CAM003_ses_01brain_dir_AP_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/get_atlases/tpl-MNI152NLin2009cAsym_res-01_atlas-Schaefer2018Ext_desc-100Parcels7NetworksLPS_dseg_to_dwi.nii.gz
		│ │ │ connectivity_type=pass,end
		│ │ │ connectivity_value=count,ncount,mean_length,gfa
		│ │ │ connectivity_output=matrix,connectogram,measure
		│ │ │ loading /work/qsirecon_wf/sub-CAM003_convert_shore_recons/sub_CAM003_ses_01brain_dir_AP_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/get_atlases/tpl-MNI152NLin2009cAsym_res-01_atlas-Schaefer2018Ext_desc-100Parcels7NetworksLPS_dseg_to_dwi.nii.gz
		│ │ │ reading /work/qsirecon_wf/sub-CAM003_convert_shore_recons/sub_CAM003_ses_01brain_dir_AP_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/get_atlases/tpl-MNI152NLin2009cAsym_res-01_atlas-Schaefer2018Ext_desc-100Parcels7NetworksLPS_dseg_to_dwi.nii.gz as a NIFTI regioin file
		│ │ │ tpl-MNI152NLin2009cAsym_res-01_atlas-Schaefer2018Ext_desc-100Parcels7NetworksLPS_dseg_to_dwi has mni in the file name. It will be loaded as an MNI space image
		│ │ ├─[1;34mload NIFTI file[0m
		│ │ │ │ tpl-MNI152NLin2009cAsym_res-01_atlas-Schaefer2018Ext_desc-100Parcels7NetworksLPS_dseg_to_dwi loaded as multiple ROI file
		│ │ │ │ looking for region label file:/work/qsirecon_wf/sub-CAM003_convert_shore_recons/sub_CAM003_ses_01brain_dir_AP_space_T1w_desc_preproc_recon_wf/qsirecon_anat_wf/get_atlases/tpl-MNI152NLin2009cAsym_res-01_atlas-Schaefer2018Ext_desc-100Parcels7NetworksLPS_dseg_to_dwi.txt
```

We don't want this file treated as being in MNI space! I will open a bug report in DSI Studio.

**Comment by dkp** [comment]
Thanks!  I'm just experimenting and trying to learn. qsirecon is a lot of fun!

**Comment by frankyeh** [comment]
Sorry for the trouble due to the update. Some users would like to treat the NIFTI file as MNI space regions, but sometime it is the opposite. Any suggestion to tell whether the NIFTI is MNI or native? (and I will fix accordingly right away)

**Comment by dkp** [comment]
That is a good question! The files are the typical output of qsiprep, as specified here: 
https://qsiprep.readthedocs.io/en/latest/preprocessing.html#outputs-of-qsiprep

In particular, I ran qsiprep this way (which, I believe is pretty typical)
singularity run --cleanenv --bind ${DATA}:/data:ro  --bind ${APP_DERIV_DIR}:/out  \
--bind ${WORK_DIR}:/work ${APP} /data /out participant --participant_label \
${Subject} --fs-license-file ${HOME}/license.txt --output-resolution 1.3 --n_cpus 16 -w /work -v -v

dim1            124
dim2            152
dim3            132
1.3 mm isotropic voxels

**Comment by frankyeh** [comment]
I did a code review. The message is going to be a false alarm because DSI Studio eventually treats it as the DWI space region.
If the region were normalized from template to native space, there would be a message showing 'warping xxxx from the template space to the native space'

I am modifying the code to prompt a makeup message (sometime like "the regions were treated as DWI regions because the image dimension is identical to DWI data"

**Comment by frankyeh** [comment]
A modification is committed to provide a more accurate message:
https://github.com/frankyeh/DSI-Studio/commit/3f85d732c1e05c58deaf00520608dffc58142d99

Thanks again for reporting this issue.

**Comment by mattcieslak** [comment]
Thank you @frankyeh!!

@dkp there must be something else happening here then. It looks like gfa isn't being stored in the fib file (`[1;31mERROR: Cannot quantify matrix value using gfa[0m`) I'm not sure why this might be

**Comment by frankyeh** [comment]
gfa is not a default output of a FIB unless specified in the reconstruction:
--other_output=fa,ad,rd,md,iso,rdi,nrdi,gfa
or --other_output=all

**Comment by mattcieslak** [comment]
Whenever a fib file is created in qsiprep the `--other_output=all` flag is [added by default](https://github.com/PennLINC/qsiprep/blob/b719e7836cd080cc358f7fd3d4c7b641db1efdb2/qsiprep/interfaces/dsi_studio.py#L215). Since the GQI workflow is passing the CI tests something else is probably going on with this specific workflow. 

@dkp if you're trying out reconstruction workflows I'd recommend `dsi_studio_autotrack`.

**Comment by dkp** [comment]
I have tried autotrack, and it works
