### ISSUE TITLE
Path to MNI T2 template

### ISSUE THREAD

**Issue by nseider** [PennLINC/qsiprep#648]
Hello,

I have data that has a T2w image instead of a T1w image.  The T2w MNI template that QSIPrep tries to find has a different name than the one inside the package.  QSIPrep version, command, error message, and correct path are copied below. 

TLDR, it's looking for file name "mni_1mm_t2w_lps.nii.gz" which appears to be renamed to "mni_1mm_t2w_lps_brain.nii.gz"

VSN: qsiprep version 0.19.1

Command: qsiprep-docker /data/bids/ /data/qsiprep_out/ participant --output-resolution 2 --participant_label sub-setA --skip-bids-validation --anat-modality T2w --hmc_model tensor --pepolar-method DRBUDDI --nthreads 4 --omp-nthreads 4 --work-dir /data/qsiprep_out/work/ --fs-license-file /data/license.txt 

Traceback Error: 
        Traceback (most recent call last):
          File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 453, in aggregate_outputs
            setattr(outputs, key, val)
          File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
            value = super(File, self).validate(objekt, name, value, return_pathlike=True)
          File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
            self.error(objekt, name, str(value))
          File "/usr/local/miniconda/lib/python3.8/site-packages/traits/base_trait_handler.py", line 74, in error
            raise TraitError(
        traits.trait_errors.TraitError: The 'template_file' trait of a _GetTemplateOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/data/mni_1mm_t2w_lps.nii.gz' <class 'str'> was specified.

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 400, in run
            outputs = self.aggregate_outputs(runtime)
          File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 460, in aggregate_outputs
            raise FileNotFoundError(msg)
        FileNotFoundError: No such file or directory '/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/data/mni_1mm_t2w_lps.nii.gz' for output 'template_file' of a GetTemplate interface
        
Template name inside docker container:
/usr/local/miniconda/lib/python3.8/site-packages/qsiprep/data/mni_1mm_t2w_lps_brain.nii.gz

**Comment by mattcieslak** [comment]
Hi Nicole, Thanks for opening this issue, should be a straightforward fix

**Comment by mb3152** [comment]
Thanks Matt! Anyway you can cherry pick this commit into 23.5.6-nofsl,

**Comment by mattcieslak** [comment]
I believe this is fixed now, 0.20 should work
