### ISSUE TITLE
Memory issues on very high-resolution data with many directions

### ISSUE THREAD

**Issue by tsalo** [PennLINC/qsiprep#692]
The complex denoising OpenNeuro test dataset ([`ds004666`](https://openneuro.org/datasets/ds004666)) contains a session with 0.9 mm3 voxels and 199 directions. I tried processing the job with a job memory limit of 64 GB and an `--mem_mb` value of `48000` (48 GB). This session is included as a "barely-usable" case for the sake of testing denoising methods, but it is so high resolution and has so many directions that QSIPrep failed with the following error:

```
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.10/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node biascorr.

Cmdline:
        dwibiascorrect ants -ants.b [150,3] -ants.c [200x200,1e-6] -bias vol0000_trans_merged_bias.nii.gz -fslgrad /cbica/projects/aslprep/qsiprep-complex/work/qsiprep_0p9mm_complex/qsiprep_wf/single_subject_01_wf/dwi_finalize_ses_0p9mm_dir_AP_run_04_part_mag_wf/$
Stdout:

Stderr:
       	dwibiascorrect:
        dwibiascorrect: Note that this script makes use of commands / algorithms that have relevant articles for citation; INCLUDING FROM EXTERNAL SOFTWARE PACKAGES. Please consult the help page (-help option) for more information.
        dwibiascorrect:
        dwibiascorrect: Generated scratch directory: /cbica/projects/aslprep/qsiprep-complex/work/qsiprep_0p9mm_complex/qsiprep_wf/single_subject_01_wf/dwi_finalize_ses_0p9mm_dir_AP_run_04_part_mag_wf/final_denoise_wf/biascorr/dwibiascorrect-tmp-3N7PLB/
        Command:  mrconvert /cbica/projects/aslprep/qsiprep-complex/work/qsiprep_0p9mm_complex/qsiprep_wf/single_subject_01_wf/dwi_finalize_ses_0p9mm_dir_AP_run_04_part_mag_wf/transform_dwis_t1/merge/vol0000_trans_merged.nii /cbica/projects/aslprep/qsiprep-comple$
        Command:  mrconvert /cbica/projects/aslprep/qsiprep-complex/work/qsiprep_0p9mm_complex/qsiprep_wf/single_subject_01_wf/dwi_finalize_ses_0p9mm_dir_AP_run_04_part_mag_wf/transform_dwis_t1/final_b0_ref/synthstrip_wf/mask_to_original_grid/vol0000_trans_merged$
        dwibiascorrect: Changing to scratch directory (/cbica/projects/aslprep/qsiprep-complex/work/qsiprep_0p9mm_complex/qsiprep_wf/single_subject_01_wf/dwi_finalize_ses_0p9mm_dir_AP_run_04_part_mag_wf/final_denoise_wf/biascorr/dwibiascorrect-tmp-3N7PLB/)
        Command:  dwiextract in.mif - -bzero | mrmath - mean mean_bzero.mif -axis 3

        dwibiascorrect: [ERROR] dwiextract in.mif - -bzero | mrmath - mean mean_bzero.mif -axis 3 (ants.py:64)
        dwibiascorrect: [ERROR] Information from failed command:
        dwibiascorrect:
                       	dwiextract: [ERROR] No b=0 volumes present
                        mrmath: [ERROR] no filename supplied to standard input (broken pipe?)
                        mrmath: [ERROR] error opening image "-"
        dwibiascorrect:
        dwibiascorrect: [ERROR] For debugging, inspect contents of scratch directory: /cbica/projects/aslprep/qsiprep-complex/work/qsiprep_0p9mm_complex/qsiprep_wf/single_subject_01_wf/dwi_finalize_ses_0p9mm_dir_AP_run_04_part_mag_wf/final_denoise_wf/biascorr/dwi$
        dwibiascorrect: Scratch directory retained; location: /cbica/projects/aslprep/qsiprep-complex/work/qsiprep_0p9mm_complex/qsiprep_wf/single_subject_01_wf/dwi_finalize_ses_0p9mm_dir_AP_run_04_part_mag_wf/final_denoise_wf/biascorr/dwibiascorrect-tmp-3N7PLB/
Traceback:
	Traceback (most recent call last):
          File "/usr/local/miniconda/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 398, in run
            runtime = self._post_run_hook(runtime)
          File "/usr/local/miniconda/lib/python3.10/site-packages/nipype/interfaces/mixins/reporting.py", line 50, in _post_run_hook
            self._generate_report()
          File "/usr/local/miniconda/lib/python3.10/site-packages/qsiprep/interfaces/denoise.py", line 68, in _generate_report
            input_dwi, denoised_nii, field_nii = self._get_plotting_images()
          File "/usr/local/miniconda/lib/python3.10/site-packages/qsiprep/interfaces/mrtrix.py", line 1188, in _get_plotting_images
            denoised_nii = load_img(ref_name)
          File "/usr/local/miniconda/lib/python3.10/site-packages/nilearn/image/image.py", line 1334, in load_img
            return check_niimg(img, wildcards=wildcards, dtype=dtype)
          File "/usr/local/miniconda/lib/python3.10/site-packages/nilearn/_utils/niimg_conversions.py", line 306, in check_niimg
            raise ValueError(f"File not found: '{niimg}'")
        ValueError: File not found: '/cbica/projects/aslprep/qsiprep-complex/work/qsiprep_0p9mm_complex/qsiprep_wf/single_subject_01_wf/dwi_finalize_ses_0p9mm_dir_AP_run_04_part_mag_wf/final_denoise_wf/biascorr/vol0000_trans_merged_N4.nii.gz'
```

While this situation won't be common, there are other datasets that we _may_ want to process with QSIPrep with similar parameters, including the HCP 7T DWI data (1.1 x 1.1 x 2.1 mm voxels; 284 directions), so we probably want to implement something like the `--low-mem` option in the future.

**Comment by tsalo** [comment]
It still failed when I gave the job 200 GB.

**Comment by mattcieslak** [comment]
Did this ever work?

**Comment by tsalo** [comment]
We did get it to work somehow, but I deleted our testing folder like two weeks ago. 🙃

**Comment by mattcieslak** [comment]
Then the issue is solved!
