### ISSUE TITLE
Referencing a non-existing variable when using QSIRecon with mrtrix_multishell_msmt_ACT-hsvs specs.

### ISSUE THREAD

**Issue by GalKepler** [PennLINC/qsiprep#717]
## Summary
A variable (`has_qsiprep_t1w`) is referenced before its assignment.

## Additional details
- QSIPrep version: 0.20.0
- Docker version:  20.10.21

### What were you trying to do?
I'm trying to use qsirecon with the preconfigured `mrtrix_multishell_msmt_ACT-hsvs` specs using the following command:

```
docker run --rm -it -v /media/hdd/ConnectomePlasticity/MRI/license.txt:/opt/freesurfer/license.txt:ro -v /media/hdd/ConnectomePlasticity/MRI/rawdata_BIDSBase_dwipa:/data:ro -v /media/hdd/ConnectomePlasticity/MRI/derivatives_dwipa/bids_filters.json:/sngl/filter/filter.json:ro -v /media/hdd/ConnectomePlasticity/MRI/derivatives_dwipa:/out -v /media/hdd/ConnectomePlasticity/MRI/derivatives_dwipa/freesurfer:/fs_dir -v /media/hdd/ConnectomePlasticity/MRI/derivatives_dwipa/qsiprep:/qsiprep_dir -v /media/hdd/ConnectomePlasticity/MRI/work:/scratch pennbbl/qsiprep:0.20.0 /data /out participant --bids-filter-file /sngl/filter/filter.json --participant_label 37 --skip_bids_validation -w /scratch --nthreads 10 --recon_input /qsiprep_dir --recon_spec mrtrix_multishell_msmt_ACT-hsvs --freesurfer_input /fs_dir --output-resolution 1.6
```

### What actually happened?
I receive the following:
```
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.10/site-packages/qsiprep/cli/run.py", line 1198, in build_recon_workflow
    retval['workflow'] = init_qsirecon_wf(
  File "/usr/local/miniconda/lib/python3.10/site-packages/qsiprep/workflows/recon/base.py", line 99, in init_qsirecon_wf
    single_subject_wf = init_single_subject_wf(
  File "/usr/local/miniconda/lib/python3.10/site-packages/qsiprep/workflows/recon/base.py", line 208, in init_single_subject_wf
    anat_ingress_node, available_anatomical_data = init_highres_recon_anatomical_wf(
  File "/usr/local/miniconda/lib/python3.10/site-packages/qsiprep/workflows/recon/anatomical.py", line 162, in init_highres_recon_anatomical_wf
    if has_qsiprep_t1w:
NameError: name 'has_qsiprep_t1w' is not defined
```
## Reproducing the bug
Preprocessing was finished without any issues using QSIPrep, so I'm not sure what is happening in the location of T1w data...

**Comment by GalKepler** [comment]
Just saw that this issue was also raised in #705, closing.
