### ISSUE TITLE
FUGUE error (no attribute 'FUGUEvsm2ANTSwarp')

### ISSUE THREAD

**Issue by jhauneuro** [PennLINC/qsiprep#789]
## Summary
This issue ([#752](https://github.com/PennLINC/qsiprep/issues/752#issue-2303840605)) was reported previously and closed but I am still getting an error when I run the latest qsiprep on dwi data using gradient echo field maps (2 phases):

```
Traceback (most recent call last):
  File "/opt/conda/envs/qsiprep/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/conda/envs/qsiprep/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/qsiprep/cli/run.py", line 1091, in build_qsiprep_workflow
    retval["workflow"] = init_qsiprep_wf(
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/qsiprep/workflows/base.py", line 237, in init_qsiprep_wf
    single_subject_wf = init_single_subject_wf(
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/qsiprep/workflows/base.py", line 748, in init_single_subject_wf
    dwi_preproc_wf = init_dwi_preproc_wf(
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/qsiprep/workflows/dwi/base.py", line 406, in init_dwi_preproc_wf
    hmc_wf = init_fsl_hmc_wf(
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/qsiprep/workflows/dwi/fsl.py", line 422, in init_fsl_hmc_wf
    b0_sdc_wf = init_sdc_wf(
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/qsiprep/workflows/fieldmap/base.py", line 244, in init_sdc_wf
    sdc_unwarp_wf = init_sdc_unwarp_wf(
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/qsiprep/workflows/fieldmap/unwarp.py", line 180, in init_sdc_unwarp_wf
    vsm2dfm = pe.Node(itk.FUGUEvsm2ANTSwarp(), name="vsm2dfm")
AttributeError: module 'niworkflows.interfaces.itk' has no attribute 'FUGUEvsm2ANTSwarp'
```

## Additional details
- QSIPrep version: 0.22.0
- Docker version: 25.0.4

### What were you trying to do?
Preprocess dwi data using the gradient echo field map distortion correction method.

### What did you expect to happen?
Completely successfully and output corrected dwi data.

### What actually happened?
Got an error (see above).

## Reproducing the bug
The command I ran:

```
docker run --rm -ti -v /usr/local/freesurfer/7.4.1/license.txt:/opt/freesurfer/license.txt:ro -v $bids_dir:/data:ro -v $out_dir:/out -v $out_dir:/scratch pennbbl/qsiprep:latest /data /out participant --output-resolution $res --bids-database-dir $bids_dir -w /scratch --participant_label $subj_id
```

**Comment by mattcieslak** [comment]
@tsalo are the gre fieldmap CI tests missing this? I thought we added them

**Comment by tsalo** [comment]
That import is what was changed in #769. @jhauneuro are you 100% sure you are using QSIPrep 0.22.0?

**Comment by jhauneuro** [comment]
@taslo, @mattcieslak I realized I had both `pennbbl/qsiprep:latest` and `qsiprep:latest` and mixed them up. I just tested on `0.22.0` and it completed successfully. Sorry about the confusion. Thank you!
