### ISSUE TITLE
EDDY_CUDA Failure: GPU can only use 1 CPU thread

### ISSUE THREAD

**Issue by amirhusseinab** [PennLINC/qsiprep#790]
## Summary

Running with an eddy_config file to utilize CUDA and mporder results in an error in eddy_cuda step:
```
EddyInputError: The version compiled for GPU can only use 1 CPU thread (i.e. --nthr=1)
Terminating program
```

## Additional details

- QSIPrep version: 0.22.0
- Docker version:
- Singularity version: 

### What were you trying to do?
The command I used:
```
singularity run --nv --cleanenv -B $TMPDIR:$TMPDIR \
-B /path/to/input/bids/directory:/input \
-B /path/to/toolboxes/folder:/toolboxes \
toolboxes/qsiprep-v0.22.0.sif /input/ /input/derivatives/qsiprep_0.22.0/ participant \
--fs-license-file toolboxes/license.txt \
--participant-label $subjid --output-resolution 1.25 \
--denoise-method dwidenoise --unringing-method mrdegibbs \
--hmc-model eddy --eddy-config /input/code/eddy_params.json --pepolar-method TOPUP \
--anat-modality T1w --anatomical-template MNI152NLin2009cAsym --b0_to_t1w_transform Rigid \
--freesurfer-input /input/derivatives/freesurfer -w /path/to/work \
--stop-on-first-crash --nthreads 30 --skip_bids_validation
```

The config file:
```
{
  "flm": "quadratic",
  "slm": "linear",
  "fep": false,
  "interp": "spline",
  "nvoxhp": 1000,
  "fudge_factor": 10,
  "dont_sep_offs_move": false,
  "dont_peas": false,
  "niter": 5,
  "method": "jac",
  "repol": true,
  "num_threads": 1,
  "is_shelled": true,
  "use_cuda": true,
  "cnr_maps": true,
  "residuals": true,
  "output_type": "NIFTI_GZ",
  "estimate_move_by_susceptibility": true,
  "mporder": 6,
  "args": "--ol_nstd=5"
}
```
### What did you expect to happen?
To have a successful preprocessing :)
### What actually happened?
Despite explicitly setting num_threads to 1 in the eddy_config, It prints out:
```
240725-14:26:19,338 nipype.workflow INFO:
	 Using 8 threads in eddy
```
And later it fails with an error:
```
EddyInputError: The version compiled for GPU can only use 1 CPU thread (i.e. --nthr=1)
Terminating program
```
In the output log file, the --nthr flag in eddy_cuda is also set to 8.

**Comment by amirhusseinab** [comment]
Update:

Setting --omp-nthreads 1 fixes the issue as expected, but the processing time of non-eddy functions is a lot.

**Comment by araikes** [comment]
This was fixed in #788 (merged yesterday)

**Comment by amirhusseinab** [comment]
I had this issue with 0.22.0 - downloaded today.

**Comment by amirhusseinab** [comment]
I think this is also relevant - on overriding the default eddy with eddy_config.json, in the boilerplate it says:
"Groups deviating by more than 4 standard deviations from the prediction had their data replaced with imputed values"
I think it is set by ol_nstd argument in eddy_config which I have set to 5 rather than the default 4.

**Comment by julfou81** [comment]
I got the same issue with qsiprep 0.22.0 downloaded this week (`QSIPrep version 0.22.1.dev0+gd9279db.d20240719`).
I am using singularity (`apptainer version 1.3.2-1.el7`)

eddy_params.json file:
```
{
  "flm": "quadratic",
  "slm": "linear",
  "fep": false,
  "interp": "spline",
  "nvoxhp": 1000,
  "fudge_factor": 10,
  "dont_sep_offs_move": false,
  "dont_peas": false,
  "niter": 5,
  "method": "jac",
  "repol": true,
  "num_threads": 1,
  "is_shelled": true,
  "use_cuda": true,
  "cnr_maps": true,
  "residuals": true,
  "output_type": "NIFTI_GZ",
  "estimate_move_by_susceptibility": true,
  "mporder": 5,
  "args": "--ol_nstd=5"
}
```

Error message:
```
line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node eddy.

Cmdline:
	eddy_cuda10.2 --ol_nstd=5 --cnr_maps --estimate_move_by_susceptibility --field=/work/temp_data24_EcriPark/qsiprep_0_22_wf/sub_CTR03_wf/dwi_preproc_ses_01_wf/hmc_sdc_wf/topup/fieldmap_HZ --field_mat=/work/temp_data24_EcriPark/qsiprep_0_22_wf/sub_CTR03_wf/dwi_preproc_ses_01_wf/hmc_sdc_wf/topup_to_eddy_reg/topup_reg_image_flirt.mat --flm=quadratic --ff=10.0 --acqp=/work/temp_data24_EcriPark/qsiprep_0_22_wf/sub_CTR03_wf/dwi_preproc_ses_01_wf/hmc_sdc_wf/gather_inputs/eddy_acqp.txt --bvals=/work/temp_data24_EcriPark/qsiprep_0_22_wf/sub_CTR03_wf/dwi_preproc_ses_01_wf/pre_hmc_wf/rpe_concat/merge__merged.bval --bvecs=/work/temp_data24_EcriPark/qsiprep_0_22_wf/sub_CTR03_wf/dwi_preproc_ses_01_wf/pre_hmc_wf/rpe_concat/merge__merged.bvec --imain=/work/temp_data24_EcriPark/qsiprep_0_22_wf/sub_CTR03_wf/dwi_preproc_ses_01_wf/pre_hmc_wf/rpe_concat/merge__merged.nii.gz --index=/work/temp_data24_EcriPark/qsiprep_0_22_wf/sub_CTR03_wf/dwi_preproc_ses_01_wf/hmc_sdc_wf/gather_inputs/eddy_index.txt --mask=/work/temp_data24_EcriPark/qsiprep_0_22_wf/sub_CTR03_wf/dwi_preproc_ses_01_wf/hmc_sdc_wf/transform_mask_to_eddy/topup_imain_corrected_avg_trans_mask_trans_flirt.nii.gz --interp=spline --data_is_shelled --json=/work/temp_data24_EcriPark/qsiprep_0_22_wf/sub_CTR03_wf/dwi_preproc_ses_01_wf/pre_hmc_wf/merge_plus/merge_dwis/merged_metadata.json --resamp=jac --mporder=5 --niter=5 --nthr=8 --nvoxhp=1000 --out=/work/temp_data24_EcriPark/qsiprep_0_22_wf/sub_CTR03_wf/dwi_preproc_ses_01_wf/hmc_sdc_wf/eddy/eddy_corrected --repol --residuals --slm=linear
Stdout:

	Warning: In a future release the first argument will have to be "diffusion" when using eddy on diffusion data, i.e.
	eddy diffusion --imain='my_ima' --acqp='my_acqp' ...

	Warning: Writing of individual text files will be discontinued in favour of a single .json file in future versions

	EddyInputError:  The version compiled for GPU can only use 1 CPU thread (i.e. --nthr=1)
	Terminating program
Stderr:

Traceback:
	Traceback (most recent call last):
	  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 453, in aggregate_outputs
	    setattr(outputs, key, val)
	  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
	    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
	  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
	    self.error(objekt, name, str(value))
	  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/traits/base_trait_handler.py", line 74, in error
	    raise TraitError(
	traits.trait_errors.TraitError: The 'out_parameter' trait of an ExtendedEddyOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/work/temp_data24_EcriPark/qsiprep_0_22_wf/sub_CTR03_wf/dwi_preproc_ses_01_wf/hmc_sdc_wf/eddy/eddy_corrected.eddy_parameters' <class 'str'> was specified.

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 400, in run
	    outputs = self.aggregate_outputs(runtime)
	  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 460, in aggregate_outputs
	    raise FileNotFoundError(msg)
	FileNotFoundError: No such file or directory '/work/temp_data24_EcriPark/qsiprep_0_22_wf/sub_CTR03_wf/dwi_preproc_ses_01_wf/hmc_sdc_wf/eddy/eddy_corrected.eddy_parameters' for output 'out_parameter' of a ExtendedEddy interface
```

Along the log file I noticed the following message:
```
241016-08:59:47,813 nipype.workflow INFO:
	 Using 8 threads in eddy
```

**Comment by mattcieslak** [comment]
did this get un-fixed somehow in the recent versions?

**Comment by araikes** [comment]
I ran it without any issue on `0.22.1` over the weekend.

**Comment by julfou81** [comment]
Thank you @mattcieslak and @araikes for your quick answers. I didn't see that 0.22.1 (and I saw also 0.23.0) was out.

For my test with QSIprep v0.22.0, here is the command I tried:
```
singularity run -e --containall --cleanenv -B /scratch/jsein/BIDS:/work \
 --nv /scratch/jsein/my_images/qsiprep-0.22.0.sif  /work/$study  \
 /work/$study/derivatives/qsiprep24 participant --participant_label $sub     \
 -w /work/temp_data24_${study} --output-resolution 1.8  --fs-license-file /work/freesurfer/license.txt \
  --eddy-config /work/$study/code/qsiprep/eddy_params24.json   \
 --b0-threshold 50 --unringing-method mrdegibbs  --denoise-method dwidenoise  \
 --distortion-group-merge none  \
 ```

and here is the eddy config file `eddy_params24.json`:
```
{
  "flm": "quadratic",
  "slm": "linear",
  "fep": false,
  "interp": "spline",
  "nvoxhp": 1000,
  "fudge_factor": 10,
  "dont_sep_offs_move": false,
  "dont_peas": false,
  "niter": 5,
  "method": "jac",
  "repol": true,
  "num_threads": 1,
  "is_shelled": true,
  "use_cuda": true,
  "cnr_maps": true,
  "residuals": true,
  "output_type": "NIFTI_GZ",
  "estimate_move_by_susceptibility": true,
  "mporder": 5,
  "args": "--ol_nstd=5"
}
```

I will try QSIPREP v0.22.1 ASAP.

**Comment by julfou81** [comment]
Indeed, QSIprep v0.22.1 seems to work as expected (same appraiser command in both cases)

QSIprep v0.22.0:
```
241016-18:09:43,498 nipype.workflow INFO:
	 Using 8 threads in eddy
```

QSIprep v0.22.1:
```
241016-21:13:10,334 nipype.workflow INFO:
	 Using CUDA and 1 threads in eddy
```

**Comment by julfou81** [comment]
Unfortunately, for QSIprep v0.21.4, v0.22.0, v0.22.1 and 0.23.1, there is still the issue #797.
