### ISSUE TITLE
TOPUP distortion correction field is flipped for my LAS oriented dwi data

### ISSUE THREAD

**Issue by jhauneuro** [PennLINC/qsiprep#793]
## Summary
Qsiprep flips the PE direction of my TOPUP distortion correction field. This issue has been reported and fixed for fmriprep here: [FIX: Revise the TOPUP workflow and related utilities](https://github.com/nipreps/sdcflows/pull/278#top) #278. Could this fix also be applied to qsiprep?

## Additional details
- QSIPrep version: 0.20.0
- Docker version: 25.0.4

### What were you trying to do?
Preprocess my dwi data.

### What did you expect to happen?
Successfully preprocess my dwi data and correct for image distortions.

### What actually happened?
The dwi output are not corrected for susceptibility distortions because the distortion correction field is flipped (shows opposite contrast to correct distortion field for the data).

## Reproducing the bug
I ran the following command:
```
docker run -ti --rm --gpus all \
	-v /usr/local/freesurfer/7.4.1/license.txt:/opt/freesurfer/license.txt:ro \
	-v $bids_dir:/data:ro \
	-v $eddy_config_file:/sngl/eddy/eddy_config.json:ro \
	-v $out_dir:/out \
	-v $out_dir:/scratch \
	pennbbl/qsiprep:latest /data /out participant \
	--eddy-config /sngl/eddy/eddy_config.json \
	--output-resolution $res --pepolar-method TOPUP \
	--distortion-group-merge average \
	--bids-database-dir $bids_dir \
	-w /scratch --omp-nthreads 1 --nthreads 1 --participant_label $subjID
```

**Comment by mattcieslak** [comment]
Thanks for reporting @jhauneuro. How do you typically convert your data from dicom? Are you not using dcm2niix?

**Comment by jhauneuro** [comment]
@mattcieslak I normally use dcm2niix for conversion to nifti. This particular dataset uses a GE research sequence that requires a different conversion process of reconstructing the images from the raw k-space data (P-files). Because of this I am using in-house recon scripts provided by the imaging center (CFMRI/UCSD) where we are collecting these data. dcm2niix fails on the dicoms (it looks like it doesn't integrate the multiband data well).

I tested the latest qsiprep (0.22.0) and get a new error regarding this option `--distortion-group-merge average`. The error message is below:

```
Traceback (most recent call last):
  File "/opt/conda/envs/qsiprep/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/conda/envs/qsiprep/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/qsiprep/cli/workflow.py", line 160, in build_workflow
    retval["workflow"] = workflow_builder()
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/qsiprep/workflows/base.py", line 82, in init_qsiprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/qsiprep/workflows/base.py", line 295, in init_single_subject_wf  
    merging_group_workflows[merged_group] = init_distortion_group_merge_wf(
TypeError: init_distortion_group_merge_wf() got an unexpected keyword argument 'template'
```
