### ISSUE TITLE
bvec/bval files with suffix like "run-1" and "run-2" do not combine

### ISSUE THREAD

**Issue by weiwei-wch** [PennLINC/qsiprep#906]
## Summary
Hi, recently I tried the newest version of qsiprep (1.0.0rc2), I meet several problems:
1. the data in different `acq` do not merge as one file like in the old version (0.22.0), this prolem is like #897, I try to add `MultipartID` in the json file, while nothing have changed, is this implemented?
2. the data in different `run`, like `run-1` and `run-2`, do not merge and cause an error, which seems caused by the unmerged bvec/bval file.
3. the SDC was not performed, even I have both PA and AP phase encoding file, I tried remove one run of PA data, but the SDC still not happen.

the BIDS structure is like follow:
```
sub-N0016F00nLHX_ses-0W_acq-b0d6_dir-PA_run-1_dwi.bval
sub-N0016F00nLHX_ses-0W_acq-b0d6_dir-PA_run-1_dwi.bvec
sub-N0016F00nLHX_ses-0W_acq-b0d6_dir-PA_run-1_dwi.json
sub-N0016F00nLHX_ses-0W_acq-b0d6_dir-PA_run-1_dwi.nii.gz
sub-N0016F00nLHX_ses-0W_acq-b0d6_dir-PA_run-2_dwi.bval
sub-N0016F00nLHX_ses-0W_acq-b0d6_dir-PA_run-2_dwi.bvec
sub-N0016F00nLHX_ses-0W_acq-b0d6_dir-PA_run-2_dwi.json
sub-N0016F00nLHX_ses-0W_acq-b0d6_dir-PA_run-2_dwi.nii.gz
sub-N0016F00nLHX_ses-0W_acq-b1000d32_dir-AP_dwi.bval
sub-N0016F00nLHX_ses-0W_acq-b1000d32_dir-AP_dwi.bvec
sub-N0016F00nLHX_ses-0W_acq-b1000d32_dir-AP_dwi.json
sub-N0016F00nLHX_ses-0W_acq-b1000d32_dir-AP_dwi.nii.gz
sub-N0016F00nLHX_ses-0W_acq-b2000d32_dir-AP_dwi.bval
sub-N0016F00nLHX_ses-0W_acq-b2000d32_dir-AP_dwi.bvec
sub-N0016F00nLHX_ses-0W_acq-b2000d32_dir-AP_dwi.json
sub-N0016F00nLHX_ses-0W_acq-b2000d32_dir-AP_dwi.nii.gz
sub-N0016F00nLHX_ses-0W_acq-b3000d32_dir-AP_run-1_dwi.bval
sub-N0016F00nLHX_ses-0W_acq-b3000d32_dir-AP_run-1_dwi.bvec
sub-N0016F00nLHX_ses-0W_acq-b3000d32_dir-AP_run-1_dwi.json
sub-N0016F00nLHX_ses-0W_acq-b3000d32_dir-AP_run-1_dwi.nii.gz
sub-N0016F00nLHX_ses-0W_acq-b3000d32_dir-AP_run-2_dwi.bval
sub-N0016F00nLHX_ses-0W_acq-b3000d32_dir-AP_run-2_dwi.bvec
sub-N0016F00nLHX_ses-0W_acq-b3000d32_dir-AP_run-2_dwi.json
sub-N0016F00nLHX_ses-0W_acq-b3000d32_dir-AP_run-2_dwi.nii.gz
```

The results I get are seperated for each `acq`, and those data with `run-1` and `run-2` are not excuted in results and here is the error details in the report file:

```
File: <workdir>/sub-ADP0001F00nTJY/log/20241213-040009_81f8aa0a-634b-41e9-bba4-7f59128437d8/crash-20241213-041444-UID1005-raw_src-16e248c9-05dc-4df8-ab4b-c4258d0029b5.txt
Working Directory: /work/qsiprep_1_0_wf/sub_ADP0001F00nTJY_ses_0W_wf/dwi_preproc_ses_0W_acq_b0d6_dir_PA_wf/pre_hmc_wf/merge_and_denoise_wf/dwi_qc_wf/raw_src
Inputs:

    args:
    bvec_convention: FSL
    environ: {}
    grad_dev:
    input_b_table_file:
    input_bvals_file:
    input_bvecs_file:
    input_dicom_dir:
    input_nifti_file:
    num_threads: 1
    output_src:
    recursive:
    subject_id:
    test_trait:

Traceback (most recent call last):
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/plugins/multiproc.py", line 66, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 525, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 643, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/envs/qsiprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 769, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node raw_src.

Cmdline:
	dsi_studio --action=src  --bval=/work/qsiprep_1_0_wf/sub_ADP0001F00nTJY_ses_0W_wf/dwi_preproc_ses_0W_acq_b0d6_dir_PA_wf/pre_hmc_wf/merge_and_denoise_wf/merge_dwis/dwi_denoise_ses_0W_acq_b0d6_dir_PA__merged.bval --bvec=/work/qsiprep_1_0_wf/sub_ADP0001F00nTJY_ses_0W_wf/dwi_preproc_ses_0W_acq_b0d6_dir_PA_wf/pre_hmc_wf/merge_and_denoise_wf/merge_dwis/dwi_denoise_ses_0W_acq_b0d6_dir_PA__merged.bvec --source=/work/qsiprep_1_0_wf/sub_ADP0001F00nTJY_ses_0W_wf/dwi_preproc_ses_0W_acq_b0d6_dir_PA_wf/pre_hmc_wf/merge_and_denoise_wf/raw_merge/sub-ADP0001F00nTJY_ses-0W_acq-b0d6_dir-PA_run-1_dwi_merged.nii.gz --thread_count=1 --output=/work/qsiprep_1_0_wf/sub_ADP0001F00nTJY_ses_0W_wf/dwi_preproc_ses_0W_acq_b0d6_dir_PA_wf/pre_hmc_wf/merge_and_denoise_wf/dwi_qc_wf/raw_src/sub-ADP0001F00nTJY_ses-0W_acq-b0d6_dir-PA_run-1_dwi_merged.src.gz
Stdout:
	DSI Studio version: Hou "??" Aug  2 2024
	[1;34m??command line[0m
	[0;32msource[0m=/work/qsiprep_1_0_wf/sub_ADP0001F00nTJY_ses_0W_wf/dwi_preproc_ses_0W_acq_b0d6_dir_PA_wf/pre_hmc_wf/merge_and_denoise_wf/raw_merge/sub-ADP0001F00nTJY_ses-0W_acq-b0d6_dir-PA_run-1_dwi_merged.nii.gz
	[0;32maction[0m=src
	[0;32mloop[0m=/work/qsiprep_1_0_wf/sub_ADP0001F00nTJY_ses_0W_wf/dwi_preproc_ses_0W_acq_b0d6_dir_PA_wf/pre_hmc_wf/merge_and_denoise_wf/raw_merge/sub-ADP0001F00nTJY_ses-0W_acq-b0d6_dir-PA_run-1_dwi_merged.nii.gz
	1;34m??run src[0m
	1;35m??opening sub-ADP0001F00nTJY_ses-0W_acq-b0d6_dir-PA_run-1_dwi_merged.nii[0m
	convert 4D NIFTI to src
	576ms
	[0;32mbvec[0m=/work/qsiprep_1_0_wf/sub_ADP0001F00nTJY_ses_0W_wf/dwi_preproc_ses_0W_acq_b0d6_dir_PA_wf/pre_hmc_wf/merge_and_denoise_wf/merge_dwis/dwi_denoise_ses_0W_acq_b0d6_dir_PA__merged.bvec
	bval[0m=/work/qsiprep_1_0_wf/sub_ADP0001F00nTJY_ses_0W_wf/dwi_preproc_ses_0W_acq_b0d6_dir_PA_wf/pre_hmc_wf/merge_and_denoise_wf/merge_dwis/dwi_denoise_ses_0W_acq_b0d6_dir_PA__merged.bval
	cannot create SRC file: cannot find bval/bvec file[0m
	580ms
	584ms
Stderr:

Traceback:
	RuntimeError: subprocess exited with code 1.
```

**Comment by weiwei-wch** [comment]
> Can you try rerunning with version 1.0.2? We made a number of improvements to the grouping code, so hopefully it will work as intended now.

Hi, thanks for your brilliant work! It seems version 1.0.2 fixed this problem, even if I do not add  "MultipartID" tag in the json file.
But It still could not run throughly because of synthseg crash #951 , I see that this has already been pulled in  Update FreeSurfer #19 ，can this merge into a release version soonly so that we can finally finish a preprocessing with new version of QSIprep? @tsalo
